### ISSUE TITLE
[REQUEST] Add / binding for find option

### ISSUE THREAD

**Issue by repparw** [aristocratos/btop#101]
**Is your feature request related to a problem? Please describe.**
Almost all my cli programs use / for search, btop is the only one with the bind on f

**Describe the solution you'd like**
An option on settings to change the bind to / or a toggle to have both

**Describe alternatives you've considered**

**Additional context**

**Comment by krei-del** [comment]
Hello,
I think it would be still nice to have a "real" search function to jump within the list of running processes and threads within the tree view. Therefore you could see, where this thread/process is child of, where as in the filter version you can't see that information. For me that comes in handy with another feature that I have requested: accumulated RAM.
