### ISSUE TITLE
[BUG] ERROR: Unsupported platform (suse).

### ISSUE THREAD

**Issue by sbradnick** [aristocratos/btop#102]
**Describe the bug**

Getting "ERROR: Unsupported platform (suse)." for v1.0.17 ; <= v1.0.16 are building fine.

**To Reproduce**

General 'make' build/install procedure.

**Expected behavior**

I would expect it to build as prior versions do.

**Screenshots**

[    2s] Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.tl5Unw
[    2s] + umask 022
[    2s] + cd /home/abuild/rpmbuild/BUILD
[    2s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/btop-1.0.17-0.x86_64
[    2s] ++ dirname /home/abuild/rpmbuild/BUILDROOT/btop-1.0.17-0.x86_64
[    2s] + /usr/bin/mkdir -p /home/abuild/rpmbuild/BUILDROOT
[    2s] + /usr/bin/mkdir /home/abuild/rpmbuild/BUILDROOT/btop-1.0.17-0.x86_64
[    2s] + cd btop-1.0.17
[    2s] + /usr/bin/make -O -j4 V=1 VERBOSE=1
[    2s] Makefile:62: *** ERROR: Unsupported platform (suse).  Stop.
[    2s] error: Bad exit status from /var/tmp/rpm-tmp.tl5Unw (%build)
[    2s] 
[    2s] 
[    2s] RPM build errors:
[    2s]     Bad exit status from /var/tmp/rpm-tmp.tl5Unw (%build)

**Info (please complete the following information):**
 - btop++ version: 1.0.17
 - Binary: building in OBS => https://build.opensuse.org
 - (If compiled) Compiler and version: gcc (SUSE Linux) 11.2.1 20210816 [revision 056e324ce46a7924b5cf10f61010cf9dd2ca10e9]
 - Architecture: x86_64
 - Platform: Linux (openSUSE specifically)
 - (Linux) Kernel: 5.14.9-1-default
 - Terminal used: kitty
 - Font used: CaskaydiaCove Nerd Font

**Additional context**

contents of `~/.config/btop/btop.log`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run `gdb btop`

2. `r` to run, wait for crash and press enter

3. `thread apply all bt` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by sbradnick** [comment]
Sounds good, thanks for the quick attention 👍

**Comment by aristocratos** [comment]
Np :)
