### ISSUE TITLE
[BUG] ERROR: Runner thread died unexpectedly! SXHKD

### ISSUE THREAD

**Issue by Shinyzenith** [aristocratos/btop#12]
**Describe the bug**
btop crashes quite a few times while attempting to launch it via sxhkd
```
2021/09/21 (08:49:04) | ===> btop++ v.1.0.2
2021/09/21 (08:49:04) | ERROR: Runner thread died unexpectedly!
```
It works just fine when I manually launch my terminal and type `btop`

My sxhkd config:
```
# btop++ process viewer
super + b
	alacritty -e btop
```

**To Reproduce**
Attempt to launch btop via sxhkd

**Info (please complete the following information):**
 - btop++ version: 1.0.2
 - Architecture: x86_64
 - Platform: Arch Linux
 - (Linux) Kernel: 5.14.6-arch1-1
 - Terminal used: alacritty
 - Font used: jetbrains nerd fonts mono

**Comment by aristocratos** [comment]
@Shinyzenith 
Very likely the same issue as #10
If it is, it should be fixed in the latest commits, if you need binaries they will up later today.

**Comment by Shinyzenith** [comment]
Cool, thank you for the amazing app. ❤️
