### ISSUE TITLE
Is it possible to build for Darwin platfrom? Big Sur with M1 chip.

### ISSUE THREAD

**Issue by mutiev** [aristocratos/btop#120]
**Is your feature request related to a problem? Please describe.**
I know that the application not available for mac chips, and yeash, we are just business developers or looking for aesthetics, etc and we want btop for M1.

**Describe the solution you'd like**
Is it possible for python developer and some linux experience to adapt the code with low blood

**Describe alternatives you've considered**
Continue using old and nice looking `htop` 

**Additional context**

![image](https://user-images.githubusercontent.com/2060695/139107024-21765da5-a9ff-445d-bd8e-829ff7e016a1.png)

**Comment by martin-braun** [comment]
@aristocratos it would be nice to have the binary on homebrew, any plans on that?

**Comment by aristocratos** [comment]
@martin-braun #33
