### ISSUE TITLE
[BUG] Failed to join _runner thread

### ISSUE THREAD

**Issue by somera** [aristocratos/btop#122]
**Describe the bug**

btop is just crashing after long run. long > 1h.

**To Reproduce**

Just run it for a while.

**Info (please complete the following information):**
 - btop++ version: `btop -v` btop version: 1.0.20
 - Binary: [self compiled or static binary from release] self compiled
 - (If compiled) Compiler and version: g++ (10.3.0)
 - Architecture: [x86_64, aarch64, etc.] `uname -m` x86_64
 - Platform: [Linux, FreeBSD, OsX] Ubuntu
 - (Linux) Kernel: `uname -r` 5.4.0-89-generic
 - (OSX/FreeBSD) Os release version: 20.04.3
 - Terminal used: MobaXTerm with bash
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

```
2021/10/27 (19:49:03) | ===> btop++ v.1.0.20
2021/10/27 (19:49:03) | ERROR: Stall in Runner thread, restarting!
2021/10/27 (21:18:56) | ERROR: Failed to join _runner thread!
```

**Comment by somera** [comment]
I can't reproduce it at the moment. I try this again.

**Comment by somera** [comment]
I can't reproduce it.

**Comment by aristocratos** [comment]
Closing this for now then.
