### ISSUE TITLE
[BUG] Inconsistent vim keys behavior in the options menu

### ISSUE THREAD

**Issue by tiborsimon** [aristocratos/btop#128]
**Describe the bug**

When the `Vim keys` mode is turned on it behaves inconsistently in the `OPTIONS` menu. I can go up and down with the `j` and `k` keys and change the options with the `h` and `l` keys but only for the boolean options. For the multiple selection menu items (for example the `Color theme`, `Graph symbol`, `Selected battery`, `Log level` in the `general` tab, and many other in the other tabs) only the arrow keys can change the given option.

**To Reproduce**

Turn on `Vim keys` mode and use the options menu with the vim keys.

**Expected behavior**

The multi select options should also be able to changed with the `h` and `l` keys.

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.0.20`
 - Binary: `arch btop 1.0.20-2`
 - Architecture: `x86_64`
 - Platform: Linux
 - (Linux) Kernel: `5.10.75-1-lts`
 - Terminal used: `kitty 0.23.1`
 - Font used: `nerd-fonts-source-code-pro`

**Comment by aristocratos** [comment]
@tiborsimon 

Yup, fixed in latest commit.

**Comment by aristocratos** [comment]
Fixed in [v1.0.23](https://github.com/aristocratos/btop/releases/tag/v1.0.23)

**Comment by tiborsimon** [comment]
Verified with `btop 1.1.1` on arch. Perfect!
