### ISSUE TITLE
[BUG] Unexpected q key behavior in the main menu

### ISSUE THREAD

**Issue by tiborsimon** [aristocratos/btop#129]
**Describe the bug**

This might be not a bug, but an intended behavior, but I found it pretty unexpected that pressing the `q` key in the main menu makes `btop` to quit instead of just closing the main menu. When I first experienced this I thought that `btop` has crashed.

**To Reproduce**

Go into the main menu by pressing the `m` key on the main screen. The main menu appears. Press the `q` key which causes `btop` to quit.

**Expected behavior**

When you have the main menu open, pressing the `q` key should exit only from the main menu (like the `esc` key does), and it should not make `btop` to quit.

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.0.20`
 - Binary: `arch btop 1.0.20-2`
 - Architecture: `x86_64`
 - Platform: Linux
 - (Linux) Kernel: `5.10.75-1-lts`
 - Terminal used: `kitty 0.23.1`
 - Font used: `nerd-fonts-source-code-pro`

**Comment by aristocratos** [comment]
@tiborsimon 
Fixed in [v1.0.23](https://github.com/aristocratos/btop/releases/tag/v1.0.23)

**Comment by tiborsimon** [comment]
Thank you! Verified with `btop 1.1.1` on arch.
