### ISSUE TITLE
Disk calculation are incorrect [BUG]

### ISSUE THREAD

**Issue by cumminsd** [aristocratos/btop#134]
**Describe the bug**

The calculations for disk size, usage and free are incorrect. I ran out of disk space with BTop++ saying I had 5% free.

**To Reproduce**

Run BTop++ in one terminal window. 
Run: `watch df -h` in another terminal window. Note the differences in the disk numbers.

**Expected behavior**

The numbers in BTop++ should be accurate and match other system numbers.

**Screenshots**

![image](https://user-images.githubusercontent.com/11546198/139961214-f956d9fb-818a-4b47-b6b8-eb61bf3ab301.png)

![image](https://user-images.githubusercontent.com/11546198/139961253-75cfaabd-835a-402f-ab34-ef499d68f8b6.png)

**Info (please complete the following information):**
 - btop++ version: 1.0.21
 - Binary: Installed as per instructions. Downloaded release, extracted to folder, ran `sudo make install`
 - (If compiled) Compiler and version:
 - Architecture: x86_64
 - Platform: Ubuntu Linux
 - (Linux) Kernel: 4.15.0-161-generic
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Gnome Terminal
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

2021/11/02 (16:40:05) | ===> btop++ v.1.0.21
2021/11/02 (16:40:05) | DEBUG: Starting in DEBUG mode!
2021/11/02 (16:40:05) | INFO: Logger set to DEBUG
2021/11/02 (16:40:05) | DEBUG: Using locale en_US.UTF-8
2021/11/02 (16:40:05) | INFO: Running on /dev/pts/0

**Comment by aristocratos** [comment]
@cumminsd
The values are acquired through kernel function `statvfs` and are accurate.
You are comparing two different values, `available` and `free`.

From https://man7.org/linux/man-pages/man3/statvfs.3.html:
```
fsblkcnt_t     f_bfree;    /* Number of free blocks */
fsblkcnt_t     f_bavail;   /* Number of free blocks for
                              unprivileged users */
```

So the 5% left on your "full" disk was still there, but not available to "unprivileged users".

**Comment by cumminsd** [comment]
Ahhhh... gotcha. Makes sense.

Is there a way to have Btop++ only show what's available to the user? Or
maybe both? I open Btop++ and keep it up to monitor what I am doing,
particularly when I'm modifying large video files. I monitor CPU usage and
temp, as well as other things. When I was working on a project and Btop++
said I had 5% left but I started getting disk space errors, it was
confusing.

Thanks!
--Darin

**Comment by cumminsd** [comment]
Will do. Thanks!
