### ISSUE TITLE
[BUG] btop freezes when pressing `QUIT` from menu

### ISSUE THREAD

**Issue by Crilum** [aristocratos/btop#142]
**Describe the bug**

btop freezes when the `QUIT` menu button is pressed, instead of quitting, and the only way to close btop is by closing the terminal. 

**To Reproduce**

open btop, hit `m` or open menu, press `QUIT`

**Expected behavior**

I expected btop to quit to terminal.

**Screenshots**

Regular btop:

![btop](https://user-images.githubusercontent.com/91354257/140686516-27a39e5e-e42d-452a-a453-f1cd56d3d755.png)

Menu:

![menu](https://user-images.githubusercontent.com/91354257/140686536-589f501f-bce3-442a-8e8a-0e53392d6fcc.png)

Now after double clicking quit, btop freezes:

![frozen](https://user-images.githubusercontent.com/91354257/140686549-477d3ffb-2946-4600-a844-b4fa7f613c79.png)

**Info (please complete the following information):**
 - btop++ version: `1.0.22`
 - Binary: all arm releases ([armv7lr](https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-armv7r-linux-musleabihf.tbz), [armv7lm](https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-armv7m-linux-musleabi.tbz), [arch64](https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-aarch64-linux-musl.tbz))
 - (If compiled) Compiler and version:
 - Architecture: `[armv7lr](https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-armv7r-linux-musleabihf.tbz), [armv7lm](https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-armv7m-linux-musleabi.tbz), [arch64](https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-aarch64-linux-musl.tbz)`
 - Platform: [Raspberry Pi 4 4G, Raspberry Pi OS, buster, latest release]
 - (Linux) Kernel: I only know mine (armv7l): `5.10.63-v7l+`, @theofficialgman [reported](https://github.com/Botspot/pi-apps/pull/1121#issuecomment-962779361) for arm64.
 - (OSX/FreeBSD) Os release version: not applicable, unless you want the debian version, which, like I said above is `buster`.
 - Terminal used: lxterminal
 - Font used: `default`

**Additional context**

contents of `~/.config/btop/btop.log`:
```

2021/11/07 (14:24:44) | ===> btop++ v.1.0.22
2021/11/07 (14:24:44) | ERROR: Stall in Runner thread, restarting!
```

P.S. Thank you for releasing packages for arm debian!!!

**Comment by aristocratos** [comment]
@Crilum 
There was an issue when trying to clear the input from "mouse release" after "mouse click" on the quit button.

Fixed in latest commits.

**Comment by Crilum** [comment]
Thank you! It's fixed.
