### ISSUE TITLE
[BUG] btop leaves bash terminal affected after closing (breaks htop use)

### ISSUE THREAD

**Issue by theofficialgman** [aristocratos/btop#144]
**Describe the bug**

If btop is used in the terminal (tested with gnome-terminal, uxterminal, uxterm, uterm, and lxterminal) and then closed, any subsequent launches of applications which support mouse input are messed up (like htop and dialog)

Clicking no longer works properly with these other applications and causes strange issues in their GUI.

**To Reproduce**

Run btop and do whatever in it and close it. then run htop and notice mouse input no longer works properly

**Expected behavior**

btop does not affect other applications functionality once closed

**Screenshots**

video linked below

**Info (please complete the following information):**
 - btop++ version: v1.0.23
 - Binary: static binary from release
 - Architecture: aarch64
 - Platform: linux
 - (Linux) Kernel: 4.9.140+
 - Terminal used: gnome-terminal (as well as uxterm, uxterm, uterm, and lxterminal) bash 4.4.20

**Comment by theofficialgman** [comment]
hold on, somehow my video was corrupted, will fix in a sec

**Comment by theofficialgman** [comment]
https://drive.google.com/file/d/14qSrFTwBaVvE7RA4ozbJACzj0vR-OHfA/view?usp=sharing
ok this link should show the video

**Comment by aristocratos** [comment]
@theofficialgman 
Can't replicate this myself, but pushed a possible fix in latest commit.

**Comment by theofficialgman** [comment]
latest commit works as long as you exit with `q` or the exit in gui
ctrl+c still leaves it broken (not sure if you can fix that)

**Comment by Crilum** [comment]
I get exactly the same thing..

**Comment by Crilum** [comment]
When I click quit in the latest commit, it leaves this in the terminal:
```
0;64;24m
```

**Comment by theofficialgman** [comment]
> I get exactly the same thing.. Latest release.
@Crilum 
latest release doesn't have the changes, only the last from github actions
it only fixes it in new terminals (so if you ran old btop and then tried the new btop without opening a new terminal the issue still happens). And as I said it still happens with ctrl+C



> When I click quit in the latest commit, it leaves this in the terminal:
> 
> ```
> 0;64;24m
> ```

I can't replicate that. I don't have that issue

**Comment by Crilum** [comment]
Let me try it again, maybe it was a random thing..

**Comment by Crilum** [comment]
Yeah, sorry, it was just a random incident.. :rofl:

**Comment by Crilum** [comment]
> > I get exactly the same thing.. Latest release.
> 
> @Crilum latest release doesn't have the changes, only the last from github actions
> 
> it only fixes it in new terminals (so if you ran old btop and then tried the new btop without opening a new terminal the issue still happens). And as I said it still happens with ctrl+C

That's because btop won't exit with the escape codes.. `ctrl+c` just kills it, I think.

**Comment by theofficialgman** [comment]
@Crilum you can `TRAP` signal 2 (ctrl+c) in bash though I'm not sure if you want to do that or not

**Comment by Crilum** [comment]
@theofficialgman Haha, I was just about to say something like that..

**Comment by aristocratos** [comment]
@theofficialgman 
ctrl+c (SIGINT) is already trapped, but is briefly "untrapped" while in a thread context to avoid a deadlock, on a really slow machine there is a good chance of hitting it while "untrapped" and not triggering the right clean up. Working on a fix.

**Comment by aristocratos** [comment]
@theofficialgman @Crilum
Ok, a possible fix in latest commit, but will be a slight delay *sometimes* when pressing CTRL+C

**Comment by Crilum** [comment]
> Ok, a possible fix in latest commit, but will be a slight delay _sometimes_ when pressing CTRL+C

I think that's fine. I'll try it.

**Comment by Crilum** [comment]
Works great. I think that fixes it.

**Comment by aristocratos** [comment]
Will need confirmation from @theofficialgman that it's fixed since he opened the issue, before any new releases.

**Comment by theofficialgman** [comment]
@Crilum @aristocratos sorry couldn't test immediately (had to go do something)
just tried it now and works perfect!

**Comment by Crilum** [comment]
@aristocratos Any thoughts on when the next release will be?

**Comment by aristocratos** [comment]
@Crilum 
Fixed in [v1.0.24](https://github.com/aristocratos/btop/releases/tag/v1.0.24)

**Comment by Crilum** [comment]
Thanks @aristocratos!
