### ISSUE TITLE
disks dont display, some processes dont display name or command

### ISSUE THREAD

**Issue by kavemang** [aristocratos/btop#147]
Hi folks, recently discovered btop and loving it, I noticed that even when running btop with "sudo btop" my disks do not display and some processes do not display name or command only the PID. This is on ubuntu server. Is there a good starting point for trouble shooting that kind of issue? 

PS the same issue is present on my raspberry pi systems also running ubuntu server 

PPS any advice on getting core temp to work would be awesome also, cant see core temp in an amdA9 rig as well as my RPI4 systems

**Comment by jamesastound** [comment]
Works fine on my MacOS system (Monterey), but Ubuntu systems running. on my Dell servers (R510 / H700 RAID Controller), experience this problem. I will add, the network panel also does not update, even when specifying the interface name in the options.

![Screen Shot 2021-11-13 at 9 36 56 AM](https://user-images.githubusercontent.com/46630094/141649851-7ce44607-ee78-4ada-8c44-256702fbfa11.png)

Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme II BCM5716 Gigabit Ethernet (rev 20)

**Comment by aristocratos** [comment]
@jamesastound @kavemang 
I'm gonna guess you are both running the snap version and didn't read the install instructions?

**Comment by jamesastound** [comment]
Thank you, yes. Arrived from third-party site. RTFM. Apollogies.

**Comment by kavemang** [comment]
this is not a proud day
