### ISSUE TITLE
[BUG] Net usage not displayed

### ISSUE THREAD

**Issue by Theiremi** [aristocratos/btop#148]
I have discovered this software recently, and I love it !

But my net usage is not displayed, it stay to zero.
I have tried to launch the app with `sudo` and it doesn't work too.

Ask me more info if needed, I really want to use `btop` 😀

![Capture d’écran de 2021-11-12 17-41-36](https://user-images.githubusercontent.com/84141518/141502774-138eed6f-06af-44d7-8bf8-bae843c0aed3.png)

**Infos:**
 - btop++ version: 1.0.22
 - Binary: static binary from release
 - Architecture: x86_64
 - Platform: Ubuntu 20
 - (Linux) Kernel: 5.11.0-40-generic
 - Terminal used: gnome-terminal
 - Font used: default

Unfortunately btop.log is not created, even with `--debug` flag

**Comment by joske** [comment]
Maybe it's the wrong network card that shows. Try pressing b/n to select another.

**Comment by Theiremi** [comment]
Yes I have try that, I have tested with all the interfaces and it shows 0 in download and upload in any case.

**Comment by aristocratos** [comment]
@Theiremi 
Well I can see that you are running the snap version from your screenshot (which is not the same as "static binary from release").

Did you read the full instructions for the snap install?

**Comment by Theiremi** [comment]
It solve my problem, thank you ! 
I have installed btop with a command found in an other site and I don't have looked into readme
