### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WolfFlightTZW** [aristocratos/btop#162]
**Describe the bug**

Error message produced after running for a period of time

**To Reproduce**

run btop in terminal

**Expected behavior**

ERROR: Exception in runner thread -> Cpu:: -> graphs, clock, meter : basic_string::_M_create

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: btop version: 1.1.1
 - Binary:  static binary from release
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m`
 - Platform: [Linux, FreeBSD, OsX]
 - (Linux) Kernel: `4.15.0-128-generic
 - (OSX/FreeBSD) Os release version:
 - Terminal used: bash
 - Font used: FONTFACE="Fixed"

**Additional context**

contents of `~/.config/btop/btop.log`

2021/11/17 (19:40:50) | ===> btop++ v.1.1.1
2021/11/17 (19:40:50) | ERROR: Exception in runner thread -> Cpu:: -> graphs, clock, meter : basic_string::_M_create

2021/11/17 (20:30:53) | ===> btop++ v.1.1.1
2021/11/17 (20:30:53) | ERROR: Exception in runner thread -> Cpu:: -> graphs, clock, meter : basic_string::_M_create

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by syrphide** [comment]
I have the same issue with v.1.2.13:

2023/01/20 (13:08:57) | ===> btop++ v.1.2.13
2023/01/20 (13:08:57) | ERROR: Exception in runner thread -> Cpu:: -> graphs, clock, meter : basic_string::_M_create

**Comment by holdjun** [comment]
<img width="1031" alt="2024-01-22 14 23 55" src="https://github.com/aristocratos/btop/assets/16971410/781995ff-ad96-43d0-8aa2-2f2c98a4a0b9">
ERROR: Exception in runner thread -> Cpu:: -> graphs, clock, meter : basic_string::at: __n (which is 0) >= this->size() (which is 0)
same issue with 1.3.0

**Comment by imwints** [comment]
Please provide a back trace

**Comment by holdjun** [comment]
<img width="1246" alt="2024-01-22 19 09 49" src="https://github.com/aristocratos/btop/assets/16971410/c15125df-54f2-4c1d-8e7b-5dd346cba809">
@imwints

**Comment by imwints** [comment]
I can't reproduce the issue. Could you disable GPU support and try to narrow it down with GDB?

**Comment by holdjun** [comment]
It is indeed caused by the GPU reality; if the GPU is turned off, it won't crash. I understand that it is caused by the GPU displaying too many gpus

**Comment by imwints** [comment]
So this is different from the reports above which happened in v1.2.13?

**Comment by BrahR** [comment]
For any WSL users disabling the GPU should fix the issue too.
