### ISSUE TITLE
[BUG] Bad temperature readout on RHEL8 over SSH

### ISSUE THREAD

**Issue by cyqsimon** [aristocratos/btop#167]
## Description

Temperature readout is incorrect. This screenshot will do:
![shot-20211125-203225](https://user-images.githubusercontent.com/28627918/143442583-63cccc16-e752-4c72-8c13-173fa3f24302.png)

I only have access via SSH so I cannot verify if the issue persists if I login locally, although I suspect that's not relevant.

No errors during compile:
```
# make
 
 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.5
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++ (11.2.1)
THREADS    :| 12
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=12
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector 
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.1.1) Linux x86_64
Compiling src/btop_input.cpp
Compiling src/btop_theme.cpp
Compiling src/btop_menu.cpp
Compiling src/btop_config.cpp
Compiling src/btop_draw.cpp
Compiling src/btop.cpp
Compiling src/btop_tools.cpp
Compiling src/linux/btop_collect.cpp
-> obj/btop_input.o                (552KiB) (02s)
-> obj/btop_tools.o                (444KiB) (02s)
-> obj/btop_menu.o                 (884KiB) (02s)
-> obj/btop_theme.o                (572KiB) (02s)
-> obj/btop_config.o               (624KiB) (02s)
-> obj/btop.o                      (720KiB) (02s)
-> obj/btop_draw.o                 (1.4MiB) (03s)
-> obj/linux/btop_collect.o        (2.0MiB) (03s)

Linking and optimizing binary...
-> bin/btop                        (1.4MiB) (02s)

Build complete in (06s)
```

## To reproduce

1. Login via SSH to RHEL8.5 x64 system as root
2. `dnf install gcc-toolset-11` and `scl enable gcc-toolset-11 bash`
3. Clone and checkout `v1.1.1`
4. `make && make install`
5. Run `btop` and observe incorrect temperature readings

## Info

 - btop++ version: 1.1.1
 - Binary: locally compiled
 - Compiler and version: `gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)` (`scl enable gcc-toolset-11 bash`)
 - Architecture: x64
 - Platform: RHEL8.5
 - Kernel: `4.18.0-348.2.1.el8_5.x86_64`
 - Terminal used: Konsole

## btop.log

Nothing useful but anyways
```
2021/11/25 (12:38:58) | ===> btop++ v.1.1.1
2021/11/25 (12:38:58) | DEBUG: Starting in DEBUG mode!
2021/11/25 (12:38:58) | INFO: Logger set to DEBUG
2021/11/25 (12:38:58) | DEBUG: Using locale en_GB.UTF-8
2021/11/25 (12:38:58) | INFO: Running on /dev/pts/0
2021/11/25 (12:39:06) | INFO: Quitting! Runtime: 00:00:08
```

**Comment by cyqsimon** [comment]
I also tried using the statically linked musl build directly from https://github.com/aristocratos/btop/releases/tag/v1.1.1

Same result.

**Comment by joske** [comment]
What's the output of 
```bash
ls -lR /sys/devices/platform/coretemp.0/hwmon/
``` ?

Check the contents of files that start with temp and end with _input. In my system I find the following:
```bash
[jos@silence ~]$ cat /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input 
32000
```

**Comment by cyqsimon** [comment]
> What's the output of
> 
> ```shell
> ls -lR /sys/devices/platform/coretemp.0/hwmon/
> ```

There is in fact no `coretemp.0` directory under `/sys/devices/platforms`. These are the directory contents:
```
# pwd
/sys/devices/platform
# ls -A
 alarmtimer    AMDIF030:00         intel_rapl_msr.0   nct6775.656   pcspkr                   PNP0103:00   PNP0C14:00   serial8250   uevent
 AMDI0030:00  'Fixed MDIO bus.0'   microcode          PCCT          platform-framebuffer.0   PNP0C0C:00   power        sp5100-tco
```
Is this perhaps an indication that a dependency related to hardware monitoring is missing?

**Comment by aristocratos** [comment]
@cyqsimon 
Coretemp is only for intel cpus so it shouldn't be present on your ryzen system but install `lm-sensors` and run the command `sensors`, I believe it will prompt you for loading of kernel modules on first run if it can't detect any sensors. Then post the output of `sensors` and we can try to figure out what's going on.

**Comment by cyqsimon** [comment]
Ah okay. `lm-sensors` is already installed, but `sensors` reports all `-49`s on `Tccd1-8` so I guess that's where that came from. I also ran a `sensors-detect` with all default choices first for good measure, but output says the same.

Maybe `lm-sensors` always reports temps for 8 CCDs on Ryzen even when they (and/or their sensors) don't exist? But at this point I'm just guessing.

Here's the full output of `sensors`:
```
# sensors
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:          +0.0°C  
Tdie:          +0.0°C  
Tccd1:        -49.0°C  
Tccd2:        -49.0°C  
Tccd3:        -49.0°C  
Tccd4:        -49.0°C  
Tccd5:        -49.0°C  
Tccd6:        -49.0°C  
Tccd7:        -49.0°C  
Tccd8:        -49.0°C  

nct6796-isa-0290
Adapter: ISA adapter
in0:                    +0.41 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +1.69 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                    +3.44 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                    +3.33 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                    +1.85 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                    +1.10 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                    +1.24 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                    +3.42 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                    +3.26 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                    +0.91 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                   +1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   +0.63 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +1.05 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +0.91 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +0.90 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                     0 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                  1039 RPM  (min =    0 RPM)
fan5:                  1009 RPM  (min =    0 RPM)
fan6:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +34.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
CPUTIN:                 +36.5°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                +13.5°C    sensor = thermistor
AUXTIN1:                -60.0°C    sensor = thermistor
AUXTIN2:                +12.0°C    sensor = thermistor
AUXTIN3:                +31.0°C    sensor = thermistor
SMBUSMASTER 0:          +42.0°C  
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
PCH_CPU_TEMP:            +0.0°C  
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled
```

**Comment by cyqsimon** [comment]
Ah okay. So I found [this post on Reddit](https://www.reddit.com/r/Amd/comments/jr2e4l/amd_ryzen_5600x_temperature_monitor_ubuntu_linux/) which says that I might need quite a new kernel for Ryzen 3000 CPUs. Maybe that's why. Redhat usually backports features back to their older RHEL kernels but it might not have happened in this particular instance.

I will do a bit more research and try a couple more things. And if it is indeed not the issue of `btop` then I will have this issue closed. Thanks for all the help.

**Comment by aristocratos** [comment]
@cyqsimon 
Btop does indeed only read the information from the sensors already present in the `/sys/` filesystem, so doesn't effect the workings of the sensors in any way.

>  So I found this post on Reddit which says that I might need quite a new kernel for Ryzen 3000 CPUs.

This would be the actual issue. So the solution would be to either update kernel or try to backport the sensor modules with ryzen support.

**Comment by cyqsimon** [comment]
Seems like it's a redhat issue indeed: https://bugzilla.redhat.com/show_bug.cgi?id=2027084

I will now close issue; thanks again.
