### ISSUE TITLE
[BUG] Core temperature on macOS Monterey with Intel Chip is unavailable

### ISSUE THREAD

**Issue by bitweedx64** [aristocratos/btop#168]
**Describe the bug**

Temperature per core on macOS Monterey with Intel Chip is `-1 °C`.

**To Reproduce**

Compile and install the binary on main branch.

**Expected behavior**

Shows exact temperature on each core.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]
<img width="1184" alt="截屏2021-11-26 下午9 18 25" src="https://user-images.githubusercontent.com/83109252/143587067-77a696f0-1270-4e01-9555-0e567fdb2baf.png">

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.1.1`
 - Binary: [self compiled or static binary from release]
 - (If compiled) Compiler and version: self compiled
 - Architecture: [x86_64, aarch64, etc.] `x86_64`
 - Platform: [Linux, FreeBSD, OsX]
 - (OSX/FreeBSD) Os release version: 21.1.0
 - Terminal used: iTerm2
 - Font used:Iosevka

**Additional context**

contents of `~/.config/btop/btop.log`

```
2021/11/26 (21:19:54) | ===> btop++ v.1.1.1
2021/11/26 (21:19:54) | DEBUG: Starting in DEBUG mode!
2021/11/26 (21:19:54) | INFO: Logger set to DEBUG
2021/11/26 (21:19:54) | DEBUG: Using locale zh_CN.UTF-8
2021/11/26 (21:19:54) | INFO: Running on /dev/ttys004
2021/11/26 (21:20:01) | INFO: Quitting! Runtime: 00:00:07
```

hardware & software information
```
MacBook Pro (15-inch, 2018)
2.6Ghz 6-core i7
macOS Monterey 12.0.1
```

**Comment by ArthurJ** [comment]
+1

Goodbye.
Signed, Arthur Julião.


Em sex., 26 de nov. de 2021 às 10:20, BitWeed x64 ***@***.***>
escreveu:

**Comment by aristocratos** [comment]
@bitweedx64 @ArthurJ 
I don't have an Intel mac so can't do much testing on this, but do you guys have any other software that shows temperatures and if so could you post a screenshot, I'm interested in the names of the sensors for the cores.

We can also ask @joske if he wanna help out with this one since he wrote most of the macos code and I believe he has a Intel mac available?

**Comment by ArthurJ** [comment]
Actually, btop++ has the (die) temperature displayed, but lacks the
temperature for each core.

[image: btop.jpg]
And I could not find any program with that info. Yours bpytop, for example,
displays the same, but without the information per code:
[image: bpytop.jpg]
Bottom and iGlance shows kinda the same (probably same source as btop and
bpytop):
[image: bottom.jpg]
[image: iglance.jpg]

Powermetrics, on the other hand, seems to take temperatures from another
sensor:
[image: powermetrics_x_iglance.jpg]

Goodbye.
Signed, Arthur Julião.


Em dom., 28 de nov. de 2021 às 07:45, aristocratos ***@***.***>
escreveu:

**Comment by joske** [comment]
Can not reproduce on my hackintosh (i5 11600): 
![image](https://user-images.githubusercontent.com/532423/143781792-a21c79c8-9b3f-44a5-b8ca-c62dcf372923.png)

But, as this is a hackintosh, can not be sure real macs do the same. The macbook pro of my girlfriend is too old to compile btop on (it's a 2009 model, stuck on el capitan, can not even install homebrew on it). Will see if it can at least *run* a ready-made build, but won't be today...

**Comment by aristocratos** [comment]
@ArthurJ your screenshots wasn't included (seems to happen when posting via mail), so can't see any of the sensor names.

@joske I remember in bpytop @hacker1024 wrote the program [coretemp](https://github.com/hacker1024/coretemp) for the reason of getting temperatures for the cores since `psutil` don't have temperature detection on macos [bpytop#119](https://github.com/aristocratos/bpytop/issues/119). So we could likely look at his sources to get a better grasp on the SMC code for Intel macs.

**Comment by joske** [comment]
@bitweedx64 Can you try with attached binary?
[btop.zip](https://github.com/aristocratos/btop/files/7614342/btop.zip)

**Comment by yiktungho** [comment]
Hi,

I'm on btop++ v.1.1.3, I checked this "fix" was merged but I still have this exact issue.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]
![Btop_coretemp](https://user-images.githubusercontent.com/9135080/147582487-b97ba02e-2da3-48cb-95e6-0eb3b583dacb.jpg)
![Btop_version](https://user-images.githubusercontent.com/9135080/147582493-dd1304b9-b23a-466e-9ea1-8b31d7a18c4d.jpg)

**Info (please complete the following information):**

- btop++ version: 1.1.3
- Binary: Static Binary (installed using brew)
- Architecture: x86_64
- Platform: OSX
- (OSX/FreeBSD) Os release version: 12.1
- Terminal used: iTerm2
- Font used: Input Mono (Patched with Nerd Font Symbols)

**Additional context**

```2021/12/28 (23:34:13) | ===> btop++ v.1.1.3
2021/12/28 (23:34:13) | INFO: Logger set to DEBUG
2021/12/28 (23:34:13) | DEBUG: Using locale en_US.UTF-8
2021/12/28 (23:34:13) | INFO: Running on /dev/ttys005
2021/12/28 (23:34:13) | DEBUG: Loading theme file: /usr/local/share/btop/themes/adapta.theme
```

hardware & software information

Mac Mini (2018)
3.2 GHz 6-core Intel Core i7
macOS Monterey 12.1

extra notes

bpytop works fine on the same machine:

![bpytop_1](https://user-images.githubusercontent.com/9135080/147583926-5cf5bf51-a94a-4135-a260-8e9309232405.jpg)
![bpytop_2](https://user-images.githubusercontent.com/9135080/147583932-bbc8aeb5-35f0-4e8a-b6c3-cc3b44da1c7c.jpg)

I've been running btop in place of bpytop for a few weeks and it's still rather unstable. It sometimes crashes with the following errors:
![btop_crash](https://user-images.githubusercontent.com/9135080/147583265-50a081db-01e6-4fcc-9a69-9fc72149fa0b.jpg)
or the network meter stops logging traffic after a while. But I can't really reliably reproduce these issues nor I have the debug logs available from those events.
