### ISSUE TITLE
[BUG] "Mebibytes" should be "Mebibits" in options > net > Net *load

### ISSUE THREAD

**Issue by glibg10b** [aristocratos/btop#169]
**Describe the bug**

The description at options > net > Net download reads:

> Value in Mebibytes, default "100"

But the upper limit of the network graph is actually set to 13M (one eighth of 100M). This means that the option is actually in mebi*bits*.

**To Reproduce**

1. Go to options > net > Net download.
2. Set it to some value.
3. Exit the options.
4. Observe that the upper limit is one eighth of that.
5. Repeat for Net upload.

**Expected behavior**

Either the settings should be in mebi*bytes*, or the descriptions should use mebi*bits*.

**Screenshots**

I still have to get screenshots working lol

**Info (please complete the following information):**
 - btop++ version: 1.0.9
 - Binary: self compiled, from [gentoo-zh](https://github.com/microcai/gentoo-zh) overlay
 - The rest doesn't matter for this particular issue.

**Comment by aristocratos** [comment]
@glibg10b 
Oops, you're quite right :)
Will fix in next release.

**Comment by aristocratos** [comment]
Fixed in v1.1.2
