### ISSUE TITLE
please add plug for "removable-media" to btop so external drives will show

### ISSUE THREAD

**Issue by kavemang** [aristocratos/btop#170]
**Is your feature request related to a problem? Please describe.**
I use BTOP to monitor a media server which uses external drives mounted automatically, these drives do not appear in btop

**Describe the solution you'd like**
add the removable-media plug to the btop snap package 

**Describe alternatives you've considered**
not sure what an alternative to this would be

**Comment by aristocratos** [comment]
@kavemang 
@kz6fittycent maintains the snap package.

**Comment by kavemang** [comment]
It looks like issues cant be started in the fork (im not to familiar with github) will it be tracked here or should I msg him?

**Comment by aristocratos** [comment]
No, the tag in the message above should get his attention eventually :)

**Comment by kz6fittycent** [comment]
Done. Refresh to latest `--edge` release.

**Comment by kavemang** [comment]
thank you @kz6fittycent ! I can confirm the external drive is now showing , however I've confirmed that the raw path to the drive is mounted as "/external" however I cant filter for that drive from the btop menu using only /external as the drive to be selected for.  Once I try filtering the external drive disappears with the others 

is that possibly a different kind of issue @aristocratos ?

**Comment by aristocratos** [comment]
@kavemang 
Yeah the filter is not gonna work correctly for all mount points when running as a snap, due to the mount point in the snaps environment might be different. I'm not enough versed in snap to know definitively what it would be, but you could try `/mnt/external`, `/media/external`, `/media/<username>/external` things like that, there isn't really any easy fix for it either.

**Comment by aristocratos** [comment]
@kavemang 
I could possibly make the filter for disks match parts of the full mount point which would make `external` work regardless of the prefix, but you should make a separate request issue or I'm likely to forget.

**Comment by kz6fittycent** [comment]
Suggest we close this @aristocratos since the plug has been added to the snap per request. Unless you want to proceed with your idea in this same issue.
