### ISSUE TITLE
[BUG] Gruvbox color sheme

### ISSUE THREAD

**Issue by pietryszak** [aristocratos/btop#176]
**Describe the bug**

In gruvbox_dark.theme a theme`[main_bg]="#1d2021"` is not gruvbox dark theme palette color!
It should be: `theme[main_bg]="#282828"`

**To Reproduce**
Install btop and choose Gruvbox-dark theme

**Expected behavior**

Color same as https://github.com/morhetz/gruvbox (Gruvbox - dark mode palette)

Can you explain why  a different background color is used instead of the original one ?

**Comment by aristocratos** [comment]
@pietryszak
> Can you explain why a different background color is used instead of the original one ?

You would have to ask @BachoSeven who created the theme file for bashtop [e4485fc](https://github.com/aristocratos/bashtop/commit/e4485fc0e2a589c3170e204667d8011da9d26a2e) 2+ years ago.

**Comment by pietryszak** [comment]
> @pietryszak
> 
> > Can you explain why a different background color is used instead of the original one ?
> 
> You would have to ask @BachoSeven who created the theme file for bashtop [#92](https://github.com/aristocratos/bashtop/issues/92) 2+ years ago.

I think It's time to use proper colors to consistency with  original colors scheme.
The foreground has the wrong color too.

**Comment by pietryszak** [comment]
[gruvbox_dark.txt](https://github.com/aristocratos/btop/files/7637091/gruvbox_dark.txt)
I prepare version with only original Gruvbox colors

**Comment by aristocratos** [comment]
@pietryszak 
You are welcome to create a pull request with your suggested changes.

**Comment by pietryszak** [comment]
I just change a color for # Highlight color for keyboard shortcuts and then create a pull request. But I think how to name a theme, because someone may be like theme created by  @BachoSeven. Maybe the name is "Gruvbox-dark-v2" or something like that..

**Comment by aristocratos** [comment]
@pietryszak
We could give @BachoSeven some time to respond and if he doesn't mind, we change the current theme. If he does, we just create a new theme.

**Comment by BachoSeven** [comment]
Probably just used `#1d2021` because I thought it looked better (btw even though it's not the original background color it is part of the Gruvbox palette, namely black), however I don't mind at all so feel free to edit the theme with the correct gruvbox colors for foreground and background

**Comment by BachoSeven** [comment]
For comparison, if anyone is interested:

Theme I created at the time:
![image](https://user-images.githubusercontent.com/55460785/144333873-36cffb4b-f521-4869-bcad-551090e28b3b.png)

edited following gruvbox spec for bg/fg:
![image](https://user-images.githubusercontent.com/55460785/144333910-f304bb63-74ab-495b-8d8c-5c4587c39265.png)

**Comment by BachoSeven** [comment]
I would say, change the background because it looks nicer but keep `#a89984` (which is a gruvbox color) as Foreground, because as you can see from the pictures it gives a much better contrast in comparison to using `#ebdbb2` everywhere

**Comment by pietryszak** [comment]
I create a whole theme with hree color gradient
![image](https://user-images.githubusercontent.com/45850093/144337030-21111742-720e-4820-8372-46cddd2acfe9.png)
![image](https://user-images.githubusercontent.com/45850093/144337195-daf75dde-9195-484d-8615-fc56a8eb69dd.png)
But I can't create new pull request to main
