### ISSUE TITLE
[BUG] theme[free_end]= not show color if Free memory is less than 3%

### ISSUE THREAD

**Issue by pietryszak** [aristocratos/btop#179]
**Describe the bug**

Btop not show a colors in free if memory is very low

**To Reproduce**

Open btop
Use a lot of memory
Color of Free not show if Free is less than 3%

**Expected behavior**

theme[free_end]=  be showed even Free memory is less than 3%

**Screenshots**
![image](https://user-images.githubusercontent.com/45850093/144333752-5baf176c-1c1c-41c0-8ebb-94afbc709d11.png)
![image](https://user-images.githubusercontent.com/45850093/144334136-e4b1a5a5-a537-41b7-9ac4-bbf26ae19877.png)
![image](https://user-images.githubusercontent.com/45850093/144334237-2d79fd5a-aa22-4099-afef-a29232fe11ae.png)

**Info:**
 - btop++ version: 1.1.2
 - Binary: self compiled
 - (If compiled) Compiler and version: g++ (11.2.1)
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.15.4-201.fc35.x86_64
 - Linux Os release version: Fedora 35
 - Terminal used: Kitty and Terminator
 - Font used: MesloLGS NF Regular 16px

**Additional context**

contents of `~/.config/btop/btop.log`

`
2021/12/02 (01:13:29) | ===> btop++ v.1.1.2
2021/12/02 (01:13:29) | DEBUG: Starting in DEBUG mode!
2021/12/02 (01:13:29) | INFO: Logger set to DEBUG
2021/12/02 (01:13:29) | DEBUG: Using locale en_US.UTF-8
2021/12/02 (01:13:29) | INFO: Running on /dev/pts/5
2021/12/02 (01:13:29) | DEBUG: Loading theme file: /usr/local/share/btop/themes/gruvbox_dark.theme
2021/12/02 (01:13:47) | INFO: Quitting! Runtime: 00:00:18
`

**Comment by aristocratos** [comment]
@pietryszak 
That's just how the math of the graph representation works. In the example above you have 3 rows of characters and each character has 4 dots on the vertical axis giving us a total of 12 dots representing 0-100%.
`100 / 12 = 8.3`
0 dots = 0 - 8.3 %
1 dot = 8.4 - 16.6 %
And so on...
This gives the best possible vertical resolution for the graph.

**Comment by pietryszak** [comment]
> @pietryszak That's just how the math of the graph representation works. In the example above you have 3 rows of characters and each character has 4 dots on the vertical axis giving us a total of 12 dots representing 0-100%. `100 / 12 = 8.3` 0 dots = 0 - 8.3 % 1 dot = 8.4 - 16.6 % And so on... This gives the best possible vertical resolution for the graph.

So I close Issue if it is the best possible resolution
