### ISSUE TITLE
[possible BUG] - install location on centos

### ISSUE THREAD

**Issue by daniejstriata** [aristocratos/btop#18]
**Describe the bug**

The installer script installs btop++ to /usr/local/bin/btop. On Centos this does not appear to be in path for 7 and 8. When I symlink it to /usr/local/sbin/btop it is found and executed.

**Expected behavior**

as btop runs with super user requirements will it not make sense to install it to /usr/local/sbin/ instead?

**Comment by aristocratos** [comment]
@daniejstriata
The `PREFIX` variable defaults to `/usr/local/bin` if not set by user which is default behaviour in most makefiles.
Running as superuser is not a requirement, the `make setuid` command is optional and added for convenience, so defaulting to `/usr/local/sbin` wouldn't be a good fix.

Might I suggest that you add `/usr/local/bin` to your path instead, since that's the path most user installed software will end up by default...

**Comment by daniejstriata** [comment]
It only seems to happen on Mint. My Fedora 34 setup does not have this issue. Closing.

**Comment by daniejstriata** [comment]
@aristocratos I would like to continue the discussion and point out another issue.

1. Install script always add `bin` in-front of the binary. This will cause undesired installation:
Install command:
`make install PREFIX=/usr/local/sbin`
Output:
`Installing binary to: /usr/local/sbin/bin/btop`
I would've expected the install script to honour the path I gave it without adding `bin`.

2. By default Centos 7 also do not include the default path to /usr/local/bin. That makes sense from this statement below.

```/usr/local/bin is for programs that a normal user may run. /usr/local/sbin is for system administration programs (which are not part of the core OS) that a local administrator may run. By default, a normal user does not have /usr/local/sbin on their path.```

Would  /usr/local/sbin not be the better install location without having to make changes to everyone's path?

**Comment by aristocratos** [comment]
@daniejstriata 
btop++ is not a "system administration program" it's a system monitor like `top`, `ps` or `htop` and just like them belongs in `*/bin`.
The PREFIX variable defines where the desired top level folder containing `bin` and `share` is located.
The themes and readme also uses the PREFIX to get correct location.
If you really want btop in your `sbin` folder you're gonna have to move it yourself or write a script to do it for you.

> That makes sense from this statement below.

What? If you got `/usr/local/sbin` in your path by default and not `/usr/local/bin`, it's the complete opposite of the cited statement...

**Comment by daniejstriata** [comment]
@aristocratos What that statement tries to say is if I'm root I have in path sbin. If I'm  a regular use then I would not.

Have you seen my other commend about the make script always prepending the binary with bin?

**Comment by aristocratos** [comment]
@daniejstriata 
The first line of the statement `/usr/local/bin is for programs that a normal user may run` applies here, there is no need to be `root` to run btop, it gives you more capabilities (like killing any process), but it's not designed to only be run by a superuser.

> Have you seen my other commend about the make script always prepending the binary with bin?

Yes, and as I explained above, the PREFIX variable isn't supposed to be pointed at the binary location, but the folder above your binary location. `/bin/` is added on the PREFIX path to get it to the binary folder, just as `/share/btop/` is added on the PREFIX path to get the themes in the correct location.

**Comment by aristocratos** [comment]
@daniejstriata 
If the goal is to get the default install path changed to `/usr/local/sbin` you're gonna have to be dissapointed.

I'm not sure why you see it as a problem to add `/usr/local/bin` to your path?

**Comment by daniejstriata** [comment]
@aristocratos Thank you for your explanation. I'm seeing the light. I'm updating my process.
