### ISSUE TITLE
Add new theme onedark

### ISSUE THREAD

**Issue by vtmx** [aristocratos/btop#187]
https://gist.github.com/vtmx/0c40acfede063ef58e0ebf7d3b4cf174

![screenshot](https://i.imgur.com/fdhnxLW.png)

**Comment by pietryszak** [comment]
Looks good, nice work.

**Comment by aristocratos** [comment]
Agreed!
@vtmx if you create a PR I'll merge it.

**Comment by vtmx** [comment]
@aristocratos glad you liked it, I created the PR.
