### ISSUE TITLE
[BUG] how to open tbz in centos?

### ISSUE THREAD

**Issue by linyongfu2013** [aristocratos/btop#188]
**Describe the bug**

how to open tbz in centos?  google not found solution.

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: `btop -v`
 - Binary: [self compiled or static binary from release]
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m`
 - Platform: [Linux, FreeBSD, OsX]
 - (Linux) Kernel: `uname -r`
 - (OSX/FreeBSD) Os release version:
 - Terminal used:
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by linyongfu2013** [comment]
why use such rare file type ? why not zip tgz ....?

**Comment by aristocratos** [comment]
@linyongfu2013 
https://www.google.com/search?q=how+to+open+tbz+in+centos

**Comment by Gerrit-K** [comment]
@aristocratos sorry for digging this up again, but what about the other question?
> why use such rare file type ? why not zip tgz ....?

I.e., is there any *major* benefit in choosing bzip over gzip here? IMO, although bzip may be faster or result in smaller archives, gzip is much more widely known and supported (as can be seen by this issue), which is a key factor of OSS to me.

**Comment by aristocratos** [comment]
Also, unless you're using a non GNU version of `tar` or a very outdated one, the command to unpack is the same for both gzip and bzip2 -> `tar -xf archive.t*z`

**Comment by Gerrit-K** [comment]
Well, "rare" wouldn't have been my choice of words, I just quoted the original issue author ;)
I know that bzip2 is also very common and installed on most systems, but still it seems to me that the de facto standard for GitHub binaries is `*.tgz`. So I'm simply asking if diverging from that was a deliberate choice and (if so) want to know the intention behind that :)

**Comment by aristocratos** [comment]
> So I'm simply asking if diverging from that was a deliberate choice and (if so) want to know the intention behind that :)

It's just for the better compression. The decompress time (for the release package) will be under 1 second for probably any machine made in the last 15 years for both gzip and bzip2. So didn't really see any reason to not go for better compression.

The reason bzip2 not working with zinit could maybe be an oversight of the author specifying the `-z` flag for `tar` and not letting `tar` autodetect the compression. So if you find the part of the sources for handling compressed files you could possibly submit a PR with a fix yourself.

**Comment by Gerrit-K** [comment]
Awesome! Thanks for the explanation and especially thanks for going the extra mile to take a look at my specific issue with `zinit` 👏  much appreciated!
I'll take a look and see if I can provide a fix there. Shouldn't be too difficult based on your findings.

**Comment by aristocratos** [comment]
@Gerrit-K 
No problem :)

Just a note if you submit a patch, you would also need to add `tbz` to the accepted file list on line 1575 in zinit-install.zsh
