### ISSUE TITLE
[BUG] - text wrapping in CPU graph - btop 1.0.4

### ISSUE THREAD

**Issue by daniejstriata** [aristocratos/btop#19]
**Describe the bug**

There is some text from the Load Average that spans to the next line.

**To Reproduce**

This happens to me all the time.

**Expected behavior**

Load AVG Should not span across multiple lines.

![btop-1 0 04](https://user-images.githubusercontent.com/13314239/134295424-f3e6a3c5-9e0b-4f53-922f-3bc004e5a2c3.png)

**Comment by aristocratos** [comment]
@daniejstriata 
Is fixed in latest commits. If you need binaries it will be up later today.

**Comment by daniejstriata** [comment]
Thank you. Closing.
