### ISSUE TITLE
[BUG] Setting network bandwidth past 10Gbit breaks the network graph

### ISSUE THREAD

**Issue by acaos** [aristocratos/btop#191]
**Describe the bug**

Setting network bandwidth (either manually or automatically) past 10 Gbit/s breaks the network graph (causing it to display 163P in the scale field, and the graph is always full).

**To Reproduce**

1. Go to the menu.
2. Go to the network tab.
3. Disable automatic scaling and set either the upload or download bandwidth to 40000 or some other high number (the system I was using it on has 40Gbit interfaces).

**Expected behavior**

The network bandwidth graph works as expected on systems with interfaces >10Gbit.

**Screenshots**

![image](https://user-images.githubusercontent.com/295044/145304642-28247dc7-629a-4f98-a0e9-462f689e034f.png)

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.1.2`
 - Binary: static binary from release
 - (If compiled) Compiler and version:
 - Architecture: `x86_64`
 - Platform: Linux
 - (Linux) Kernel: `3.10.0-1160.el7.x86_64`
 - (OSX/FreeBSD) Os release version:
 - Terminal used:
 - Font used:

**Additional context**

No log present, no crash detected.

**Comment by aristocratos** [comment]
@acaos 
Missplaced some parentheses, should be fixed in latest commit.

**Comment by acaos** [comment]
I can confirm this solves the problem for me. Thank you!
