### ISSUE TITLE
[BUG] CPU over 100% usage

### ISSUE THREAD

**Issue by Crylia** [aristocratos/btop#20]
**Describe the bug**

While compiling something my CPU spikes over 100% well into the 300% area in the proc tree

It might be interesting to note that it only occured when a single process was going ham at the cpu, if i compile clang++ over multiple processes i have no problem anymore

**To Reproduce**

Compile unreal engine from source

**Expected behavior**

CPU Should be maxed at 100% with all proc combined

**Screenshots**

Bug example
![Bug example](https://i.imgur.com/NnHqcUo.png)

Working example
![Working example](https://i.imgur.com/iHY8PhQ.png)

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.0.4`
 - Binary: `static binary from release`
 - Architecture: `x86_64`
 - Platform: `Linux`
 - (Linux) Kernel: `5.13.0-7614-generic`
 - (OSX/FreeBSD) Os release version: `Pop!_OS 21.04`
 - Terminal used: `Alacritty`
 - Font used: `MesloLGS`

`2021/09/22 (09:29:34) | ===> btop++ v.1.0.4
2021/09/22 (09:29:34) | ERROR: Terminal size to small for current config.
(WxH) Current: 94x22 | Needed: 80x24
Resize terminal or disable some boxes in config file to fix this.`

**Comment by aristocratos** [comment]
@Crylia 
![image](https://user-images.githubusercontent.com/59659483/134310307-4066351a-2203-46c3-939a-93f99acd24fa.png)
