### ISSUE TITLE
Disk Filter / lvm2 / cryptsetup

### ISSUE THREAD

**Issue by ralphee** [aristocratos/btop#203]
I am trying to` Exclude=/boot` unfortunately once entered all my disks disappear.  

btop version: 1.1.3
Architecture: x86_64
Platform: Linux
Arch Linux: 5.10.84-1-lts
Terminal: Alacritty

**Comment by RedBearAK** [comment]
If you're capitalizing "Exclude" like that, it won't work. That causes all my disks to disappear too. 

Use `exclude=/boot` instead. See if that works.
