### ISSUE TITLE
Graphical issue whtn high number of cores

### ISSUE THREAD

**Issue by cattaneod** [aristocratos/btop#21]
When the number of CPU cores/threads is high (>99), there are two graphical issues:
- cores above 99 are shown as 10, 11 instead of 100, 110, etc.
- when the terminal window is not full screen (e.g., when is resized to occupy only half of the screen), the CPU usage graph overlap with the list of processes.

**Screenshots**
![image](https://user-images.githubusercontent.com/11426917/134337182-77778165-7f43-4e04-bf5e-5558ff2b8e48.png)
![image](https://user-images.githubusercontent.com/11426917/134337227-0271e990-13c6-466f-be09-868f93a6beef.png)

EDIT: The same happen with CPU and NET graphs
![image](https://user-images.githubusercontent.com/11426917/134339712-d1aaf4a9-0303-4e12-b41c-2d27b26375f8.png)

**Comment by aristocratos** [comment]
@cattaneod 
Found the problem (and some other issues)
Fixed in [v1.0.7](https://github.com/aristocratos/btop/releases/tag/v1.0.7)
