### ISSUE TITLE
Disk IO display is covered and obscured by the upper and lower triangle signs

### ISSUE THREAD

**Issue by xhsky** [aristocratos/btop#212]
**Describe the bug**

Disk IO display is covered and obscured by the upper and lower triangle signs

**Info (please complete the following information):**
 - btop++ version: 1.1.3
 - Binary: btop-x86_64-linux-musl.tbz
 - Architecture: x86_64 and aarch64
 - Platform: Centos7, UOS, linuxmint
 - Terminal used: gnome-terminal

**Additional context**
2021/12/15 (16:51:58) | ===> btop++ v.1.1.3
2021/12/15 (16:51:58) | DEBUG: Starting in DEBUG mode!
2021/12/15 (16:51:58) | INFO: Logger set to DEBUG
2021/12/15 (16:51:58) | DEBUG: Using locale zh_CN.UTF-8
2021/12/15 (16:51:58) | INFO: Running on /dev/pts/6
2021/12/15 (16:51:58) | DEBUG: Loading theme file: /opt/btop/share/btop/themes/dracula.theme

**Comment by aristocratos** [comment]
@xhsky 
This would be an issue between you and your font.
Btop assumes all fonts are correctly spaced and have no control in how your fonts are presented, only your font and your terminal have control over that.
