### ISSUE TITLE
Makefile doesn't pull any files as prerequisites.

### ISSUE THREAD

**Issue by stwnt** [aristocratos/btop#216]
**Describe the bug**

For some reason the ```.d``` files created by GCC are empty. If you change any code in dependend files it doesn't lead to a recompile of the source file.

**To Reproduce**

Just compile the program and look in the build directory.

**Expected behavior**

The ```.d``` files should contain a full make target with all sources and headers the current target depends on.
So if you recompile the program, any changes made in those files result in a recompiled ```.o``` file.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - `btop -v`: 1.1.3
 - self compiled
 - GCC 10.2.1, 11.2.0
 - `uname -m` x86_64, aarch64
 - Linux
 - `uname -r` 5.10 and 5.15

There is actually a simple solution, i can make a pull request of you want to.

**Comment by aristocratos** [comment]
@stwnt 
Good catch, and yes please feel welcome to submit a PR with a fix to the Makefile.

**Comment by stwnt** [comment]
Closed with #218.
