### ISSUE TITLE
[BUG] Konsole, some text disappearing

### ISSUE THREAD

**Issue by THEGODFATHERRX** [aristocratos/btop#219]
Konsole, text view bug.

Temperature text getting cut off after sometime.
 tested with other terminals on my system (kitty, and gnome terminal), works perfectly with them, I dont think its a resize or font size issue, as changing them does not help, btw, my font is 'Hack', its monospace, changing font does not help.
when I start btop in Konsole, I can see the temperature, however after sometimes the temperature text slowly moves out of the screen to the left. 

open Konsole,
run btop
see the temperature text disapearing into the left side.

https://i.imgur.com/zb07nOu.png

**Info (please complete the following information):**
 - btop++ version: `btop -v`
1.1.3
installed using pacman.
 - Architecture: [x86_64, aarch64, etc.] `uname -m`
  x86_64
 - Platform: [Linux, FreeBSD, OsX]
  Manjaro Linux
 - (Linux) Kernel: `uname -r`
 5.12.19-1-MANJARO
 - Terminal used:
 Konsole
- Font used:
Hack and Monospace
**Additional context**

contents of `~/.config/btop/btop.log`
`2021/12/14 (18:38:54) | ===> btop++ v.1.1.2
2021/12/14 (18:38:54) | INFO: Logger set to INFO

2021/12/17 (11:54:16) | ===> btop++ v.1.1.2
2021/12/17 (11:54:16) | ERROR: Stall in Runner thread, restarting!

2021/12/17 (15:11:13) | ===> btop++ v.1.1.3
2021/12/17 (15:11:13) | ERROR: No tty detected!
btop++ needs an interactive shell to run.

2021/12/20 (20:23:18) | ===> btop++ v.1.1.3
2021/12/20 (20:23:18) | DEBUG: Starting in DEBUG mode!
2021/12/20 (20:23:18) | INFO: Logger set to DEBUG
2021/12/20 (20:23:18) | DEBUG: Using locale en_US.UTF-8
2021/12/20 (20:23:18) | INFO: Running on /dev/pts/3
2021/12/20 (20:23:27) | INFO: Quitting! Runtime: 00:00:09
`

**Comment by THEGODFATHERRX** [comment]
I just notcied, even the CPU percentage numbers are disappearing into the left, it can be seen in the screenshot.

btw, should I take a video of the text disappearing?

**Comment by THEGODFATHERRX** [comment]
Here is a video

https://user-images.githubusercontent.com/61771930/146788993-2400fb99-f064-4b4d-b06e-3e0b54448e55.mp4

**Comment by THEGODFATHERRX** [comment]
https://user-images.githubusercontent.com/61771930/146800164-6b43ee1a-83a4-43e0-b15f-a085ee6ef2f7.mp4

Ignore the calculator widget that appears in the background when I restart btop.
I have cropped the video because personal information can be seen.

**Comment by aristocratos** [comment]
@THEGODFATHERRX 
[README.md -> Notice text rendering issues](https://github.com/aristocratos/btop#notice-text-rendering-issues)
