### ISSUE TITLE
Error while running on WSL 1.0

### ISSUE THREAD

**Issue by LinuxTux23** [aristocratos/btop#22]
Dear community:

I have tried to install the latest version of btop inside of WSL 1.0 and encountered some issue. After the installation process has finished successfully, I tried to launch btop, but there is only an error message showing up:

`-bash: /usr/local/bin/btop: cannot execute binary file: Exec format error`

**Did someone encounter this problem before, or know the solution for this problem?**

regards:

Benedikt

**Comment by aristocratos** [comment]
You're using a binary for a different architecture then your own...
