### ISSUE TITLE
[BUG] btop incorrectly reports ram

### ISSUE THREAD

**Issue by skulldealer** [aristocratos/btop#225]
**Describe the bug**
Comparing ram usage shown by "btop" with "htop" and "free -m" gives different results

**To Reproduce**
Try comparing ram usage shown by "btop" with "htop" and "free -m"

**Expected behavior**
Values should be very close/same.
and
Total=USED+AVAILABLE
Available=FREE+CACHED

**Screenshots**
![SS_22-51-21_Sat_25⁄12⁄21](https://user-images.githubusercontent.com/77295140/147390284-010736b5-f9a2-4151-95a0-8455c34219c5.png)

**Info (please complete the following information):**
btop version: 1.1.3
Binary: static binary from release
Architecture: x86_64
Platform: Linux
(Linux) Kernel: 5.11.0-43-generic
Terminal used: Tilix
Versions
	Tilix version: 1.9.1
	VTE version: 0.60
	GTK Version: 3.24.20
Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
Font used: Fira Code Retina

**Additional context**
contents of `~/.config/btop/btop.log`
[btop.log](https://github.com/aristocratos/btop/files/7776084/btop.log)
contents of `~/.config/btop/btop.conf`
[btop.conf.txt](https://github.com/aristocratos/btop/files/7776085/btop.conf.txt)

**Comment by aristocratos** [comment]
@skulldealer 
Not a bug, the values are collected directly from the kernel. Your assumptions of what the labels mean are incorrect.
See https://man7.org/linux/man-pages/man5/proc.5.html and search for `/proc/meminfo` for the actual meaning.
For more details about what "available" is, see the [kernel commit message](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773) from Linus Torvalds himself.
