### ISSUE TITLE
[BUG] sorting is inconsistant

### ISSUE THREAD

**Issue by bgkillas** [aristocratos/btop#226]
**Describe the bug**

sorting is only based off of 1 variable then randomized after it seems

**To Reproduce**

turn to command sorting and find the kthread programs 

**Expected behavior**

not have the programs jump around at random

**Screenshots**

https://user-images.githubusercontent.com/55570525/147397315-d52f746b-97db-4b48-a237-781938f3d67a.mp4

**Info (please complete the following information):**
 - btop++ version: `1.1.3`
 - Binary: arch repo
 - (If compiled) arch repo:
 - Architecture: [x86_64, aarch64, etc.] `x86_64`
 - Platform: [Linux]
 - (Linux) Kernel: `5.15.11`
 - (OSX/FreeBSD) Os release version:
 - Terminal used: kitty
 - Font used: noto sans mono

**Additional context**

contents of `~/.config/btop/btop.log`
``2021/12/25 (21:26:19) | ===> btop++ v.1.1.3
2021/12/25 (21:26:19) | INFO: Logger set to DEBUG
2021/12/25 (21:26:19) | DEBUG: Setting LC_ALL=en_US.UTF-8
2021/12/25 (21:26:19) | INFO: Running on /dev/pts/4``

**Comment by aristocratos** [comment]
@bgkillas 
Sorting is perfectly consistent, any possible ordering are correct for items that lack the chosen sorting property (as long as they are below they ones with a value), so it's doing exactly what you are asking it to do.
If you want a stable ordering sort by PID.

I'm not sure if I see much benefit to a second order sorting of the unsorted items, will only increase cpu usage and if you are interested in "following" those items you could just sort by a value the have instead, like "program".

**Comment by bgkillas** [comment]
so there is no plan to implement this into btop from bpytop?

**Comment by aristocratos** [comment]
@bgkillas 
This is not a feature in bpytop either. The reason you might experience a difference is because if the "arguments" field is empty in bpytop, it's automatically filled with the program name enclosed in brackets. This is however not a good practice since processes can be confused for some kernel processes that have this behavior.

**Comment by bgkillas** [comment]
https://user-images.githubusercontent.com/55570525/147429680-fd8c2afc-0385-4aa3-a33c-a3668938812e.mp4

well then with threads sorting it is obviously sorted from top to bottom lower pid to higher pid

i dont see why this cant be an option it makes it so much more usable with anything besides pid sorting and pid sorting in tree mode does not even work so its just dumb

**Comment by aristocratos** [comment]
@bgkillas 
Obviously pid sorting in the tree view is not gonna be a perfect ordering (then it wouldn't be a tree anymore).

But I have changed the sorting function from `rng::sort()` to `rng::stable_sort()` in the latest commit.
Try the binary from the [Continuous Build Linux](https://github.com/aristocratos/btop/actions/runs/1626597001), I believe this is the behavior you were looking for?

**Comment by bgkillas** [comment]
yes that is
