### ISSUE TITLE
[BUG] Cut up displayed CPU usage+temp

### ISSUE THREAD

**Issue by Jacksack2000** [aristocratos/btop#228]
Somethings wrong with the "braille display option" for the CPU usage and temp.
It is sliced / truncated
Didn´t do anything.
Used it right after the install.

![btop](https://user-images.githubusercontent.com/90605780/147861531-2f878274-4a5d-416e-b729-527fb4d57529.png)

When Using the tty or block display option everything´s fine

![btop2](https://user-images.githubusercontent.com/90605780/147861588-04c61381-8060-4d87-99a6-afaec7a38918.png)

Any Idea what is wrong?

**Comment by Jacksack2000** [comment]
forgot to mention,

using KDE Konsole (Plasma 5.23)

**Comment by aristocratos** [comment]
@Jacksack2000 
Read README.md -> https://github.com/aristocratos/btop#prerequisites
