### ISSUE TITLE
[REQUEST] Display system hostname

### ISSUE THREAD

**Issue by Ypnose** [aristocratos/btop#229]
**Is your feature request related to a problem? Please describe.**
I manage a big pool of servers and I monitor some of them with `btop`. Sometimes, it's hard to distinguish what server is being monitored.

**Describe the solution you'd like**
Display system hostname at the left / right of the clock.

Thanks your work, anyway.

**Comment by aristocratos** [comment]
![image](https://user-images.githubusercontent.com/59659483/149290549-e8075a10-302d-4f81-a2f8-84bac9a3f96a.png)
