### ISSUE TITLE
[BUG] disks section ignores /tmp on zram

### ISSUE THREAD

**Issue by eu41** [aristocratos/btop#230]
disks section of btop ignores /tmp when it is mounted on zram.

Gentoo system using zram-init, with zram0 used for swap (1GB) and zram1 used for /tmp (2GB).

Info:
 - btop++ version: 1.1.4
 - Binary: self compiled
 - (If compiled) Compiler and version: gcc-11.2.0
 - Architecture: aarch64 on Raspberry Pi 4
 - Platform: Linux
 - (Linux) Kernel: 5.15.13-v8
 - Terminal used: console
 - Font used: n/a

**Comment by aristocratos** [comment]
@eu41 
Have you disabled `Only physical` in the `Options menu` -> `mem`?

**Comment by eu41** [comment]
My bad, I did not spot that option when browsing through the menu.
Sorry and please close the bug.
Thanks,
Eugen

**Comment by aristocratos** [comment]
No problem :)
