### ISSUE TITLE
[BUG] No UTF-8 locale detected!

### ISSUE THREAD

**Issue by jsmoment** [aristocratos/btop#231]
**Describe the bug**

when i launch btop it says
`No UTF-8 locale detected!
Use --utf-force argument to force start if you're sure your terminal can handle it.`
even though my i have a utf 8 locale generated, it works when i add the --utf-force argument
**To Reproduce**

1.  try to launch btop
**Expected behavior**

btop launches

**Screenshots**

![image](https://user-images.githubusercontent.com/75227863/148648168-7e75bf28-2e5c-4712-8fb8-c2df17efbd47.png)

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: `btop -v`
 - Binary: static binary from the community repository
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] x86_64
 - Platform: [Linux, FreeBSD, OsX] Linux
 - (Linux) Kernel: `uname -r` 5.15.13-zen1-1-zen
 - (OSX/FreeBSD) Os release version:
 - Terminal used: kitty
 - Font used: i don't know what to put here

**Additional context**

contents of `~/.config/btop/btop.log`

`
2022/01/08 (15:32:15) | ===> btop++ v.1.1.4
2022/01/08 (15:32:15) | ERROR: No UTF-8 locale detected!
Use --utf-force argument to force start if you're sure your terminal can handle it.`

**Comment by aristocratos** [comment]
@jsmoment 
The UTF-8 detection is programmed to be very forgiving, so even if it fails to set any found locales it will continue.
But in this case it couldn't even detect a UTF-8 locale.

What output do you get from `echo $LANG '|' $LC_ALL`

If they are both empty and you are certain you have correctly [generated UTF-8 locales and setup the correct config files](https://wiki.archlinux.org/title/locale), you can set the `LANG` variable in your shells `.rc` file to a valid locale and it should work.

**Comment by jsmoment** [comment]
> @jsmoment The UTF-8 detection is programmed to be very forgiving, so even if it fails to set any found locales it will continue. But in this case it couldn't even detect a UTF-8 locale.
> 
> What output do you get from `echo $LANG '|' $LC_ALL`
> 
> If they are both empty and you are certain you have correctly [generated UTF-8 locales and setup the correct config files](https://wiki.archlinux.org/title/locale), you can set the `LANG` variable in your shells `.rc` file to a valid locale and it should work.

i had to reinstall arch because i broke my filesystem and no longer have this issue

**Comment by megumew** [comment]
I thought I had this bug but my install just didn't have the locale set. I had generated the locale during install but never set it. I believe this is most likely what [jsmoment](https://github.com/jsmoment) did by accident as well. This issue did help me find the solution so I am thankful for that!
