### ISSUE TITLE
[REQUEST] Addition of option for gpu info and graph

### ISSUE THREAD

**Issue by devpartap** [aristocratos/btop#233]
like btop++ has windows for memory, cpu, net etc.. it will make it the best if it also has gpu window too for gpu stats.

thanks for the software :)

**Comment by danjenson** [comment]
I like this idea too, something like `nvtop`

**Comment by aristocratos** [comment]
From README.md ->

> 18 September 2021
> The Linux version of btop++ is complete. Released as version 1.0.0
> 
> I will be providing statically compiled binaries for a range of architectures in every release for those having problems compiling.
> 
> For compilation GCC 10 is required, GCC 11 preferred.
> 
> Please report any bugs to the Issues page.
> 
> The development plan right now:
> 
> 1.1.0 Mac OsX support
> 1.2.0 FreeBSD support
> 1.3.0 Support for GPU monitoring
> 1.X.0 Other platforms and features...
> Windows support is not in the plans as of now, but if anyone else wants to take it on, I will try to help.

**Comment by ma-sadeghi** [comment]
Hi @aristocratos, thank you for creating this great package! 

Can I ask what the timeline is (roughly) with respect to the GPU support? Thanks once again!
