### ISSUE TITLE
[REQUEST] Support for android

### ISSUE THREAD

**Issue by Iamafnan** [aristocratos/btop#235]
Is there any plan to add support for Android (termux)?

**Comment by aristocratos** [comment]
@Iamafnan 
Not on my part. But if anyone is passionate about it they are free to submit fixes to any currently existing issues.

**Comment by wallentx** [comment]
I tried, but this is as far as I've gotten. No disk info (I could probably get that), no CPU graph, and no network info

![Image](https://github.com/user-attachments/assets/8ff672a8-2856-457e-9cc5-b5ea64e3a971)

**Comment by spergware** [comment]
> I tried, but this is as far as I've gotten. No disk info (I could probably get that), no CPU graph, and no network info
> 
> ![Image](https://github.com/user-attachments/assets/8ff672a8-2856-457e-9cc5-b5ea64e3a971)

Are you rooted? How did you managed to install it anyway? Thanks

**Comment by wallentx** [comment]
@spergware not rooted. I just had to change a bunch of stuff that was causing btop to fail. I wasn't intending on pushing this or anything, and was just seeing if I could get it to build and run, so it wouldn't surprise me if my changes break functionality on anything outside of termux
https://github.com/wallentx/btop/tree/wallentx/termux

**Comment by spergware** [comment]
@wallentx well I dug up the thing a lil bit because I like to get my hands dirty and while I didn't manage to compile in main Termux I did it in proot-distro, and with root it runs just fine, the only stat that it didn't manage to pick was gpu data, for all the rest no problem at all. Jfytk
