### ISSUE TITLE
[BUG] TUI lines unaligned using the JetBrains Mono Font

### ISSUE THREAD

**Issue by BetaLost** [aristocratos/btop#239]
Title says it. If I change the font to anything else then the lines appear just fine, but if I change it to a JetBrains Mono font, the lines are unaligned.

**To Reproduce**

Just change your terminal font to JetBrains Mono and you'll see it.

**Expected behavior**

The lines should be aligned with the corners like all other fonts.

**Screenshots**

https://i.imgur.com/DeY7DOr.png

**Info (please complete the following information):**
 - btop++ version: btop version: 1.1.4
 - Binary: From the Arch User Repository.
 - (If compiled) Compiler and version:
 - Architecture: x86_64
 - Platform: Arch Linux
 - (Linux) Kernel: 5.15.13-arch1-1
 - Terminal used: Alacritty
 - Font used: JetBrainsMono Nerd Font

**Comment by aristocratos** [comment]
@BetaLost 
Read README.md -> https://github.com/aristocratos/btop#prerequisites

**Comment by BetaLost** [comment]
Turns out this issue happens because of the terminal emulator not the program.
