### ISSUE TITLE
[REQUEST] put some configuration into cache

### ISSUE THREAD

**Issue by c02y** [aristocratos/btop#24]
**Is your feature request related to a problem? Please describe.**

I notice two issues:
1. When I update my btop to a new version, the version number in the first line `Config file for btop v.` of `~/.config/btop/btop.conf` file will change
2. when I exit btop with a different layout, some parts of the btop.conf will be different

The btop.conf file should only be modified when you manually modify it.

**Describe the solution you'd like**

Put those parts that are easy to change into another file such as `~/.cache/btop/btop.conf`, since I sync my btop.conf with git in dotfiles, every time the btop changes, it is annoying that I got a new modification in my dotfiles.

**Describe alternatives you've considered**

**Additional context**

**Comment by aristocratos** [comment]
@c02y 
So you want there to be a secondary config file because you think " it is annoying that I got a new modification in my dotfiles".

How about no.

**Comment by c02y** [comment]
Actually, it is not a second configuration file, it is a temporary cache file to keep the previous state.

I use so many cli tools, and this is the first tool that it changes its configuration file by itself, normally under this situation, they all save its temporary file into `~/.cache` or `~/.local/share/`.

Or maybe another suggestion:
1. Delete the unnecessary version number in the configuration file
2. discard the state in configuration file (do not modify the configuration file when exiting btop from a different layout)

I just suggest that this kind of traditional rule should be followed, of course, this is your project, you can ignore it if you insist.
