### ISSUE TITLE
[BUG] Total network traffic stuck at 4GB on 32 bit systems

### ISSUE THREAD

**Issue by pixelbart80** [aristocratos/btop#240]
**Describe the bug**

On 32-bit systems, the total upload/download values get stuck at 3.99GB

**To Reproduce**

- Build btop on a 32 bit system
- Start btop with network view
- Generate 4GB of network traffic

**Expected behavior**

Rollover behavior like in bpytop, so if the 32 bit rx_bytes or tx_bytes values rollover, the old value is stored and added to the new value.

**Info (please complete the following information):**
 - btop++ version: 1.1.4
 - Binary: self compiled
 - Compiler and version: gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
 - Architecture: arm7l
 - Platform: Linux
 - Kernel: 5.10.63-v7l+
 
**Additional context**

(I'm new here and I don't know how to do a proper pull request. Sorry!)

The issue seems to be in btop_collect.cpp, line 1101. The max() prevents 'val' from being less than the last read value of rx_bytes or tx_bytes, so the rollover behavior is never triggered.

[btop_32bit_rollover.diff.txt](https://github.com/aristocratos/btop/files/7857120/btop_32bit_rollover.diff.txt)

**Comment by aristocratos** [comment]
@pixelbart80 #224
Ah man, you're right! Cant believe I missed that when I added the rollover code :P
Great catch, thank you!

Will push a fix shortly.

**Comment by pixelbart80** [comment]
Missing easy bugs is part of every programmer's life :)

Thanks for the quick fix (and for the great tool btw)! I've tested it on above configuration with multiple rollovers for upload and download, everything seems to work correctly.
