### ISSUE TITLE
[REQUEST] apt repository for btop++

### ISSUE THREAD

**Issue by laundmo** [aristocratos/btop#241]
**Is your feature request related to a problem? Please describe.**
Installs from a downloaded file make it hard to update, especially having forgotten how it was originally installed.

**Describe the solution you'd like**
An apt repository I can add, from which I can `apt(-get) install` btop++.

**Describe alternatives you've considered**
an official snap would also be nice, that's definitely a valid alternative

**Comment by aristocratos** [comment]
@laundmo 
Read README.md -> https://github.com/aristocratos/btop#installing-the-snap

**Comment by laundmo** [comment]
what about apt? i somehow missed the snap (mostly because its not listed in the table at the top with the other packages) but i still think a apt way to install this would be nice.
