### ISSUE TITLE
[BUG] btop.cfg file is not being auto-generated

### ISSUE THREAD

**Issue by joaoportela** [aristocratos/btop#243]
**btop.cfg is not being auto-generated**

In the [documentation](https://github.com/aristocratos/btop#configurability) it says "btop.cfg: (auto generated if not found)", but even after running btop a few times, the file `$HOME/.config/btop/btop.cfg` doesn't exist.

**To Reproduce**

1. Install btop
2. Start btop
3. Exit btop

**Expected behavior**

A config file was created at `$HOME/.config/btop/btop.cfg`.

**Actual behavior**

No file to be found. Even the folder `$HOME/.config/btop` doesn't exist.

**Screenshots**

N/A

**Info (please complete the following information):**
 - btop++ version: `btop version: 1.1.4`
 - Binary: static binary from release.
 - Platform: Linux
 - (Linux) Kernel: `5.11.0-46-generic`
 - Terminal used: N/A
 - Font used: N/A

**Additional context**

* No `~/.config/btop/btop.log` file found.
* `XDG_CONFIG_HOME` env var is unset.

**GDB Backtrace**

N/A

**Comment by joaoportela** [comment]
I found what part of the problem is. I installed btop using snap.

Looking for the logs (`find / -name btop.log 2> /dev/null`) I found the correct directories:

* `$HOME/snap/btop/278/.config/btop/btop.log`
* `$HOME/snap/btop/273/.config/btop/btop.log`

There probably isn't anything you can do about this. Should I close the issue?

**Comment by aristocratos** [comment]
@joaoportela 
If you type `snap info btop` or visit https://snapcraft.io/btop you will see:

> Logs, et cetera are located: `~/snap/btop/current/.config/btop`

So no, nothing I can do about it since snap is running sandboxed.

**Comment by joaoportela** [comment]
Thanks. And sorry to bother you. 😅

**Comment by romelsalwi** [comment]
I'm facing this issue, and in my case:

cannot access '/home/l3m0r/snap/btop/current/.config': No such file or directory

I'm running Btop on Arch linux.

**Comment by planet36** [comment]
In README.md, should "btop.cfg" be replaced with "btop.conf"?

**Comment by aristocratos** [comment]
@planet36 Yes it should, and done :)
