### ISSUE TITLE
[BUG]thanks 4 closing 

### ISSUE THREAD

**Issue by Jacksack2000** [aristocratos/btop#244]
Thanks for closing the thread/issue.

Your comment didn't help at all

**Comment by aristocratos** [comment]
Thanks for reading the README.

Here I'll qoute it and hilight the relevant part for you:

> Notice (Text rendering issues)
> If you are having problems with the characters in the graphs not looking like they do in the screenshots, it's likely a problem with your systems configured fallback font not having support for braille characters.
> 
> See Terminess Powerline for an example of a font that includes the braille symbols.
> 
> See comments by @sgleizes link and @XenHat link in issue #100 for possible solutions.
> 
> **_If text are misaligned and you are using Konsole or Yakuake, turning off "Bi-Directional text rendering" is a possible fix._**
> 
> Characters clipping in to each other or text/border misalignments is not bugs caused by btop, but most likely a fontconfig or terminal problem where the braille characters making up the graphs aren't rendered correctly.
> 
> Look to the creators of the terminal emulator you use to fix these issues if the previous mentioned fixes don't work for you.
