### ISSUE TITLE
[REQUEST] Stop blocking right click.

### ISSUE THREAD

**Issue by donuts-are-good** [aristocratos/btop#245]
**Is your feature request related to a problem? Please describe.**
When btop is running, I still want to be able to right-click the terminal window unobstructed. Running btop disrupts that.

**Describe the solution you'd like**
Stop doing that.

**Describe alternatives you've considered**
htop

**Additional context**
If I'm missing this in the settings somewhere, I can't tell.

**Comment by aristocratos** [comment]
@donuts-are-good 
Since btop has mouse support it's up to your specific terminal how it handles right clicks.

But it will likely pass on the right click if you hold `shift` while clicking.
If not, look at the documentation/help for you specific terminal emulator.

**Comment by donuts-are-good** [comment]
Thank you, that works.
