### ISSUE TITLE
[BUG] Process tree view don't disappear on collapse a branch

### ISSUE THREAD

**Issue by mrdotx** [aristocratos/btop#25]
**Describe the bug**

When I close a branch in the process tree view, the processes under that branch are moved to the bottom of the list.

**To Reproduce**

Close a branch and scroll down to the end of the list.

**Expected behavior**

The processes should disappear.

**Screenshots**

![screenshot-1](https://user-images.githubusercontent.com/46796031/134476520-e19a6854-3c41-4136-8acf-a8bd1ff01f88.png)
![screenshot-2](https://user-images.githubusercontent.com/46796031/134476525-47e42618-3abc-4b12-a60d-c01c3a77dec4.png)
![screenshot-3](https://user-images.githubusercontent.com/46796031/134476529-b7b97855-4215-4979-b3f0-25601fda92a7.png)

**Info (please complete the following information):**
 - btop++ version: 1.0.5
 - Binary: self compiled
 - (If compiled) Compiler and version:  11.1.0, 10.2.0
 - Architecture: x86_64,  armv7l
 - Platform: Linux
 - (Linux) Kernel: 5.14.6-zen1-1-zen, 5.10.63-9-ARCH
 - (OSX/FreeBSD) Os release version:
 - Terminal used: urxvt, st, tty

**Comment by aristocratos** [comment]
@mrdotx 
Should be fixed in latest commits.

**Comment by mrdotx** [comment]
I compiled the git source code with the latest commits. After a short test it works as expected. Thanks!

**Comment by mrdotx** [comment]
Sorry that I reopen this issue, but the slider on the right side doesn't end with the list, if the last process tree is collapsed.

![screenshot](https://user-images.githubusercontent.com/46796031/134545949-b6035103-8b01-45d9-bf01-5a2f8a6b9bcf.png)

**Comment by aristocratos** [comment]
I'm not seeing this myself: 
![image](https://user-images.githubusercontent.com/59659483/134561326-ecdf97c6-1a95-4a57-ac59-992b7b794223.png)

Did you `make clean` before compiling with latest commits?

**Comment by aristocratos** [comment]
@mrdotx 
Found the problem, sleep deprived mathematics :)
Fixed in [v1.0.7](https://github.com/aristocratos/btop/releases/tag/v1.0.7)

**Comment by mrdotx** [comment]
Thank you, works as expected ;)
