### ISSUE TITLE
[BUG]brew install error

### ISSUE THREAD

**Issue by duyuyouci** [aristocratos/btop#251]
brew install btop

Warning: No available formula with the name "btop". Did you mean btpd?
==> Searching for similarly named formulae...
This similarly named formula was found:
btpd
To install it, run:
  brew install btpd

**Comment by aristocratos** [comment]
@duyuyouci 
I'm guessing your not on one of the homebrew supported platforms?

> macOS (x86_64 & ARM64) / Linux (x86_64)

See https://formulae.brew.sh/formula/btop

If you are on a supported platform you'll need to report your issue to https://github.com/Homebrew/homebrew-core
I didn't create the formula.
