### ISSUE TITLE
[BUG] Theme settings not saved between snap updates

### ISSUE THREAD

**Issue by kz6fittycent** [aristocratos/btop#252]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

I'm not sure why, but the `btop` snap isn't saving the theme settings during refreshes. For example, if I choose "`gruvbox_material_dark`" and the snap refreshes, the default theme is applied. It's **NOT** a big deal, but I can foresee someone getting annoyed. 

`bpytop` and `bashtop` don't seem to have this issue, so it leads me to believe it might be something in the base code for `btop`. I can see in `btop.conf` that  the theme is noted there (see below), but it doesn't seem to survive a refresh. Any ideas?

```
color_theme = "/snap/btop/293/usr/local/share/btop/themes/flat-remix.theme"
```

**To Reproduce**

Set theme, refresh `btop` to newer version. Note theme has changed.

**Expected behavior**

Retain theme settings between refreshes. 

**Info (please complete the following information):**
 - btop++ version: `1.2.0`
 - Binary: snap
 - Architecture: `x86_64`
 - Platform: Linux (Pop!_OS)
 - (Linux) Kernel: `5.15.15-76051515-generic`
 - Terminal used: Terminator
 - Font used: UTF-8

**Additional context**

contents of `~/.config/btop/btop.log`:

```

[TRUNCATED]

2022/01/18 (21:34:11) | ===> btop++ v.1.2.0
2022/01/18 (21:34:11) | ERROR: Invalid RGB decimal value: "2"

2022/01/18 (21:53:03) | ===> btop++ v.1.2.0
2022/01/18 (21:53:03) | WARNING: Failed to join _runner thread on exit!

2022/01/18 (21:56:08) | ===> btop++ v.1.2.0
2022/01/18 (21:56:08) | WARNING: Failed to join _runner thread on exit!

2022/01/24 (12:04:18) | ===> btop++ v.1.2.0
2022/01/24 (12:04:18) | ERROR: Invalid RGB decimal value: "2"
```

**Comment by aristocratos** [comment]
@kz6fittycent 
Btop does nothing different from bashtop and bpytop in regards of the config file. A new config file is only created if no one exists. 

The only way I could see this happening is if the .config file is included in the snap package?
Which could possibly happen if the binary is started during the snap build process?

**Comment by kz6fittycent** [comment]
I'll check the build logs to see what it's doing. The only directory that persists between builds is `$SNAP_USER_COMMON`, which may be why the config is changing between updates.

**Comment by kz6fittycent** [comment]
Here are the build logs: https://launchpadlibrarian.net/583229777/buildlog_snap_ubuntu_focal_amd64_f580518366f2293e82287f00927e7f92_BUILDING.txt.gz 

Let me know if you can see the logs. I don't see any reference to `btop` binary being started.

**Comment by kz6fittycent** [comment]
I don't know what's causing this to occur so closing it makes sense to me. It's likely something to do with the snap not saving settings between refreshes.

**Comment by kz6fittycent** [comment]
I don't know what's causing this to occur so closing it makes sense to me. It's likely something to do with the snap not saving settings between refreshes.
