### ISSUE TITLE
[BUG] Incomplete CPU cores temperature

### ISSUE THREAD

**Issue by superbonaci** [aristocratos/btop#26]
For some reason, default btop display doesn't show properly cores temperature:

![](https://i.imgur.com/feVrkYL.jpg)

**Comment by superbonaci** [comment]
Also text next to percentage is partially covered by the % symbol:

![](https://i.imgur.com/shJXP7P.jpg)

**Comment by aristocratos** [comment]
@superbonaci 
Read the README.md! [Prerequisites (Read this if you are having issues!)](https://github.com/aristocratos/btop#prerequisitesl)

**Comment by superbonaci** [comment]
It's an issue with Yakuake. With Terminator works fine.
