### ISSUE TITLE
[REQUEST] Sending real time signals to process

### ISSUE THREAD

**Issue by bagnaram** [aristocratos/btop#262]
It would be great to specify sending real time signals when selecting the "Send Signal" function.

Perhaps having a SIGRTMIN+n option where N can be specified as the real time signal number. Many thanks!

**Comment by aristocratos** [comment]
@bagnaram 
As indicated in the box:
![image](https://user-images.githubusercontent.com/59659483/152926024-d12beecf-5632-471c-949a-250cd97066cd.png)

You can send any signal (up to the max allowed of 64).
Just type in the number.

Wasn't really much point in including another 32 signals that are unspecified in the selector.

**Comment by bagnaram** [comment]
Many thanks, I did not realize the interface allowed the user to input an arbitrary signal ID. Maybe as a future enhancement, the tool could read user-specific POSIX signal numbers from `/usr/include/bits/signum-arch.h` (or the system equivalent) and display the current selected signal or some such.
