### ISSUE TITLE
[BUG] Program doesn't recover after terminal size restoration

### ISSUE THREAD

**Issue by monstrous-moonshine** [aristocratos/btop#263]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

While I was using btop++ with dwm, the program stopped working with a message saying it needs at least 80 cols and 24 rows when it was pinched into a smaller window by the window manager (because another window was opened). However, when the offending window was closed and the btop++ window was restored to its previous size, the program didn't resume working.

**To Reproduce**

Use btop++ in a tiling window manager and open more windows until the btop++ window becomes too small. Restore the size by closing one or more of the previously opened windows.

**Expected behavior**

Resume working when window size is restored.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: 1.2.0
 - Binary: package manager (Arch)
 - (If compiled) Compiler and version:
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.16.5-arch1-1
 - (OSX/FreeBSD) Os release version:
 - Terminal used: st
 - Font used: DejaVu Sans Mono

**Additional context**

contents of `~/.config/btop/btop.log`

2022/02/08 (17:59:52) | ===> btop++ v.1.2.0
2022/02/08 (17:59:52) | DEBUG: Starting in DEBUG mode!
2022/02/08 (17:59:52) | INFO: Logger set to DEBUG
2022/02/08 (17:59:52) | DEBUG: Using locale en_US.UTF-8
2022/02/08 (17:59:52) | INFO: Running on /dev/pts/1
2022/02/08 (18:00:25) | INFO: Quitting! Runtime: 00:00:33

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by aristocratos** [comment]
@monstrous-moonshine 
I believe this might be a bug that was introduced when changing some input related code in v1.1.4
Would you mind testing version [1.1.3](https://github.com/aristocratos/btop/releases/tag/v1.1.3) and see if this is the case.

Normal operation should resume when pressing any key when it freezes.
Have noticed similar behavior on my own system in rare cases.
Just haven't had time to look into it yet.

**Comment by monstrous-moonshine** [comment]
@aristocratos 
Thanks for your reply! You're right, pressing a random key brought it back to working (v1.1.4). Previously, I'd only tried 'q' to quit. Also, as you said, v1.1.3 resumed working right when the window size went back to big enough.

**Comment by aristocratos** [comment]
@monstrous-moonshine 
Should be fixed in latest commits, see the [continuous build](https://github.com/aristocratos/btop/actions/runs/1818672134) for binaries.
