### ISSUE TITLE
[BUG] btop does not calculate character count of UTF-8 correctly

### ISSUE THREAD

**Issue by KSXGitHub** [aristocratos/btop#265]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

btop uses the wrong method to count characters. It seems to not take into account that window titles could contain wide unicode characters (such as emojis, Chinese characters, Japanese characters, etc.).

**To Reproduce**

**Step 1:** Create a file named `このプログラムは2GBのメモリを消費します.sh` with the following content:

```sh
#!/bin/bash
set -o errexit -o pipefail -o nounset
echo 'Consuming RAM. Press Ctrl-C to stop.' >&2
while true; do
  echo {0..8388608} >/dev/null
done
```

**Step 2:** Run the script

```sh
bash 'このプログラムは2GBのメモリを消費します.sh'
```

**Step 3:** Open another terminal and launch `btop`.

**Expected behavior**

The command of the spawned process stays within the "Command" column. The table is in shape.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/11488886/153405441-f3a4616f-3049-4663-8844-2c57e0f68687.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.0
 - Binary: [self compiled or static binary from release]
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m`
 - Platform: [Linux, FreeBSD, OsX]
 - (Linux) Kernel: `uname -r`
 - (OSX/FreeBSD) Os release version:
 - Terminal used:
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by aristocratos** [comment]
@KSXGitHub 
Hi, I'm aware of the issue, the following is the code used to calculate the length of a UTF-8 string:
https://github.com/aristocratos/btop/blob/951423dba56543d9804f79561fe5580c394306f6/src/btop_tools.hpp#L135-L139

I have a toggle `wide` used for things like program and command names that can contain wide characters but I haven't found a way to reliably determine exactly _how_ wide a character is, only if it is wider than 1 "normal" character (in most cases).
Assuming 2 works for most commonly used wide characters on a english language system including most emoji characters.

But would need some help from people with a little more in-depth knowledge of the UTF-8 encoding to fix the algorithm to accurately count the width.

**Comment by KSXGitHub** [comment]
@aristocratos I have attempted converting a string of UTF-8 characters to an array of single characters in Python, Node.js, and Rust. They all result in correct characters. Flag emojis being broken up into 2 or more characters, but this shouldn't be a problem since most terminal emulators break up emoji flags anyway (at least, the ones I use). If you can somehow copy the algorithm used by Python, Node.js, and Rust to count characters then I think it is solved.

**Comment by aristocratos** [comment]
@KSXGitHub 
The issue isn't really how to count the number of UTF-8 characters. It's determining how many columns in the terminal one character takes up (the symbol width).

This might however also be up to the author of the terminal emulator and could therefor vary between terminals.

But I do have a solution to fix it without actually fixing UTF-8, I can manually place the different stat columns instead of writing it as one line. This will get all the columns in the correct place, but if the command name is _too_ long it might still spill over on to the other side of the screen. But should at least make it usable until I come up with a better solution.

**Comment by aristocratos** [comment]
@KSXGitHub 
I don't think you get what I mean.

Try running the following in a terminal
```bash
echo -e "test2fkor🔴sda🔴sd443ghgf\ntest2fkorosdaosd443ghgf"
```

Both lines will have the same amount of UTF-8 characters but will not be the same "width" because the red circles take up 2 spaces instead of 1.

**Comment by KSXGitHub** [comment]
I see. So Terminals do respect character width. Let me test some more.

**Comment by aristocratos** [comment]
Yeah the same can be seen with the filename you posted.
Below is the same amount of the characters with "normal" width
```bash
このプログラムは2GBのメモリを消費します
ssssssssssssssssssss
```

**Comment by KSXGitHub** [comment]
It seems that crate `unicode_width` ([docs](https://docs.rs/unicode-width/0.1.9/unicode_width/index.html) | [repo](https://github.com/unicode-rs/unicode-width)) in Rust has to correct algorithm

![screenshot of the test program](https://user-images.githubusercontent.com/11488886/153613160-a0dc1735-5ac5-44fb-b16f-53f1b7e8ddc1.png)

**Comment by aristocratos** [comment]
@KSXGitHub 
Try latest commit, should fix the issue. Binaries in the [continuous build](https://github.com/aristocratos/btop/actions/runs/1830921768).

UTF8 widths is still not fixed, just band-aided by ignoring the "command" column width and manually resetting postion...
I used https://github.com/ridiculousfish/widecharwidth to get the width (based on the same source as the rust repo uses), but it still doesn't seem to get correct sizes.

**Comment by aristocratos** [comment]
Fixes included in v1.2.1

**Comment by KSXGitHub** [comment]
BTW, I just noticed this: How does the memory usage column display 1.5GB? Both rounding up to 2GB and rounding down to 1GB make 0.5GB error, which is 50%, which is not at all representative of the data. I think you should display at least 1 fractional, this way, displaying 1.55GB as 1.6GB would make only 0.1GB error (which is 6.4%). For reference, I encountered the same problem when I built a tool called parallel-disk-usage.

**Comment by aristocratos** [comment]
@KSXGitHub 
The function that "humanizes" the size in bytes has toggle for shortening the output (only showing first letter in the unit, and rounding floats), shouldn't be an issue to add check that keeps the fractional if the the value is below 10 (thus keeping it at max 4 characters).

But open a new issue for that or I'll likely forget.

**Comment by KSXGitHub** [comment]
> But open a new issue for that or I'll likely forget.

https://github.com/aristocratos/btop/issues/268
