### ISSUE TITLE
[BUG] Crash when process list wider than 55 columns

### ISSUE THREAD

**Issue by ToyKeeper** [aristocratos/btop#269]
**Describe the bug**

Any time the process list is wider than 55 characters (wide enough to show the "Command:" column, the next update causes btop to crash with this error:

ERROR: Exception in runner thread -> Proc:: -> wstring_convert::from_bytes

**To Reproduce**

1. Configure btop to show its proc panel, with a width of 56 or more characters (56+ when it's the only panel, 101+ when sharing screen with mem/disk or net panel).  It should be wide enough to show the "Command:" column.
2. Wait until next data update
3. Crash with error about converting proc string to bytes

This may depend on the exact processes running on the system at the time, but I'm not sure if that's relevant or which specific processes are needed.  According to 'ps axuwww', I have ~820 processes running and some have very long command lines.  The longest I see is 638997 bytes, according to /proc/NNNN/cmdline, so I wonder if btop might be overflowing a string buffer or something.

**Expected behavior**

... no crash.

**Info (please complete the following information):**
 - btop++ version: 1.2.2
 - Binary: btop-x86_64-linux-musl.tbz (static binary from release)
 - Architecture: x86_64
 - Platform: Linux, Debian 10 (Buster)
 - (Linux) Kernel: 4.9.0-3-amd64
 - Terminal used: rxvt-unicode

**Additional context**

This is the log when I run btop in debug mode in a large terminal.  It succeeds at the initial display, then crashes 2 seconds later as soon as it tries to update the screen.

```
2022/02/14 (15:29:52) | ===> btop++ v.1.2.2
2022/02/14 (15:29:52) | DEBUG: Starting in DEBUG mode!
2022/02/14 (15:29:52) | INFO: Logger set to DEBUG
2022/02/14 (15:29:52) | DEBUG: Using locale en_US.UTF8
2022/02/14 (15:29:52) | INFO: Running on /dev/pts/199
2022/02/14 (15:29:52) | WARNING: No good candidate for cpu sensor found, using random from all found sensors.
2022/02/14 (15:29:54) | ERROR: Exception in runner thread -> Proc:: -> wstring_convert::from_bytes
2022/02/14 (15:29:54) | INFO: Quitting! Runtime: 00:00:02
```

In case this is relevant...

```
$ for PROC in /proc/*/cmdline ; do wc -c $PROC ; done | sort -n | tail                                                                            
21933 /proc/5946/cmdline
22656 /proc/7990/cmdline
22943 /proc/7991/cmdline
77209 /proc/21638/cmdline
77228 /proc/5755/cmdline
77233 /proc/5944/cmdline
77233 /proc/7961/cmdline
77496 /proc/21645/cmdline
77515 /proc/5757/cmdline
638997 /proc/5694/cmdline
```

**Comment by aristocratos** [comment]
@ToyKeeper 
Seems to be when converting from regular string to wide string and the string is too big.
Added a limit on 1000 characters for command and a size check for the conversion just to be safe.
Try latest commit.

Btw, what program has that astronomical sized command line? :O

**Comment by ToyKeeper** [comment]
Ah, it doesn't take long to do the expansion... and this eliminates the need to create playlists and keep them updated.  Usually I just play parts of my collection ad-hoc, and then leave the process running for days or weeks or months until I feel like something else.  In this case, apparently it has been running since September.

Been doing it that way since I first started using zsh in the 90s, and the only downside I've ever encountered was a crash in btop... which is fixed now.  <3
