### ISSUE TITLE
[REQUEST] Make use of notcurses

### ISSUE THREAD

**Issue by WSLUser** [aristocratos/btop#27]
**Is your feature request related to a problem? Please describe.**
Provide a better TUI experience than what `ncurses` provides along with allowing Windows support eventually.
https://github.com/dankamongmen/notcurses
**Describe the solution you'd like**
I want to see better performance and graphics that notcurses provides that ncurses does not.
**Describe alternatives you've considered**
Do nothing.
**Additional context**
It's a cross-platform Apache2 licensed library that's available in many Linux distribution package managers as well as Brew/Macports. It also provides C++ wrappers so that you don't need to use C code (which would be sub-optimal in a C++ project) with extensive documentation and discussion threads to help answer any questions you may have on how to use it.

**Comment by aristocratos** [comment]
@WSLUser 
I think you're confused. Btop++ is not using `ncurses`, it's all native code.
Introducing a third party library to do what btop++ is already doing in native code for performance seems counter productive.

**Comment by WSLUser** [comment]
I did see the screenshots on the README but I do think notcurses can help. Especially with portability.  You said you are new to C++ so taking advantage of a library that has wealth of experience in C with contributions from experts from different languages including C++ providing easy to use API wrappers seems to be beneficial. I see a few issues I know could resolved right off the bat using notcurses such as anything to do with margins and images.

**Comment by aristocratos** [comment]
@WSLUser 
May I suggest that you read the actual code of this project before making suggestions of replacing already written code with third party libraries.

But you are welcome to forking and replacing the about 20% terminal related parts of the code with `nocurses`, then you can let me know if it was faster.
