### ISSUE TITLE
[BUG] Process Tree Not Rendering Properly

### ISSUE THREAD

**Issue by Galax028** [aristocratos/btop#270]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**
The process tree starts to bug when you scroll down or up like the picture below.

**To Reproduce**

1. Turn on the process tree view in the config
2. Scroll down the process tree, the bug starts to happen

**Expected behavior**

I expected the process window when using tree view to render normally like the normal process view.

**Screenshots**
![image](https://user-images.githubusercontent.com/72642849/153989623-e2e59e8c-37c1-409d-8765-3335058a1fe9.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.2
 - Binary: static binary from release
 - Architecture: [x86_64, aarch64, etc.] x86_64
 - Platform: [Linux, FreeBSD, OsX] Linux
 - (Linux) Kernel: 5.16.8-zen1-1-zen
 - Terminal used: kitty, tty
 - Font used: Fira Code

**Comment by aristocratos** [comment]
@Galax028 
Yup, that's me not testing properly, fixed in latest commit.
