### ISSUE TITLE
[REQUEST] gradient for TTY color scheme

### ISSUE THREAD

**Issue by skulldealer** [aristocratos/btop#272]
This is how tty themed memory bar looks like:
![tty](https://user-images.githubusercontent.com/77295140/154973779-7b2944a0-ad8c-46ab-a9ae-28135aa7d63b.png)

This is how onedark themed memory bar looks like:
![oned](https://user-images.githubusercontent.com/77295140/154973891-c57184f9-3d8a-47fc-abd0-cb547e9e8281.png)

The onedark themed memory bar shows gradient like Green>Yellow>Orange>Red,
while the tty themed memory bar shows single color only.
can you add a gradient to the tty theme or atleast such an option in the settings?
it will be better because the cpu graph and battery indicator also shows a gradient.

**Comment by aristocratos** [comment]
@skulldealer 
The theme is called TTY because it's "TTY" compatible (can be used in a non desktop environment) and only using 16 colors. (The 16 colors you yourself specified in your terminal if using a terminal emulator).

**Comment by skulldealer** [comment]
Ok,
But having a setting that sets gradient for the default theme(not tty, the default theme for btop) will be great.
Also it would be much better if the default theme had gradient out of the box.
I know that tty picks up the default theme but i guess some adjustments can be made.

**Comment by aristocratos** [comment]
@skulldealer 
The default theme is truecolor, it already uses gradients...
