### ISSUE TITLE
[REQUEST] Theme

### ISSUE THREAD

**Issue by pallebone** [aristocratos/btop#278]
Hi there,

I created a theme that I find preferable to the defaults. Is there a way I can send you this theme so you can see if you like it?

Kind regards
Peter

**Comment by aristocratos** [comment]
@pallebone 
Hi, you can create a pull request with the theme added.
Look at #180 for an example.

**Comment by pallebone** [comment]
Thank you, I have done this. Would be great if you could tell me what you think of the theme :)

**Comment by pallebone** [comment]
Thank you for merging theme :)
