### ISSUE TITLE
[REQUEST] Key usage?

### ISSUE THREAD

**Issue by rubyFeedback** [aristocratos/btop#296]
I used the mouse to navigate and that works, but would it be possible to add keybindings?

Ideally if it makes sense those that are similar to htop, ideally the "sort by xyz" functionality.
People could then sort by CPU, mem usage and so forth.

Not sure how much effort this would be to implement, but I think there are some others who
would prefer to use the keyboard rather than the mouse (I tried with the F-keys but these
do not work, perhaps an interactive help menu could be shown on some key combination
too)..

**Comment by aristocratos** [comment]
@rubyFeedback 
I'm not sure if you are serious?

You could try opening the menu and pressing HELP for the "interactive help menu", or just use the keys that are highlighted on every button...

All this should be pretty apparent if you read the README or just open up the menu.

**Comment by somejavadev** [comment]
@rubyFeedback @aristocratos just adding to this closed ticket since I had the same trouble finding the sorting functionality. Once you see it you can't miss it by using the "<" and ">" keyboard keys. I think the problem is the < and > almost looks like it blends into the frame at first.
