### ISSUE TITLE
[REQUEST] Add graphic protocol support

### ISSUE THREAD

**Issue by WSLUser** [aristocratos/btop#30]
**Is your feature request related to a problem? Please describe.**
Add  support for Sixel, Kitty, and Iterm2's graphic protocols. Take a look at https://github.com/hackerb9/lsix for example (which just does Sixel).
**Describe the solution you'd like**
Add support for the graphic protocols in order to improve graphics further, and in some cases potentially boost performance as well. On Linux, start with detecting Kitty support. Kitty and Wezterm both support the Kitty protocol and notcurses favors this support when available, otherwise detect Sixel. Otherwise ignore altogether. On Mac, look for Iterm2 graphics protocol support (assuming you're not running on the aforementioned terminals), if it's not there, then search for Sixel and if that's not available, ignore there too. 

Notcurses also has a fall-back layer where graphics protocols aren't supported, it will display things as best it can, which is still pretty well, if not quite as good which can make notcurses an optional dependency of this feature request (you may need to do very little as notcurses does detection for all 3 protocols).
**Describe alternatives you've considered**
Do  nothing.
**Additional context**

**Comment by aristocratos** [comment]
@WSLUser 
If you're gonna suggest random libraries that comes to your mind you should maybe look in to what btop++ aims to do and have a look at the code.

I can see no need for "graphic protocol support".

If you do, maybe mention how and to what end instead of linking to unrelated software.
