### ISSUE TITLE
[BUG] Transparency

### ISSUE THREAD

**Issue by HVisMyLife** [aristocratos/btop#303]
Btop isn't transparent. I'm on Arch + sway + alacritty. Other programs, like ranger for example (and terminal of course) are transparent. Is there any option to enable that? I'm asking, because on r/unixporn I've seen it with transparent background...
Thanks in advance

**Comment by aristocratos** [comment]
@HVisMyLife 
![image](https://user-images.githubusercontent.com/59659483/163109813-dd7117f4-247e-4290-b9c3-620a9ac73552.png)
