### ISSUE TITLE
enter symbol breaks on some fonts even though it's available

### ISSUE THREAD

**Issue by elandorr** [aristocratos/btop#306]
**Describe the bug**
The enter symbol in `info ↲└` isn't rendered with some fonts like jetbrains mono. With other fonts it renders only while the menu is open and it's non-bold. Others like iosevka work.
All of them can display U+21B2 just fine in a text editor, bold and non-bold, in various terminals/os.

Why is this char in particular behaving oddly?

**Info (please complete the following information):**
 - btop++ version: 1.2.5
 - Binary: static
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.10.0-
 - Terminal used: putty on win
 - Font used: see above

**Additional context**

nothing besides 
`DEBUG: Using locale en_US.UTF-8`

**Comment by aristocratos** [comment]
@elandorr 
Will swap to using `↵` instead of `↲`.
It should be more likely to be available in any font.

**Comment by elandorr** [comment]
@aristocratos The weird thing is that even in a font that supports the char both regular and bold it doesn't work in btop, while it does outside:
![image](https://user-images.githubusercontent.com/56206745/163137865-a200762d-1ad9-40fa-a058-7ad353a0dbf0.png)
I wouldn't normally disturb you for such an inconsequential thing, I'm just curious why this would occur :)
new one for comparison:
![image](https://user-images.githubusercontent.com/56206745/163138170-c3325d43-c928-4610-b386-2fc6be921555.png)

**Comment by aristocratos** [comment]
@elandorr 
It's likely a `putty` problem since I've noticed no issues with `mintty` or `windows-terminal` on Windows.
