### ISSUE TITLE
[BUG] Crashing on startup with floating point exception error

### ISSUE THREAD

**Issue by quasigod-io** [aristocratos/btop#308]
**Describe the bug**
When btop is started the tui is drawn for a split second then it immediately crashes saying, "floating point exception (core dumped)

**To Reproduce**
Run btop in any way

**Screenshots**
![btop](https://user-images.githubusercontent.com/62124625/162642307-fdc69b83-adc9-41fe-bf40-bc1ffd5c84c8.gif)

**Info (please complete the following information):**
 - btop++ version: `btop -v 1.0.5`
 - Binary: Arch repos community/btop
 - (If compiled) Compiler and version: N/A
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.17.1-arch1-1
 - Terminal used: Alacritty, Kitty, and Xfce-terminal
 - Font used: JetBrains-Mono

**Additional context**
[btop.log](https://github.com/aristocratos/btop/files/8460041/btop.log)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:
![image](https://user-images.githubusercontent.com/62124625/162642366-6b43fa90-1d1b-40f7-a081-9cb32559914d.png)

**Comment by aristocratos** [comment]
@quasigod-io 
The latest version in the arch community repo is 1.2.5 so not sure why you are running 1.0.5?

**Comment by quasigod-io** [comment]
Welp I found the issue. I do have it installed from the arch repo, but at some point I must have also compiled it myself because 'which btop' returned '~/.local/bin/btop'. Removed that and it works fine now using the arch repos version, my bad haha.
