### ISSUE TITLE
Exec format error when running on Raspberry Pi 4 - Wrong architecture

### ISSUE THREAD

**Issue by sgolding81** [aristocratos/btop#314]
btop has recently stopped working on my Raspberry Pi 4 after performing an apt upgrade with the following message at runtime: 

> /snap/btop/387/snap/command-chain/snapcraft-runner: 4: exec: /snap/btop/387/usr/local/bin/btop: Exec format error

Executing 

> file /snap/btop/387/usr/local/bin/btop

 results in:

> /snap/btop/387/usr/local/bin/btop: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=463a58fbbfc46ea0c5622992f3bccb06edcb15ef, for GNU/Linux 3.2.0, with debug_info, not stripped

Somehow the wrong architecture has been selected for the binary.

**Comment by gitscosh** [comment]
I'm getting something similar, but it's on an Ubuntu 20 cloud instance. It was running fine before. Now, I get:

-bash: /usr/local/bin/btop: cannot execute binary file: Exec format error

**Comment by marazmarci** [comment]
Same here on Raspberry Pi 4 with Ubuntu 20.04.4 LTS aarch64:
> /snap/btop/389/snap/command-chain/snapcraft-runner: 4: exec: /snap/btop/389/usr/local/bin/btop: Exec format error

output of `file /snap/btop/389/usr/local/bin/btop`:
> /snap/btop/389/usr/local/bin/btop: ELF 64-bit LSB executable, **x86-64**, version 1 (GNU/Linux), statically linked, BuildID[sha1]=463a58fbbfc46ea0c5622992f3bccb06edcb15ef, for GNU/Linux 3.2.0, with debug_info, not stripped

Seems like snap selects the x86-64 binary instead of the aarch64 one.

**Comment by marazmarci** [comment]
@aristocratos, I'm pretty sure that commit 384f082cd966a35a2db48150ed42abf1ec94eca7 caused the issue.

**Comment by aristocratos** [comment]
@sgolding81 @gitscosh @marazmarci 
You will have to take this up with @kz6fittycent, the snap package is his thing.

I only provide installation support for the static binaries in the releases which I create myself.

**Comment by kz6fittycent** [comment]
Uh oh... give me some time, I think I know what it is. @aristocratos  get ready for another PR.

**Comment by kz6fittycent** [comment]
I've initiated a new snap build - please be prepared to refresh using the `--edge` channel.

**Comment by marazmarci** [comment]
This is the exact command, right @kz6fittycent?
`snap refresh btop --edge`

**Comment by kz6fittycent** [comment]
OK, you should have a working snap now. Please refresh to the `--edge` channel. 

Command: `sudo snap refresh btop --edge`

**Comment by marazmarci** [comment]
I just checked it, and I can confirm that the build published on the `--edge` channel works!

Thanks for the fix! 🙂

**Comment by kz6fittycent** [comment]
@aristocratos I think we can close this issue at this point.
