### ISSUE TITLE
[BUG] Color problem on MacOS

### ISSUE THREAD

**Issue by Shaokun-X** [aristocratos/btop#319]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/25054748/164267469-7e6b685e-0f3d-47cf-904f-658bf2ebe7eb.png">

**To Reproduce**

```
OS: macOS 12.3.1 21E258 x86_64 
Host: MacBookPro16,2 
Terminal: Apple_Terminal
Shell: zsh 5.8
btop version: 1.2.6
Kernel: 21.4.0
```

Thanks in advance :)

**Comment by aristocratos** [comment]
@Shaokun-X 
> Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Comment by Shaokun-X** [comment]
> @Shaokun-X
> 
> > Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

Sorry and thank you! 😨🤗
