### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BrianNicholson** [aristocratos/btop#323]
Disks section of btop incorrectly measures used disk space. Absolutely every other utility (bpytop, ncdu, and thunar) measures my disk usage to be 5 gb, while btop measures it to be 10.9 gb
**To Reproduce**

Run btop, compare disk usage to what something like ncdu or your file manager says

**Screenshots**
![2022-04-24_20:35:00](https://user-images.githubusercontent.com/68448812/165011415-c53aabeb-b417-457d-a7af-4bd87e981dbc.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.6
 - Binary: Self complied using AUR script (tried btop and btop-git)
 - (Compiler and version: gcc version 11.2.0
 - Architecture: x86_64
 - Platform: Arch Linux
 - (Linux) Kernel: 5.17.3-arch1-1
 - Terminal used: Alacritty
 - Font used: Code New Roman Nerd Fonts

contents of `~/.config/btop/btop.log`:

2022/04/24 (20:33:38) | ===> btop++ v.1.2.6
2022/04/24 (20:33:38) | INFO: Logger set to DEBUG
2022/04/24 (20:33:38) | WARNING: Failed to set locale en-US.UTF-8 continuing anyway.
2022/04/24 (20:33:38) | INFO: Running on /dev/pts/1
2022/04/24 (20:33:38) | DEBUG: Loading theme file: /usr/local/share/btop/themes/gruvbox_material_dark.theme

2022/04/24 (20:34:00) | ===> btop++ v.1.2.6
2022/04/24 (20:34:00) | INFO: Logger set to DEBUG
2022/04/24 (20:34:00) | WARNING: Failed to set locale en-US.UTF-8 continuing anyway.
2022/04/24 (20:34:00) | INFO: Running on /dev/pts/0
2022/04/24 (20:34:00) | DEBUG: Loading theme file: /usr/local/share/btop/themes/gruvbox_material_dark.theme

**Comment by aristocratos** [comment]
@BrianNicholson 
The extra 6 GiB of reported used would be the reserved and privileged space that only super users has access to.
If you add up the numbers from your filemanager stats you will notice there is 5GiB missing:
5 GiB reported usage but reporting 9% usage, and 9% of 116 GiB is over 10 GiB.

To include available space for privileged users in the free amount, enable `disk free priv` in the [mem] section in the options.
