### ISSUE TITLE
[REQUEST] Add a `.desktop` file to install so that btop will act as an application for DEs

### ISSUE THREAD

**Issue by gnaggnoyil** [aristocratos/btop#328]
This feature was mainly inspired by current status of htop.

By far, btop acts as a TUI program and needs to be invoked inside a tty/terminal, and so is htop.

However, currently htop also installs an `htop.desktop` file into `$(PREFIX)/share/applications`. Therefore, in most (if not all) desktop environments htop will also be seen as a normal desktop application and will run itself in the default terminal of current DE, when opened by this DE. This allows htop to be invoked without explicitly opening a terminal first, and allows users to open htop quickly.

Thus, I would like to see btop adding the same feature too, by providing an .desktop file (and its associated icon file) and install it into proper place, so that users can use btop just like how they use htop.

### Additional Info

* `htop.desktop` file: https://github.com/htop-dev/htop/blob/main/htop.desktop
* `htop.svg`: https://github.com/htop-dev/htop/blob/main/htop.svg

**Comment by gnaggnoyil** [comment]
@aristocratos I would like to see your opinions about whether or not to implement this feature and if yes, how to implement. If you feel like you don't have time to implement it yourself, we can do the implementation and create a PR for you to review.

**Comment by yonatan8070** [comment]
This would be quite simple to implement, the .desktop file would look like this:
```
[Desktop Entry]
Type=Application
Version=1.2.6
Name=btop
GenericName=System Monitor
Comment=Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
Icon=btop
Exec=btop
Terminal=true
Categories=System;Monitor;ConsoleOnly;
Keywords=system;process;task
```
This would need to be saved at `/usr/share/applications/btop.desktop`.
Translations can easily be added to this like so `KEY[LANG]=TRANSLATION`

I could open a PR to add this into the repo and add it to the makefile, but I don't know how to add it into other packages

**Comment by aristocratos** [comment]
@gnaggnoyil Sounds like a great idea!
@yonatan8070 Great initiative.

> I could open a PR to add this into the repo and add it to the makefile, but I don't know how to add it into other packages

Feel free to create a PR. I'll make sure to include the .desktop file with the static build packages. For other packages (external) that would be up to the individual package maintainer how to implement the installation.

**Comment by aristocratos** [comment]
I believe for icon the `B` from the svg logo could be used.

**Comment by yonatan8070** [comment]
> I believe for icon the `B` from the svg logo could be used.

Something like this?

![image](https://user-images.githubusercontent.com/45665471/167252571-6e3af061-ac47-4408-af32-457abda902ca.png)

**Comment by aristocratos** [comment]
@yonatan8070 
> Something like this?

That works!

**Comment by yonatan8070** [comment]
I added that along with the desktop file into #329
