### ISSUE TITLE
[REQUEST] homebrew formula

### ISSUE THREAD

**Issue by lucmichalski** [aristocratos/btop#33]
Hi @aristocratos ,

Hope you are all well !

I was wondering if it would be possible to create an homebrew formula for your great project :-)

Ps. apt package also ^^

Cheers,
Luc Michalski

**Comment by aristocratos** [comment]
@lucmichalski 
All good and swell :)

I've said this before but I will not be doing any other packaging (than the static binaries + installer script), I'll leave that to those who are good at it.

Hopefully some homebrew enthusiast will notice this this request and create a PR with the needed homebrew scripts.

**Comment by martin-braun** [comment]
Yes, I'd love to see this as well, for Intel and M1 chips.

**Comment by XuehaiPan** [comment]
`btop` is now available in Homebrew (Homebrew/homebrew-core#90061).

**Comment by martin-braun** [comment]
@XuehaiPan Thanks, I can confirm the installation on Intel devices works flawlessly.

**Comment by brerx** [comment]
ARM on M1 works as well. like a charm. ❤️

**Comment by aristocratos** [comment]
Will add install instructions to the readme.

**Comment by nevack** [comment]
Happy to help, thanks for testing it! @aristocratos Can we close the issue now?
