### ISSUE TITLE
[REQUEST] Cross compilation support

### ISSUE THREAD

**Issue by jaskij** [aristocratos/btop#330]
**Is your feature request related to a problem? Please describe.**
I want to cross-compile btop for AArch64, using Yocto project. A quick look through your `Makefile` tells me the experience will not be pleasent - overriding `CXX` is a giant red flag in my book.

**Describe the solution you'd like**
Best would be either fixing the `Makefile`, or adding CMake support. I know CMake much better than make, so I'm prepared to contribute a `CMakeLists.txt` if you help me understand what's going on in your Makefile. Changing `:=` to `?=` [here](https://github.com/aristocratos/btop/blob/841941afbac20e9379375b300d54b0039d715cec/Makefile#L57-L63) would be a first step, but I'm not sure it would be sufficient.

**Describe alternatives you've considered**
I could keep a private, patched fork. But that's a stupid solution.

**Additional context**
The two approaches I proposed - fixing Makefile or adding CMake support - are only two possibilities, I'm sure there are other options. I want to help with this, and this issue is mostly to open discussion.

**Comment by jaskij** [comment]
I guess my lack of GNU Make experience shows - I can probably set `CXX` as a make argument.

**Comment by aristocratos** [comment]
@jaskij 
The makefile respects the CXX flag, `CXX := ` only applies if make is called with no `CXX=` flag.
You need to use `override` before the assignment in the makefile to ignore the make flags.
To set it when calling make just use `make CXX=<your cross compiler>`.
The CXX flag must be explicitly set when calling make to not automatically get auto set to best fitting GCC candidate.
This is because GCC is currently the only guaranteed compiler to work with the C++20 functions used in btop++.

I set it up like this to not have to deal with bug reports from people having CXX set to `clang` in the environment and that didn't bother reading the compile instructions.

There is also a cmake fork as mentioned in the README.md: 
> For a cmake based build alternative see the [fork](https://github.com/jan-guenter/btop/tree/main) by @jan-guenter

It looks to be a version behind, but the CmakeLists.txt should still work if copied over.

**Comment by jaskij** [comment]
Okay, I must apologize - after reading the README and actually applying myself, it seems to build properly. I won't be able to test it on hardware until Monday.

That said, Yocto was throwing a `host-user-contaminated` QA at me (any specific reason for `cp -p`?):

> host-user-contaminated: Checks that no package produced by the recipe contains any files outside of /home with a user or group ID that matches the user running BitBake. A match usually indicates that the files are being installed with an incorrect UID/GID, since target IDs are independent from host IDs. For additional information, see the section describing the [do_install](http://docs.yoctoproject.org/4.0/singleindex.html#ref-tasks-install) task.

So I had to apply a small patch to the Makefile:

```patch
host-user-contaminated: Checks that no package produced by the recipe contains any files outside of /home with a user or group ID that matches the user running BitBake. A match usually indicates that the files are being installed with an incorrect UID/GID, since target IDs are independent from host IDs. For additional information, see the section describing the [do_install](http://docs.yoctoproject.org/4.0/singleindex.html#ref-tasks-install) task.
```

I'll need to give the Makefile a more thorough read, but I don't think your usage of `uname` or other tools probing the host should break anything too badly. At least, not while I'm cross compiling from Linux to Linux.

**Comment by jaskij** [comment]
Here's my full Yocto recipe, after testing I will have to read up how to get it merged upstream. The patch is the one from my previous comment.

```bitbake
# Copyright (C) 2022 jaskij <jaskij@gmail.com>
# Released under the MIT license (see COPYING.MIT for the terms)

SUMMARY = "Resource monitor that shows usage and stats for processor, memory, disks, network and processes."
HOMEPAGE = "https://github.com/aristocratos/btop"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"
SECTION = "console/utils"

SRC_URI = "\
    git://github.com/aristocratos/btop.git;protocol=https;branch=main \
    file://0001-fix-make-install.patch \
    "
SRCREV = "df205fb23c4d27bbe67d7e1bca4e7ee6f0e56a2f"

EXTRA_OEMAKE:append = "-e ADDFLAGS='${CXXFLAGS}' QUIET=true DESTDIR='${D}' PREFIX='/usr'"

CLEANBROKEN="1"

S = "${WORKDIR}/git"

do_compile() {
    oe_runmake
}

do_install() {
    oe_runmake install
}
```

**Comment by aristocratos** [comment]
@jaskij 
As also mentioned in the compile instructions, you can use the `ARCH=` make flag to manually set architecture when cross compiling.

> That said, Yocto was throwing a host-user-contaminated QA at me (any specific reason for cp -p?):

Not sure honestly, can't think of reason why `-p` would be needed, probably a remnant from an older project I copied the beginning of the Makefile from.

**Comment by jaskij** [comment]
> As also mentioned in the compile instructions, you can use the `ARCH=` make flag to manually set architecture when cross compiling.

I'm not entirely sure if the cross compiler is actually in the `PATH` for the build, and overriding `CXX` is the preferred way as far as I understand. That said, something you maybe don't account for, `CXX` also includes some flags, here's a sample from my build:
```
export CXX="aarch64-poky-linux-g++  -mcpu=cortex-a35 -march=armv8-a+crc+crypto --sysroot=/home/jaskij/yocto/build/tmp-glibc/work/cortexa35-crypto-poky-linux/btop/1.2.6-r0/recipe-sysroot
```

> > That said, Yocto was throwing a host-user-contaminated QA at me (any specific reason for cp -p?):
> 
> Not sure honestly, can't think of reason why `-p` would be needed, probably a remnant from an older project I copied the beginning of the Makefile from.

Yocto's recommendation is actually using either `install` or `cp --no-preserve-ownership`, but this kinda small patch, for a file which probably won't change much, I can keep around.

-----

Summing it up: thanks for the help, and once again I apologize for not reading up before opening the issue. I'll test if it actually works properly on Monday, and then try to get it upstreamed in `meta-oe`, where `htop` already is.

**Comment by aristocratos** [comment]
@jaskij 
The ARCH flag would be used in conjunction with also setting CXX.
To get your environment CXX you could use `make CXX="$CXX"` to have the shell expand it for you in to make.

**Comment by jan-guenter** [comment]
> @jaskij 
> There is also a cmake fork as mentioned in the README.md:
> 
> > For a cmake based build alternative see the [fork](https://github.com/jan-guenter/btop/tree/main) by @jan-guenter
> 
> It looks to be a version behind, but the CmakeLists.txt should still work if copied over.

Thanks for letting me know. I setup an automated workflow to pull the upstream changes, which is supposed to fail when the upstream Makefile changes so that I can update the cmake file accordingly. Somehow the notification did not work.

On the first glance it seems that the Makefile changes are mostly cosmetic in nature, so I triggered the cmake build workflow on the new code without changing the cmake file yet and it seems to build fine.

I will have a closer look at the Makefile changes tomorrow and will correct the cmake file accordingly if necessary.

**Comment by jaskij** [comment]
> The ARCH flag would be used in conjunction with also setting CXX. To get your environment CXX you could use `make CXX="$CXX"` to have the shell expand it for you in to make.

Earlier on I used the `-e` `make` flag, but yes, switching to setting `CXX` explicitly in `make` arguments is better.

As for `ARCH`, your `Makefile` correctly gets `aarch64` from running `$(CXX) -dumpmachine`. If I wanted to add that flag manually it could turn into some hassle - I'd need to understand what values you expect and possibly set up a mapping. What is it used for in `btop`'s build process anyway? The only place I can see it influencing the build is [detecting ARM macOS](https://github.com/aristocratos/btop/blob/841941afbac20e9379375b300d54b0039d715cec/Makefile#L41-L43). Setting target CPU flags is already done in `CXX` for me anyway.

**Comment by aristocratos** [comment]
@jaskij 
>As for ARCH, your Makefile correctly gets aarch64 from running $(CXX) -dumpmachine. If I wanted to add that flag manually it could turn into some hassle - I'd need to understand what values you expect and possibly set up a mapping. What is it used for in btop's build process anyway? The only place I can see it influencing the build is [detecting ARM macOS](https://github.com/aristocratos/btop/blob/841941afbac20e9379375b300d54b0039d715cec/Makefile#L41-L43). Setting target CPU flags is already done in CXX for me anyway.

No you're right, the cross compiler `-dumpmachine` should give the correct arch. I was mistakenly thinking I was using `uname` for arch, but it's just for platform. So as long you are compiling for the same platform it should work fine regardless of architecture :)

**Comment by aristocratos** [comment]
@jan-guenter 
> On the first glance it seems that the Makefile changes are mostly cosmetic in nature, so I triggered the cmake build workflow on the new code without changing the cmake file yet and it seems to build fine.

Oh, yeah, I added percentages to the build progress.. :)

**Comment by jaskij** [comment]
@aristocratos all good then. I did some more probing, and the output seems just fine. I'll test it on Monday with our actual hardware and report back.

**Comment by jaskij** [comment]
One more thing I have noticed - I will either clear `OPTFLAGS` or set it to just `-ftree-loop-vectorize`. `-O2` is already in what I'm passing as `ADDFLAGS`, and LTO probably needs to be disabled - it's known to break reproducibility in GCC. [Upstream has it fixed for GCC 12](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101473), and I am honestly not sure about the status in Yocto - there were plans to backport the fix, plus a few patches needed to be added to Yocto itself, and I have to read up further on how it ended up.

**Comment by aristocratos** [comment]
@jaskij 
Looking at that thread, it looks like just stripping debug information would fix the reproducibility issue, so you could add `STRIP=true` make flag, then you shouldn't loose any possible performance gains from lto.

**Comment by jaskij** [comment]
@aristocratos for myself, I could live with that, but if I want to upstream the recipe, I need to adhere to project's best practices, and it seems like the debug symbols also must be reproducible. At least that's what I infer [from this thread](https://bugzilla.yoctoproject.org/show_bug.cgi?id=14481) - I'll ask about it when mailing my patch.

**Comment by jaskij** [comment]
@aristocratos I'm happy to report that, after properly cross compiling, `btop` works nicely on an i.MX8X SoC using a custom distro built with Yocto Project/OpenEmbedded.

My current recipe is as follows:

```bitbake
# Copyright (C) 2022 jaskij <jaskij@gmail.com>
# Released under the MIT license (see COPYING.MIT for the terms)

SUMMARY = "Resource monitor that shows usage and stats for processor, memory, disks, network and processes."
HOMEPAGE = "https://github.com/aristocratos/btop"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"
SECTION = "console/utils"

SRC_URI = "\
    git://github.com/aristocratos/btop.git;protocol=https;branch=main \
    file://0001-fix-make-install.patch \
    "
SRCREV = "df205fb23c4d27bbe67d7e1bca4e7ee6f0e56a2f"

# This is how the project is set up to take the flags
# OPTFLAGS='' is cleared, because
#   1)  we supply our own optimization flags
#   2)  btop by default sets -flto, and I'm not sure
#       about the status of reproducible builds with it enabled
EXTRA_OEMAKE:append = "\
    CXX='${CXX}' \
    ADDFLAGS='${CXXFLAGS} ${LDFLAGS}' \
    QUIET=true DESTDIR='${D}' \
    PREFIX='/usr' \
    OPTFLAGS='' \
    "

S = "${WORKDIR}/git"

do_compile() {
    oe_runmake
}

do_install() {
    oe_runmake install
}
```

One minor issue I hit is that for whatever reason `btop` is not showing disk IO for my root drive (not that I care much about it, but it's still something one would expect to work). It seems to be caused by using `/dev/root` in `/etc/fstab` and passing `root=` in kernel cmdline. To fix that it seems you would need to parse `/proc/cmdline`.

**Comment by aristocratos** [comment]
@jaskij 
Glad to hear!

> One minor issue I hit is that for whatever reason btop is not showing disk IO for my root drive

I've seen that issue before, see #140

It seemed to be solvable by manually symlinking `/dev/root` to the correct block device see: https://github.com/aristocratos/btop/issues/140#issuecomment-980315055

But I'm not sure how good of a practice it is to do this, just a FYI.

> To fix that it seems you would need to parse `/proc/cmdline`.

That is however a good solution I hadn't thought of, will look into it when I've got time.

**Comment by jaskij** [comment]
Iirc the syntax is `rootfs=/dev/path,mount,opts`, I'm not sure what, if any, rules are there for quoting and escaping are for kernel arguments, which you would need to reimplement to correctly select the argument.

**Comment by jaskij** [comment]
Since I managed to build everything fine, and it's working nicely (sans #140 ), I'll close this issue.

**Comment by jclsn** [comment]
Is this maintained somewhere? 

I btw wrote one recipe myself using the [cmake fork](https://github.com/jan-guenter/btop), which worked quite well. Would be nice if this was supported by autotools though.

**Comment by jclsn** [comment]
You can also automate that with AUTOREV. I will maybe ask the Yocto guys tomorrow of they are interested in upstreaming the recipe.

**Comment by jaskij** [comment]
We're getting a bit off-topic here, but reading the docs, `AUTOREV` is mostly meant for in-development projects. Normally, you want to stick to a specific revision.

**Comment by jclsn** [comment]
Alright, there seems to be no objection to upstreaming it as long as it is maintained. Are you interested in that?
