### ISSUE TITLE
[BUG] Apparmor kernel log msgs

### ISSUE THREAD

**Issue by jmakov** [aristocratos/btop#339]
**Describe the bug**
audit: type=1400 audit(1653430931.795:463389): apparmor="DENIED" operation="open" profile="snap.btop.btop" name="/proc/spl/kstat/zfs/arcstats" pid=1960814 comm="btop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

**To Reproduce**

Run btop on Ubuntu 22.04.

**Expected behavior**

No "denied" msgs.

**Comment by EndlessDex** [comment]
This issue can be resolved for the snap case by running the following after install:

```
snap connect btop-desktop:hardware-observe
snap connect btop-desktop:mount-observe
snap connect btop-desktop:network-observe
snap connect btop-desktop:process-control
snap connect btop-desktop:removable-media
snap connect btop-desktop:system-observe
```

**Comment by jmakov** [comment]
Thanks for the answer. This issue isn't relevant for me anymore so I'll close it.

**Comment by aristocratos** [comment]
@EndlessDex @jmakov 
I believe the connections are made automatically since maybe a year or so back when btop was accepted as trusted on snapcraft.

**Comment by EndlessDex** [comment]
@aristocratos They are not made automatically. I installed the snap (v1.2.13) this week for Ubuntu 20.04 and ran into this issue. 

Running `snap connections btop-desktop` showed that none of the items listed above were connected. This led to log spam and a partially blank interface.

**Comment by aristocratos** [comment]
@kz6fittycent Shouldn't the connections be made automatically?
