### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lanqsh** [aristocratos/btop#34]
I compile btop from the source code last night
coredump when I run btop
here is my gdb info:
![image](https://user-images.githubusercontent.com/12372700/134615850-ab7391a8-0d13-47d1-a03e-531ad17365f1.png)
my env:
![image](https://user-images.githubusercontent.com/12372700/134615927-2d8a1213-c0ec-4f6a-a45a-e494936f5a68.png)

next I download the release binary btop which update 9 hours ago,it works,hope that bug is fix

**Comment by lanqsh** [comment]
this project is really awesome,I really appreciate your work, maybe my env is not right,plz ignore this bug if it's not important.

**Comment by aristocratos** [comment]
@lanqsh 
Thanks :)

Not really sure why it's stopping where it is. But recently made some changes to that particular function, you can try compiling fresh from latest commit. And see it works better.
