### ISSUE TITLE
[BUG][macos][monterey] `btop` 1.27 crashes at launch

### ISSUE THREAD

**Issue by dennismayr** [aristocratos/btop#343]
**Describe the bug**

`btop` _1.27_ crashes at launch.

```bash
$ btop
[1]    49987 killed     btop
```

Version _1.26.x_ works.

**To Reproduce**

Download the latest _1.27_ version for `btop`.
I use the following method:
```bash
mkdir -p ~/tmp; curl -L --compressed $(curl --compressed -s https://api.github.com/repos/aristocratos/btop/releases/latest | grep 'browser_' | grep 'arm64-macos-monterey[.]tbz' | cut -d\" -f4) -o ~/tmp/btop-latest.tbz; cd ~/tmp && tar xvfj btop-latest.tbz; sudo ./install.sh; rm -rf CHANGES.md install.sh LICENSE Makefile README.md setuid.sh themes uninstall.sh btop-latest.tbz; cd -
```

**Expected behavior**

`btop` launches without errors.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: 1.27
 - Binary: static binary from release
 - Architecture: aarch64
 - Platform: OsX
 - (OSX/FreeBSD) Os release version: Monterey
 - Terminal used: iTerm2 + zsh
 - Font used: Hasklig / Source Code Pro

**Comment by aristocratos** [comment]
@dennismayr 
I've noticed this happening sometimes on macos, try first running `make uninstall` before running `make install`.
And it should be working again.
Have no idea why it's happening.

**Comment by dennismayr** [comment]
Well, that **did** work 😄 

Closing then; thanks for the heads-up!

**Comment by dennismayr** [comment]
> @dennismayr 
> I've noticed this happening sometimes on macos, try first running `make uninstall` before running `make install`.
> And it should be working again.
> Have no idea why it's happening.

I'm thinking that perhaps Mac OS stores the hash of the previously authorised `btop` binary (after allowing it in _System Settings_ -> _Security & Privacy_), and when the new binary is installed through a shell script, the hash mismatch triggers a kill process.

Go figure 🤷🏻
Anyway, it works now 😃

**Comment by aristocratos** [comment]
@dennismayr 
Huh, possible. But one would think there would be a popup to "re-authorise" the binary after `make uninstall && make install` since it's a new hash, which I've never seen happening. But who knows with the mysterious and undocumented ways of Apple... :)
