### ISSUE TITLE
[BUG] missing themes with homebrew formula

### ISSUE THREAD

**Issue by zhengpd** [aristocratos/btop#344]
**Describe the bug**

`color_theme = "nord"` in btop.conf not working, installed via `brew install btop`.

Can be fixed by `ln -s /opt/homebrew/opt/btop/share/btop /usr/local/share/btop`

Guess the `share/btop` should be symlinked in homebrew formula.

- [homebrew] btop: stable 1.2.6 (bottled)

**Comment by jjsanderson** [comment]
Same issue here, though my paths were a little different. I ended up fixing with:

    ln -s /opt/homebrew/share/btop/themes ~/.config/btop/

I'll see if I can log an issue with Homebrew.

btop 1.2.8 / macOS 12.4.

**Comment by carlocab** [comment]
You can also do
```
color_theme = "/opt/homebrew/share/btop/themes/nord.theme"
```
in your `btop.conf`.

If `btop` checked `../share/btop/themes` relative to the `btop` binary, it would also be able to find the themes. Currently, it seems to only check `~/.config/btop/themes`, and `/usr[/local]/share/btop/themes`.

**Comment by carlocab** [comment]
Actually, there is code that looks like it should be checking that relative path:

https://github.com/aristocratos/btop/blob/102b6dbc9d33906319e7c710cf58ba2893d6ec49/src/btop.cpp#L707-L710

Presumably, it is just not being exercised.

**Comment by aristocratos** [comment]
@carlocab
This would likely be an issue of where homebrew is placing the `share/btop` folder in regards to the binary.
Since it will look for `../share/btop/themes` in relation to where the binary is placed.
But if it's placed in `/opt/homebrew/opt/btop/share/btop/themes` and the binary in `/opt/homebrew/opt/bin/btop` it won't find it because of the extra `btop` folder created under `opt`. 

I'm not really versed in homebrew so I don't know if this is something that have recently changed in how homebrew installs packages?

**Comment by carlocab** [comment]
Nothing has changed recently in how Homebrew installs packages (that would break many things).

Homebrew installs `btop` with a prefix of
```
/opt/homebrew/Cellar/btop/1.2.8
```
and
```
/opt/homebrew/opt/btop
```
is merely a symlink to the `Cellar` path above.
```
❯ file /opt/homebrew/opt/btop
/opt/homebrew/opt/btop: symbolic link to ../Cellar/btop/1.2.8
```

The `1.2.8` changes when the version of `btop` changes, of course. The `btop` binary can be found at
```
❯ realpath $(which btop)
/opt/homebrew/Cellar/btop/1.2.8/bin/btop
```
and the themes are installed to
```
❯ realpath /opt/homebrew/share/btop/themes
/opt/homebrew/Cellar/btop/1.2.8/share/btop/themes
❯ realpath /opt/homebrew/opt/btop/share/btop/themes
/opt/homebrew/Cellar/btop/1.2.8/share/btop/themes
```

So there is no extra `btop` directory:
```
❯ realpath /opt/homebrew/opt/btop/bin/../share/btop/themes
/opt/homebrew/Cellar/btop/1.2.8/share/btop/themes
```

**Comment by carlocab** [comment]
> But if it's placed in `/opt/homebrew/opt/btop/share/btop/themes` and the binary in `/opt/homebrew/opt/bin/btop` it won't find it because of the extra `btop` folder created under `opt`.

There is no `/opt/homebrew/opt/bin`. There is, however, an `/opt/homebrew/opt/btop/bin`.

**Comment by aristocratos** [comment]
@carlocab 
Not sure what's going on then, since nothing has changed in the btop code for getting the path to the themes folder but I'm fairly certain that the themes were picked in the homebrew install when I tested some time ago. But can confirm it's not working now.

Has homebrew always been symlinked in the way you described above?

**Comment by carlocab** [comment]
Yes. Though packages shouldn't be aware of the `/opt/homebrew/opt` symlinks, that's just a way to expose an unversioned path to users.

**Comment by aristocratos** [comment]
Looking at the code again I can see why this isn't working on macos atleast:
``` cpp
	//? Try to find global btop theme path relative to binary path
#if defined(__linux__)
	{ 	std::error_code ec;
		Global::self_path = fs::read_symlink("/proc/self/exe", ec).remove_filename();
	}
#endif
	if (std::error_code ec; not Global::self_path.empty()) {
		Theme::theme_dir = fs::canonical(Global::self_path / "../share/btop/themes", ec);
		if (ec or not fs::is_directory(Theme::theme_dir) or access(Theme::theme_dir.c_str(), R_OK) == -1) Theme::theme_dir.clear();
	}
	//? If relative path failed, check two most common absolute paths
	if (Theme::theme_dir.empty()) {
		for (auto theme_path : {"/usr/local/share/btop/themes", "/usr/share/btop/themes"}) {
			if (fs::is_directory(fs::path(theme_path)) and access(theme_path, R_OK) != -1) {
				Theme::theme_dir = fs::path(theme_path);
				break;
			}
		}
	}
```

There is currently no method implemented in the code for getting the path to "self" in the code for macos.
Will look in to it.

**Comment by carlocab** [comment]
> There is currently no method implemented in the code for getting the path to "self" in the code for macos. Will look in to it.

You probably want `_NSGetExecutablePath`. See [`man 3 dyld`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dyld.3.html).

**Comment by aristocratos** [comment]
Fixed in a84a7e6

**Comment by carlocab** [comment]
Thanks; opened https://github.com/Homebrew/homebrew-core/pull/105731 to apply your patch in Homebrew.

**Comment by zhengpd** [comment]
Fixed by upgrading to latest version.
