### ISSUE TITLE
Identical download and upload values

### ISSUE THREAD

**Issue by Methatronc** [aristocratos/btop#35]
Hello,

Awesome update of htop so far, thanks for your work.
Only thing I've noted so far is that download and upload values are the same :
![image](https://user-images.githubusercontent.com/58328740/134632710-c9ef86a2-ac35-4560-af84-ddbd1be42471.png)

 - btop++ version: 1.06
 - Binary: complied with make STATIC=true
 - (If compiled) Compiler and version: gcc-10 10.2.1
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.10.0-8-amd64
 - (OSX/FreeBSD) Os release version:Debian 11

Logs :

2021/09/24 (09:40:25) | ===> btop++ v.1.0.6
2021/09/24 (09:40:25) | DEBUG: Starting in DEBUG mode!
2021/09/24 (09:40:25) | INFO: Logger set to DEBUG
2021/09/24 (09:40:25) | DEBUG: Setting LC_ALL=fr_FR.UTF-8
2021/09/24 (09:40:25) | INFO: Running on /dev/pts/0
2021/09/24 (09:40:32) | INFO: Quitting! Runtime: 00:00:07

**Comment by aristocratos** [comment]
@Methatronc 
Huh, how does the output from 
`cat /sys/class/net/<interface>/statistics/rx_bytes` and 
`cat /sys/class/net/<interface>/statistics/tx_bytes` look.
<interface> = your interface.

**Comment by UmarJ** [comment]
You may be looking at the loopback device `lo`.

**Comment by aristocratos** [comment]
Yeah, the network graph will default to the interface with highest combined throughput. 
Unless you set which interface to start with in the options.

**Comment by Methatronc** [comment]
You're totally right, you think we could specify at compile time what device to listen to by default ?

**Comment by aristocratos** [comment]
Why? You can set it in the options or manually in the config file.
If you really want to, you can change the deault in `btop_config.cpp` in `unordered_flat_map<string, string> strings`.
But not really much point when you can just copy the config file if you're gonna set up multiple computers with a predefined default.

**Comment by Methatronc** [comment]
True, I guess I'll go with that.
Thanks for your time !
