### ISSUE TITLE
[BUG] Wrong memory usage in proc box

### ISSUE THREAD

**Issue by ErrorNoInternet** [aristocratos/btop#361]
**Describe the bug**
The memory usage displayed in the proc box is double than the memory usage in the proc details box. I'm assuming this is happening because "1000M" can't fit in the proc box...

**To Reproduce**
Have a process use more than 1000 MB ram, but less than 1024 MB
(Running `variable = "a" * (1000 * 1016 * 1024)` in Python should use about 1002 MB ram)

**Expected behavior**
Correct memory usage displayed in the proc box (1G)

**Screenshots**
![2022-06-09_17-49-22](https://user-images.githubusercontent.com/61157623/172820170-52b97b9a-ec1d-4a77-95c1-c2bdf2253f99.png)
![0](https://user-images.githubusercontent.com/61157623/174421009-b29f5e51-b131-46f8-b9cd-c89e796a7b65.png)

**Info (please complete the following information):**
 - btop++ version: `1.2.6`
 - Binary: static binary from release
 - Architecture: `x86_64`
 - Platform: Linux
 - (Linux) Kernel: `5.17.9-1-MANJARO`
 - Terminal used: Konsole (zsh)
 - Font used: JetBrains Mono

**Additional context**
```
2022/06/09 (17:53:43) | ===> btop++ v.1.2.6
2022/06/09 (17:53:43) | DEBUG: Starting in DEBUG mode!
2022/06/09 (17:53:43) | INFO: Logger set to DEBUG
2022/06/09 (17:53:43) | DEBUG: Using locale en_US.UTF-8
2022/06/09 (17:53:43) | INFO: Running on /dev/pts/2
2022/06/09 (17:53:43) | DEBUG: Loading theme file: /usr/local/share/btop/themes/nord.theme
```

**Comment by Abrifq** [comment]
same issue as #493
should be fixed within next release :slightly_smiling_face:
