### ISSUE TITLE
[BUG]btop will be automaticatlly exit/crashed abnormally on Linux Kernel 5.18

### ISSUE THREAD

**Issue by linunixer** [aristocratos/btop#363]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

After keeping btop for minutes it always crashes with the following error:

**To Reproduce**

open btop and keep running for 2-5 minutes

**Expected behavior**

The btop will crash and showing error message

**Screenshots**

![btop_crashed_2022-06-13_10-14-31](https://user-images.githubusercontent.com/3668438/173408997-8c26cedf-74aa-4469-b162-3f3055a2ea52.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.7
 - Binary: Arch Linux community/btop
 - (If compiled) Compiler and version:
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.18.3-arch1-1
 - (OSX/FreeBSD) Os release version: N/A
 - Terminal used: xfce4-terminal or kitty
 - Font used: JetBrains Mono

**Additional context**

contents of `~/.config/btop/btop.log`

2022/06/13 (09:50:49) | ===> btop++ v.1.2.7
2022/06/13 (09:50:49) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (09:50:55) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (09:51:01) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (09:51:07) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (09:51:13) | ERROR: Stall in Runner thread, restarting!

2022/06/13 (10:12:19) | ===> btop++ v.1.2.7
2022/06/13 (10:12:19) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:12:25) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:12:31) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:12:37) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:12:43) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:12:49) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:12:55) | ERROR: Stall in Runner thread, restarting!
2022/06/13 (10:13:01) | ERROR: Stall in Runner thread, restarting!

2022/06/13 (10:18:20) | ===> btop++ v.1.2.7
2022/06/13 (10:18:20) | WARNING: Failed to join _runner thread on exit!
2022/06/13 (10:18:20) | ERROR: No response from Runner thread, quitting!

2022/06/13 (10:23:24) | ===> btop++ v.1.2.7
2022/06/13 (10:23:24) | ERROR: Stall in Runner thread, restarting!

**GDB Backtrace**
btop++ is not crashing at start

**Comment by linunixer** [comment]
Just tested on Linux Kernel LTS 5.15, there is no issue on btop(working well)

**Comment by aristocratos** [comment]
@linunixer 
Tested with a clean arch install with kernel 5.18.7-arch1-1, seeing no issues.
So don't think this is a kernel issue.

Can you run `btop --debug` and screenshot the screen and also see if there is anymore information in the logfile?

**Comment by linunixer** [comment]
hi @aristocratos 
Thank you for your reply. I noticed it might be an issue caused from here https://bbs.archlinux.org/viewtopic.php?id=277097
 which is a retrogression issue on my ath9k wireless driver.
When I blacklisted the kernel module of ath9k and re-run btop with kernerl 5.18.7, everythin looks good.
I believe this bug could be cancelled or closed.
Appreciate
