### ISSUE TITLE
[REQUEST] Use default x-terminal-emulator when opening from `.desktop`

### ISSUE THREAD

**Issue by StuSerious** [aristocratos/btop#367]
First of all, thanks for adding a desktop entry!

**Is your feature request related to a problem? Please describe.**
I have Alacritty set up so that it has no borders and a precise size and placement.
However, when I open btop from the .desktop, it uses the basic Ubuntu terminal, so it has 'random' positioning and a border.

**Describe the solution you'd like**
I think it would be cool if the default `x-terminal-emulator` is used to open btop instead.

**Describe alternatives you've considered**
Launching from terminal directly, but at that point, the .desktop is not even considered anymore.

**Additional context**
Related to #329 and #345.

**Comment by Jan200101** [comment]
Since the Desktop file specified that the program is suppose to be ran in a Terminal, isn't it up to whatever deals with it to pick the user specified terminal emulator?

**Comment by StuSerious** [comment]
Could you be a bit more specific? I don't really understand your question.

In my research I haven't found a way to change it's behavior, usually it should be down to `x-terminal-emulator` priority, unless there is some distro-specific way to choose default software that I'm not aware of.

**Comment by Jan200101** [comment]
.desktop files are usually consumed by your DE or other program (e.g. rofi)
that program then has to make the decision on how to start that app.

Since the .desktop file specified `Terminal=true` it should be ran in a terminal so whatever you use to run desktop files, that is responsible for choosing the right terminal so I don't think btop can do anything to fix this.

**Comment by StuSerious** [comment]
Thanks for the explanation!

Knowing that there is no way to specify the use of the default `x-terminal-emulator` from btop's side or in the .desktop file, I think this issue has little reason to stay open.

I'll still update here if I find a solution, cheers!
