### ISSUE TITLE
[BUG] RAID-0 array doesn't show up

### ISSUE THREAD

**Issue by mhillebrand** [aristocratos/btop#37]
My 4 TB RAID-0 array doesn't show up. Also, my 4 TB RAID-1 array shows up as 2.41 GiB.

<img width="960" alt="Screen Shot 2021-09-24 at 9 41 59 AM" src="https://user-images.githubusercontent.com/286198/134711274-b43b9e5a-d945-4e46-958f-465c3d6b21ea.png">
<img width="685" alt="Screen Shot 2021-09-24 at 9 34 15 AM" src="https://user-images.githubusercontent.com/286198/134711284-af8f5970-65bf-4741-87e2-cfe33fd11dac.png">

**Info (please complete the following information):**
 - btop++ version: 1.0.6
 - Binary: static binary `btop-1.0.6-linux-i686.tbz`
 - (Linux) Kernel: 5.4.0-84-generic
 - Terminal used: bash
 - Font used: Default Linux Mint terminal font: Ubuntu Mono Regular

**Comment by aristocratos** [comment]
@mhillebrand 
I have a similar setup with but with two 4TB drives in raid zero on `/dev/md/0p1` and that's working without problem on x86-64. This might be an issue with values wrapping around on 32-bit systems considering the weird percentage values and the 163 PetaBytes of used, gonna look into it.

**Comment by aristocratos** [comment]
@mhillebrand 
Wait a minute, why are you running the `i686` package? Just noticed your memory size and the cpu in the screenshot.
Download the `x86-64` package and your problems should be solved...

**Comment by mhillebrand** [comment]
Ah ha! Good catch. It works now. Thanks :)

<img width="957" alt="Screen Shot 2021-09-24 at 11 13 28 AM" src="https://user-images.githubusercontent.com/286198/134721757-19ed3295-eb8c-49f7-a920-7ceb81e14442.png">
