### ISSUE TITLE
Option to make 100% CPU usage = 1 CPU fully used?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [aristocratos/btop#371]
**Is your feature request related to a problem? Please describe.**

I like to know at a glance how many CPUs a process is using based on the % CPU column in the process table. This can help me identify runaway processes using 100% of 1 or more CPUs (wasting my battery and spinning up my fans). 

**Describe the solution you'd like**

It would be nice if there was an option to make 100% CPU usage mean 100% of 1 CPU. That way, if I see a process using about 400% CPU, I know it's using 4 cores (well, maybe 4 hyperthreads, but close enough). Moreover, this makes percent CPU more comparable across machines with different numbers of cores, and it means that the individual CPU usage percents will add up to the total usage in the CPU graph (modulo rounding).

Of course, this would imply that, for example, an 8-core system could have a total of 800% CPU usage if all cores were fully loaded.

**Comment by aristocratos** [comment]
@DarwinAwardWinner 
Press `c` as in per-`c`ore
