### ISSUE TITLE
[REQUEST] disable cpu proc graphs

### ISSUE THREAD

**Issue by wael444** [aristocratos/btop#372]
**Describe the solution you'd like**
have an option to disable the cpu graph in proc.

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/47404953/175437626-05b08910-d40a-43bd-bcf7-5fbc4b946a0f.png)

**Comment by aristocratos** [comment]
@wael444 
Added in commit 2d6bf1f4aaee3a83f5518406f7854de47e36e9fa

**Comment by wael444** [comment]
how come you didn't close this?

**Comment by wael444** [comment]
also in your commit atleast add 'solves #372'
