### ISSUE TITLE
[BUG] Must toggle "Force TTY" to disable TTY mode

### ISSUE THREAD

**Issue by melonedo** [aristocratos/btop#373]
**Describe the bug**

I use btop on RISC-V with qemu. It is exciting to see that btop really works on such a niche platform, however, I have to **toggle** "Force TTY" to disable TTY mode, no matter it was true or false before.

**To Reproduce**

1. Download ubuntu-20.04.2-preinstalled-server-riscv64 and run it on qemu
2. Build and run btop
3. Now TTY mode is enabled on **each** start
4. Toggle "Force TTY" to disable it

**Expected behavior**

The value of "Force TTY" should be respected.

**Info (please complete the following information):**
 - btop++ version: 1.2.7  (commit 7d86602e)
 - Compiler and version: g++-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
 - Architecture: riscv
 - Platform: Linux
 - Kernel: 5.13.0-1026-generic
 - Terminal used: probably qemu's default TTY 
 - Font used: Monospace

**Additional context**

<details>
<summary>contents of `~/.config/btop/btop.log`</summary>
```plain
2022/06/25 (18:08:25) | ===> btop++ v.1.2.7
2022/06/25 (18:08:25) | DEBUG: Starting in DEBUG mode!
2022/06/25 (18:08:25) | INFO: Logger set to DEBUG
2022/06/25 (18:08:25) | DEBUG: Using locale C.UTF-8
2022/06/25 (18:08:25) | INFO: Running on /dev/ttyS0
2022/06/25 (18:08:25) | INFO: Forcing tty mode: setting 16 color mode and using 
tty friendly graph symbols
2022/06/25 (18:08:30) | DEBUG: Loading theme file: /usr/local/share/btop/themes/
flat-remix.theme
2022/06/25 (18:08:30) | WARNING: get_cpuHZ() : Failed to read /sys/devices/syste
m/cpu/cpufreq/policy and /proc/cpuinfo.
2022/06/25 (18:08:35) | WARNING: Failed to join _runner thread on exit!
2022/06/25 (18:08:35) | DEBUG: Writing new config file
2022/06/25 (18:08:35) | INFO: Quitting! Runtime: 00:00:10

2022/06/25 (18:09:00) | ===> btop++ v.1.2.7
2022/06/25 (18:09:00) | DEBUG: Starting in DEBUG mode!
2022/06/25 (18:09:00) | INFO: Logger set to DEBUG
2022/06/25 (18:09:00) | DEBUG: Using locale C.UTF-8
2022/06/25 (18:09:00) | INFO: Running on /dev/ttyS0
2022/06/25 (18:09:00) | INFO: Real tty detected: setting 16 color mode and using tty friendly graph symbols
2022/06/25 (18:09:03) | WARNING: Failed to join _runner thread on exit!
2022/06/25 (18:09:03) | INFO: Quitting! Runtime: 00:00:03
```
</details>

**Comment by aristocratos** [comment]
@melonedo 
> Terminal used: probably qemu's default TTY

From your log file:
> 2022/06/25 (18:09:00) | INFO: Running on /dev/ttyS0
> 2022/06/25 (18:09:00) | INFO: Real tty detected: setting 16 color mode and using tty friendly graph symbols

Since it's obvious you're running in a real TTY and not a terminal emulator, why would you expect it to not start in TTY mode? And why would you disable TTY mode when you don't have support for truecolor or the characters needed to correctly display btop in non TTY mode?

If you want to force the TTY option in either direction read the README.md or run `btop --help` to see the command line arguments.

**Comment by melonedo** [comment]
Well I am not sure, but by toggling "Force TTY" I can indeed see colorful display and braille since I am running qemu in gnome terminal. My question is that why I need to toggle it or pass "+t" instead of using the option in the menu.



---Original---
From: "Jakob P. ***@***.***&gt;
Date: Mon, Jun 27, 2022 14:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aristocratos/btop] [BUG] Must toggle "Force TTY" to disable TTYmode (Issue #373)




 
@melonedo
  
Terminal used: probably qemu's default TTY
  
From your log file:
  
2022/06/25 (18:09:00) | INFO: Running on /dev/ttyS0
 2022/06/25 (18:09:00) | INFO: Real tty detected: setting 16 color mode and using tty friendly graph symbols
  
Since it's obvious you're running in a real TTY and not a terminal emulator, why would you expect it to not start in TTY mode? And why would you disable TTY mode when you don't have support for truecolor or the characters needed to correctly display btop in non TTY mode?
 
If you want to force the TTY option in either direction read the README.md or run btop --help to see the command line arguments.

**Comment by aristocratos** [comment]
@melonedo 
The "Force TTY" will still be toggled by the auto detection that triggers when running in a real TTY, unless turned off with the `+t` argument.

If the "Force TTY" option turned off the auto-detection, the auto-detection wouldn't serve any purpose since "Force TTY" is off by default.
The fact that you are running in a terminal emulator becomes opaque to btop since your qemu vm will look like a real TTY.
Why not just create an alias in your shell for `btop` to equal `btop +t`?
I'm not gonna break the default behavior (auto-detection) for everyone so that  the `+t` flag doesn't have to be used in one  niche use-case.

**Comment by melonedo** [comment]
Thanks! That was a detailed explanation.



---Original---
From: "Jakob P. ***@***.***&gt;
Date: Mon, Jun 27, 2022 15:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aristocratos/btop] [BUG] Must toggle "Force TTY" to disable TTY mode (Issue #373)




 
@melonedo
 The "Force TTY" will still be toggled by the auto detection that triggers when running in a real TTY, unless turned off with the +t argument.
 
If the "Force TTY" option turned off the auto-detection, the auto-detection wouldn't serve any purpose since "Force TTY" is off by default.
 The fact that you are running in a terminal emulator becomes opaque to btop since your qemu vm will look like a real TTY.
 Why not just create an alias in your shell for btop to equal btop +t?
 I'm not gonna break the default behavior (auto-detection) for everyone so that  the +t flag doesn't have to be used in one  niche use-case.

**Comment by aristocratos** [comment]
@melonedo 
Np :)
I'm assuming you running qemu in "nographic" mode or similar? Was confused at first since from the bug report I thought you were using the standard qemu SDL output, where TTY mode would make perfect sense.

**Comment by melonedo** [comment]
Yes, qemu -nographic, so it is correct to automatically force TTY mode.
The only surprising thing is that toggling the option, regardless of its value, makes a difference. Otherwise I would not haved considered this bug.



---Original---
From: "Jakob P. ***@***.***&gt;
Date: Mon, Jun 27, 2022 15:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aristocratos/btop] [BUG] Must toggle "Force TTY" to disable TTY mode (Issue #373)




 
@melonedo
 Np :)
 I'm assuming you running qemu in "nographic" mode or similar? Was confused at first since from the bug report I thought you were using the standard qemu SDL output, where TTY mode would make perfect sense.

**Comment by aristocratos** [comment]
@melonedo 
The auto-detection only runs once at start and only temporarily sets the value for "Force TTY", so it's not intended to block the user from changing it themselves.

It would be possible to add another option for "TTY autodetection" that can be turned off, but this is the first issue anybody raised about it.
