### ISSUE TITLE
[BUG] wrong characters on screen when using sc(4) on FreeBSD 13

### ISSUE THREAD

**Issue by bw-development** [aristocratos/btop#382]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**
After changing screen resolution to more night (640x480 text -> 1600x1200 graphics), output from btop app (formerly bpytop on-screen real-time monitoring tool) look like mess (see attached screen photos).

The same behavior for current btop app and for previous version - bpytop.
Only one exception: btop not start (display ERROR: No UTF-8 locale detected) automatically, and able to start only with key —utf-force that ignore UTF compability locale detection.

[UPDATE]
Other monitoring utility “gotop” have the same behavior: mess on a local-attached screen (ttyv0).

Better described here https://forums.freebsd.org/threads/how-to-solve-local-terminal-output-mess-for-btop-bpytop-formerly-resource-monitoring-tool.85687/

**To Reproduce**
Read thread on FreeBSD .org

**Expected behavior**
Normal work as on official screenshots.

**Screenshots**

**Info (please complete the following information):**
 - btop++ version: 1.2.7
 - Binary: static binary from release
 - Architecture: x86_64
 - Platform: FreeBSD
 - (OSX/FreeBSD) Os release version: 12.3-STABLE
 - Terminal used: local attached keyboard and monitor ttyv0

**Comment by bw-development** [comment]
btop.log

2022/06/30 (08:42:37) | ===> btop++ v.1.2.7
2022/06/30 (08:42:37) | WARNING: Failed to set locale en_US.UTF-8 continuing anyway.

**Comment by bw-development** [comment]
I trying to play with vidfont(1) to choosing different fonts with “UTF-8” in name:
- the issue still exist;
- the characters changing according selected font;

**Comment by aristocratos** [comment]
@bw-development 
I'm not sure what you are expecting me to do here?
The prerequisites are pretty clear about what's needed to run btop and having it look "correct".

Btop prints out ANSI escape sequences for formatting and coloring and relies on UTF-8 encoded fonts to display the correct symbols. If your terminal (or terminal emulator) of choice doesn't support either of those two requirements, it's simply not gonna work as intended.

**Comment by bw-development** [comment]
Thank You! 
I’ll try to change terminal app.
