### ISSUE TITLE
Different colors between root and normal user

### ISSUE THREAD

**Issue by roughnecks** [aristocratos/btop#390]
Hello,
why is that btop shows up differently based on the user's type I'm running it on?

This is on root: https://i.imgur.com/XooUHsN.jpeg
This is on a normal user: https://i.imgur.com/ujd2c9m.jpeg

Disk "graph" looks better on root but I really don't know what is the correct visual.

Thanks

P.S. Forgot to say that I'm running it on Debian Stable

**Comment by ErrorNoInternet** [comment]
Probably just different settings between users, like `/home/user1/.config/btop`, `/home/user2/.config/btop` and `/root/.config/btop`

**Comment by roughnecks** [comment]
you were right tho, I just deleted my user's conf and now btop looks the same as root.. Still not sure what I might have changed.

Thanks
