### ISSUE TITLE
[BUG] The last user in the user list is not displayed in the process list

### ISSUE THREAD

**Issue by D0LLYNH0** [aristocratos/btop#391]
**Describe the bug**

The last user listed in `/etc/passwd` is never displayed in the process list.

**Screenshots**

![Snap 517 • 14 07 2022 19h 37m 05s](https://user-images.githubusercontent.com/67797325/179100575-99ddee50-b940-4f27-a679-7654bd9c4cc7.png)

![Snap 516 • 14 07 2022 19h 35m 32s](https://user-images.githubusercontent.com/67797325/179100569-ac6caa10-c8f2-422c-b9f3-94b33f8c0443.png)

**Info (please complete the following information):**
 - btop++ version: 1.2.8
 - Binary: static binary from release
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.4.0-122-generic
 - Terminal used: Xterm
 - Font used: Lucida Console

**Comment by acid-bong** [comment]
Same behaviour with version 1.2.12 (Arch Linux). I feel like it was made to highlight human user's processes, but if that's actually the reason, it should detect the uid of the user it's run as

**Comment by aristocratos** [comment]
@D0LLYNH0 @acid-bong 
Should be fixed.
Try with latest commit, binaries at https://github.com/aristocratos/btop/actions/runs/3401813176

**Comment by D0LLYNH0** [comment]
@aristocratos, thanks. I confirm it has been fixed!

**Comment by acid-bong** [comment]
Same, fixed as well. Cheers
