### ISSUE TITLE
[BUG] Graph Drawing bug

### ISSUE THREAD

**Issue by Mitsunee** [aristocratos/btop#397]
**Describe the bug**

![image](https://user-images.githubusercontent.com/19474909/180736567-dac50384-8420-4f08-bad4-de4fdd7cd5b9.png)

I often get these impossible graphs. I sadly do not know the specifics. When this behaviour occurs every other frame drawn has this issue.

I'm currently running Fedora 36 KDE (X11 mode) on an AMD Ryzen 5 5600X and RX6600XT. I'm using Konsole running Bash, previously used Terminator running Bash on Kubuntu 21.10 (also X11) with the same issue.

**To Reproduce**

Unsure :\

**Expected behavior**

Graphs should always look normal.

**Info (please complete the following information):**
 - btop++ version: 1.2.8
 - Binary: self compiled after running `git checkout v1.2.8`
 - (If compiled) Compiler and version: unsure as I ran the script provided in the repo
 - Architecture: x86_64
 - Platform: Linux, Fedora 36, KDE X11
 - (Linux) Kernel: 5.18.13-200.fc36.x86_64
 - Terminal used: Konsole and Terminator
 - Font used: Konsole uses Hack Nerd Font, while Terminator had Ubuntu Mono Nerd Font

**Additional context**

contents of `~/.config/btop/btop.log`

```
2022/07/25 (10:53:48) | ===> btop++ v.1.2.8
2022/07/25 (10:53:48) | DEBUG: Starting in DEBUG mode!
2022/07/25 (10:53:48) | INFO: Logger set to DEBUG
2022/07/25 (10:53:48) | DEBUG: Setting LC_ALL=en_US.UTF-8
2022/07/25 (10:53:48) | INFO: Running on /dev/pts/1
2022/07/25 (10:53:48) | DEBUG: Loading theme file: /usr/local/share/btop/themes/monokai.theme
2022/07/25 (10:54:04) | INFO: Quitting! Runtime: 00:00:16
```

I did two runs with `--debug` and both have virtually the same debug log, while only the second run had the glitchy graphs.

**Comment by Mitsunee** [comment]
Can still reproduce this bug in 1.2.9 (self compiled after running `git checkout v1.2.9`)

**Comment by aristocratos** [comment]
@Mitsunee 
The symbols are hardcoded:
https://github.com/aristocratos/btop/blob/24f06094f8e573e0c85f01b989bd5e9313114edf/src/btop_draw.cpp#L59-L72


This is a font/terminal issue not a btop bug, try another font/terminal.
