### ISSUE TITLE
[REQUEST] AppImage release option

### ISSUE THREAD

**Issue by JaxxArmstrong** [aristocratos/btop#4]
Hello,

Thank you for this resource monitoring utility, but may I recommend that you consider package it as an AppImage for easy of use and wider adoption, please.

AppImages are very easy to create and can easily be automated for new releases.

**Comment by aristocratos** [comment]
I would argue that downloading the `btop.tbz` for your architecture, unpacking and double-clicking `install.sh` is easy enough.
It's already statically compiled so will work unless you've got a really outdated kernel (older than 3.2.0).

I'm hoping that it will eventually get picked up by package maintainers for the different distros (like what happened with bashtop and bpytop).

But it's also worth considering that I released it yesterday, so there's likely plenty of bugs to still fix before considering it absolutely stable.

**Comment by truatpasteurdotfr** [comment]
For information, btop builds fine on CentOS-7 x86_64 with the devtoolset-10 toolchain.

**Comment by mystrdat** [comment]
Also would like to see AppImage, somehow it feels right for this kind of software. Similar libs are also distributed in the format:
https://github.com/Syllo/nvtop/releases 
https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/releases.

The install script is certainly easy and you made it look really good (just like the whole lib), but having the OS integration, sandboxing and updating handled on all Linux flavors by the same distribution mechanism seems quite valuable. I'm still rather new Linux development but could give `appimage-builder` a try if you're not opposed to it @aristocratos
