### ISSUE TITLE
[REQUEST] distribute application via AUR as package

### ISSUE THREAD

**Issue by replicadse** [aristocratos/btop#40]
Amazing work, very nice system monitor!
I would love to see btop being distributed as a package on the Arch User Repository (AUR). Writing the PKGBUILD should be quite straight forward. The `setuid` step of the installation could be a question to ask during that install.
I might even go ahead and submit a PR for this if I find some time to check out how the best practices for C++ apps are.

**Comment by jbpratt** [comment]
Here is the package I've been using https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=btop

**Comment by replicadse** [comment]
I don't know how but I somehow msised that. Thanks for pointing that out - issue closed then I guess :D
