### ISSUE TITLE
[REQUEST] make this program c++17 instead of c++20

### ISSUE THREAD

**Issue by minneelyyyy** [aristocratos/btop#400]
I am not exactly using a totally old setup, I'm using plain WSL 2 with the default Ubuntu setup, and I CANNOT very easily install this program. It requires me to compile a modern version of gcc and clang, and even with a new compiler I still need libs.

![image](https://user-images.githubusercontent.com/79120883/182460408-fbf7f647-ba4b-4b50-8dd0-ae0587760261.png)

Using just a slightly older version of C++ would help a ton with this issue. It's hard to tell exactly how much work needs to be done, but it can be done slowly over time. This would easily make the program that much more portable without changing the usability all that much, C++17 is very usable by todays standard.

I won't be too mad if this doesn't go through, but it just makes the program insanely difficult for me to actually use. I'm positive that I am not the only person who cant use C++20, its only 2 years old at this point.

Using the most recent version of a language like C or C++ is not always the best option, it comes at the very big cost of portability. That's why I **still** use C99 or even C89, even if newer versions have fancy new features that make the language easier.

**Comment by aristocratos** [comment]
@minneelyyyy 
If you read the README.md and look at the release pages you'll notice that are static compiled binaries for most architectures, use them if you can't compile yourself.

I'm not gonna rewrite code written in modern c++ because you don't want to upgrade your distribution/compiler...
