### ISSUE TITLE
[BUG] Graph Drawing bug 1

### ISSUE THREAD

**Issue by finflaex** [aristocratos/btop#405]
![изображение](https://user-images.githubusercontent.com/13582750/185548892-e20f1761-6373-4fe0-b3c6-e49f9b045caf.png)

on all charts, the edges of the peaks are shifted, this was not observed in older versions (unfortunately, I do not remember the version)

btop version: 1.2.8
cat /etc/lsb-release && uname -r
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
5.19.1-051901-generic

**Comment by finflaex** [comment]
![изображение](https://user-images.githubusercontent.com/13582750/185550920-682715da-73eb-4df6-814d-4bf783dd6881.png)

**Comment by aristocratos** [comment]
@finflaex 
This is a font issue not a btop issue, read the [prerequisites](https://github.com/aristocratos/btop#prerequisites).
I have no control over what font you use or how the terminal you use renders those fonts.
