### ISSUE TITLE
[REQUEST] Snap size is getting big using gnome-3-38-2004 and gtk-common-themes

### ISSUE THREAD

**Issue by daniejstriata** [aristocratos/btop#407]
The snap is now requiring gnome-3-38-2004 which adds another 401M and gtk-common-themes of 92M to the storage requirements to run the snap version of btop. @kz6fittycent Is the required on a server? Is there not a not a possibility of a version not requiring the extra packages? btop worked fine before.

**Comment by kz6fittycent** [comment]
It's not required on any server, but I am running the same snap on all my servers. 

I want to keep pace w/ what's available via the other binaries (e.g. `.deb`). 

If there's an option for the desktop users to have a desktop icon, it makes sense to me for that to be available within the snap. 

Here's what I'm seeing on my server(s):

![image](https://user-images.githubusercontent.com/14829816/186021896-302705c6-7b3e-462e-8b01-54ac2baea6c8.png)

@aristocratos what are your thoughts? Does it matter to you that the snap mirrors the other available binaries or should we just remove the desktop launcher from the snap? I'm NOT keen on the idea of 2 separate snaps.

**Comment by aristocratos** [comment]
@kz6fittycent 
Why does the desktop icon require gnome to be installed?
The snap is your thing so it's up to you how you wanna handle it, but I can certainly see @daniejstriata's point, 500M of extra needed space is a lot.

**Comment by kz6fittycent** [comment]
> @kz6fittycent Why does the desktop icon require gnome to be installed? The snap is your thing so it's up to you how you wanna handle it, but I can certainly see @daniejstriata's point, 500M of extra needed space is a lot.

Yeah it pulls it in automatically so that it'll display. We can revert back to the "terminal only" snap. I really don't have any issue with _not_ having the desktop icon - just wanted to mirror what you've got available.

**Comment by kz6fittycent** [comment]
Okay, I talked myself into creating a separate desktop snap...what in the world is wrong with me. Sigh.
