### ISSUE TITLE
[Request] Radeontop utilization option to create comprehensive system overview dashboard

### ISSUE THREAD

**Issue by iamhumanipromise** [aristocratos/btop#415]
**Example**: Currently, multiple tmux sessions are required or multiple local terminal sessions are required for btop and radeontop. 

**Use case:** System dashboard for monitoring mission-critical system. Btop could show customizable usage bars/meters based on the ones from radeontop. Customizable themes/colors per usual btopiness. 

[Radeontop Github](https://github.com/clbr/radeontop)

Additionally, I have [opened a request](https://github.com/clbr/radeontop/issues/137) to add lm-sensors support to radeontop. 

Failing that, or in spite of that, **please also consider adding voltage, watt usage, fan speed, and GPU temp** as dashboard options to b-top.

**Comment by Atrate** [comment]
It'd be nice if it worked for Nvidia GPUs as well, like [nvtop](https://github.com/Syllo/nvtop).
