### ISSUE TITLE
[BUG] Filtering processes causes crash

### ISSUE THREAD

**Issue by guillaumeboehm** [aristocratos/btop#417]
**Describe the bug**

When filtering processes btop crashes after more or less time. (Not sure but seems to crash faster when selecting a process or showing more info about the process with RET)

**To Reproduce**

- Open btop
- Filter processes (can be anything it seems)
- Crashes after more or less time

**Expected behavior**

To not crash.

**Info (please complete the following information):**
 - btop++ version: `1.2.9`
 - Binary: both
 - (If compiled) Compiler and version: `g++ 12.2.0`
 - Architecture: [x86_64, aarch64, etc.] `x86_64`
 - Platform: `Linux`
 - (Linux) Kernel: `5.19.6-zen1-1-zen`
 - Terminal used: `kitty 0.26.1`
 - Font used: `FiraCode Nerd Font Mono`

**Additional context**

I'm using vim mode if it changes anything.

contents of `~/.config/btop/btop.log`
```
2022/09/06 (11:15:23) | ===> btop++ v.1.2.9
2022/09/06 (11:15:23) | DEBUG: Starting in DEBUG mode!
2022/09/06 (11:15:23) | INFO: Logger set to DEBUG
2022/09/06 (11:15:23) | DEBUG: Using locale en_US.UTF-8
2022/09/06 (11:15:23) | INFO: Running on /dev/pts/4
2022/09/06 (11:15:23) | DEBUG: Loading theme file: /usr/share/btop/themes/gruvbox_dark_v2.theme
2022/09/06 (11:15:32) | ERROR: Exception in runner thread -> Proc:: -> basic_string::replace: __pos (which is 18446744073709551608) > this->size() (which is 0)
2022/09/06 (11:15:32) | INFO: Quitting! Runtime: 00:00:09
```

- The bug occurred in urxvt with a different font too, so likely not the issue.
- The bug still occurs when the filtering doesn't return any matches.

**GDB Backtrace**

No stack

**Comment by aristocratos** [comment]
@guillaumeboehm 
Is this happening when displaying processes in "tree" mode?
Because the exception eludes to a `basic_string::replace` being the cause of the crash and the only string replace commands I can find seem to be related to "tree" mode being active.

I can't reproduce this issue so not sure where else to look right now.

**Comment by NopoTheGamer** [comment]
> @guillaumeboehm Is this happening when displaying processes in "tree" mode?

Not OP but this happens to me only when I'm in tree mode

My log is just 
```2022/10/02 (21:16:00) | ===> btop++ v.1.2.9
2022/10/02 (21:16:00) | ERROR: Exception in runner thread -> Proc:: -> basic_string::replace: __pos (which is 18446744073709551608) > this->size() (which is 0)

**Comment by guillaumeboehm** [comment]
I use tree mode indeed, I don't remember testing without tree mode.

**Comment by aristocratos** [comment]
@guillaumeboehm @NopoTheGamer 
I've added some extra guards that hopefully fixes this issue, would you guys mind either compiling with latest commit or downloading binary from https://github.com/aristocratos/btop/actions/runs/3168382437 and test if it works?

**Comment by NopoTheGamer** [comment]
Yep the downloaded binary works thanks!

**Comment by guillaumeboehm** [comment]
Sorry I can't test right now I'm bed ridden lmao.

**Comment by aristocratos** [comment]
@guillaumeboehm No worries :) I'm pretty certain it's fixed from @NopoTheGamer's test.
We'll leave this issue open until you have had a chance to test it, and if it works, just close it :)

**Comment by guillaumeboehm** [comment]
Seems good, I can't seem to reproduce the bug anymore.
