### ISSUE TITLE
[BUG] `btop` crashes when number of CPU cores enabled < number of CPU cores total

### ISSUE THREAD

**Issue by BSGalvan** [aristocratos/btop#439]
**Describe the bug**

 `btop` crashes with an error when only some of the available cores on a CPU are configured to run.
The error message is this: `ERROR: Exception in Shared::init() -> collect() : stoi`

**To Reproduce**

The initial error occurred on a work desktop which I do not have access to as of writing this.
 On it however, 16 out of 32 CPU cores were enabled.

CPU cores can be manually disabled using [`chcpu(8)`](https://www.mankier.com/8/chcpu), so this is what I did to reproduce the error on my Ryzen 7 4750U laptop:

1. `sudo chcpu -d 4-15` (kind of overkill, but on another laptop with an i5-7200U, knocking out 1 or 2 did suffice)
2. run `btop`, which throws this error: `ERROR: Exception in Shared::init() -> collect() : stoi`

**Expected behavior**

`btop` should show at least the usual UI, but with lesser CPUs in the 'CPU' box (which indicates that some of them are disabled).

This is what it shows now:
![2022-10-05-124142_1920x1080_scrot](https://user-images.githubusercontent.com/38353913/194011099-c71867bb-49fe-4060-9ccc-9fc993c1432e.png)

Whereas this is what I expect it to show:
![2022-10-05-124417_1920x1080_scrot](https://user-images.githubusercontent.com/38353913/194011124-04f3d154-e3cd-4412-a011-5ed42868eef5.png)

Note: I was able to get the above by reverting the change in 96b770c. However, I do not know if that is a sensible bug fix, hence an issue instead of a PR! 

**Screenshots**

**Info (please complete the following information):**
 - btop++ version: 1.2.9
 - Binary: compiled from source, at commit 2b02a66
 - (If compiled) Compiler and version: gcc version 11.3.0 (Gentoo Hardened 11.3.0 p4)
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.15.69-gentoo
 - (OSX/FreeBSD) Os release version: N/A
 - Terminal used: st
 - Font used: FiraCode NerdFont

**Additional context**

Contents of `~/.config/btop/btop.log`:

```
2022/10/05 (12:49:02) | ===> btop++ v.1.2.9
2022/10/05 (12:49:02) | DEBUG: Starting in DEBUG mode!
2022/10/05 (12:49:02) | INFO: Logger set to DEBUG
2022/10/05 (12:49:02) | DEBUG: Using locale en_US.utf8
2022/10/05 (12:49:02) | INFO: Running on /dev/pts/3
2022/10/05 (12:49:02) | DEBUG: get_cpuHz() : stoi
2022/10/05 (12:49:02) | ERROR: Exception in Shared::init() -> collect() : stoi
2022/10/05 (12:49:02) | INFO: Quitting! Runtime: 00:00:00
```

**GDB Backtrace**
```
GNU gdb (Gentoo 11.2 vanilla) 11.2
--- omitted for brevity ---
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from btop...
(No debugging symbols found in btop)
(gdb) r
Starting program: /usr/bin/btop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
ERROR: Exception in Shared::init() -> collect() : stoi
[Inferior 1 (process 3197) exited with code 01]
(gdb) thread apply all bt
(gdb)
```

**Comment by aristocratos** [comment]
@BSGalvan 
Can you post the output of `/proc/stat` when you have some cores disabled.

**Comment by BSGalvan** [comment]
Here you go, output of `cat /proc/stat` after `chcpu -d 4-15`:
 
```
cpu  585677 3980 141041 6709601 3496 0 1849 0 0 0
cpu0 106694 522 23916 862478 1109 0 1531 0 0 0
cpu1 74817 217 20002 3498 8 0 67 0 0 0
cpu2 79505 540 22266 3354 6 0 96 0 0 0
cpu3 72573 557 19701 3442 8 0 13 0 0 0
intr 30075083 114 323 0 0 0 0 0 0 12680 9339 0 0 982 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 198 6568 0 0 0 0 37 22 0 0 0 0 0 0 0 0 0 168 101 56 75 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 126054 53866 1730 2783 2307 919 2645 1565 1100 2455 1332 2974 29062 2042 4783 17 1662806 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 47713632
btime 1664947501
processes 80959
procs_running 1
procs_blocked 0
softirq 13138886 86712 1261465 163 237461 115 0 38543 5111595 162 6402670
```

**Comment by aristocratos** [comment]
@BSGalvan
Was a counting issue, the last core was missed if not enabled. Fixed in latest commit.
Binaries: https://github.com/aristocratos/btop/actions/runs/3188452086

**Comment by BSGalvan** [comment]
Awesome! Thanks for the quick fix :smile:
Closing.
