### ISSUE TITLE
[REQUEST] Makefile: verbose mode support

### ISSUE THREAD

**Issue by NexAdn** [aristocratos/btop#442]
**Is your feature request related to a problem? Please describe.**

When building the project, the exact command-lines used are not visible.
The main issue is that it sometimes makes build logs harder to read,
especially when there is a bug report from another person (e.g. in [Gentoo Bug 876319](https://bugs.gentoo.org/876319) I am unable to see which CXXFLAGS the author of the bug had set).
This makes debugging harder or at least requires extra communication.

**Describe the solution you'd like**

I'd like to have something like a verbose mode where the whole build command which is executed is shown.

**Describe alternatives you've considered**

The current output already shows the options set using various other variables in the Makefile.
However, this does not show the whole set of compiler flags.
When setting custom CXXFLAGS (e.g. `make CXXFLAGS=-blah`) these are not shown in the build output.

**Comment by stefanos82** [comment]
The reason it's not showing it is because you should be using a different flag, named `ADDFLAGS`.

Can you try running `make info ADDFLAGS=-fhello-world=true` and see whether it displays the mock flag or not?

**Comment by NexAdn** [comment]
> The reason it's not showing it is because you should be using a different flag, named `ADDFLAGS`. 
> Can you try running `make info ADDFLAGS=-fhello-world=true` and see whether it displays the mock flag or not?

This does indeed show the flag used:

```
$ make ADDFLAGS=-blah

<snip>

REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=4
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector -blah
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
```

However, this isn't a good solution.
The `CXXFLAGS` environment variable _is_ respected in the sense that all the flags used by btop are appended to CXXFLAGS.
So in the event I e.g. accidentally have set CXXFLAGS in my shell to some weird values (or I don't know if the person sending me a bug report has),
I have no way to see the whole set of flags used in the current build output.
And since the author of the Makefile wrote `override CXXFLAGS +=` and the info output shows `+|` for CXXFLAGS,
I must assume it is intended that CXXFLAGS are _not_ overriden, but appended.

The next thing to consider is that the flags for the include directories or flags used for a special compile unit aren't shown either.
Again, this can be a crucial information while debugging.

While you can certainly generate info messages for all the flags,
just supporting some kind of verbose mode (like e.g. `ninja -v`) makes life easier and permanently solves the issue of determining which flags are used to compile which object.

**Comment by stefanos82** [comment]
Yes, I understand what you are saying and to be honest with you, with my initial attempt to play with `btop`, I had replaced `*FLAGS` with `+=` operator so I could turn on and off specific custom flags of mine based on custom defined macro names; this way was easier to debug each `make <foo>` I have originally setup for testing purposes.

I guess we need a `make verbose` for verbosity during compilation procedure.

Thoughts?

**Comment by aristocratos** [comment]
@NexAdn
Hi, shouldn't be an issue to add so any already existing `$CXXFLAGS` and `$LDFLAGS` are shown in the normal output. Like:

```bash
$ make CXXFLAGS=-blah1 LDFLAGS=-blah2

REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=4
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS) -blah1
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS) -blah2
```

Also shouldn't be an issue to add a verbose mode where all the full commands are also printed.

**Comment by stefanos82** [comment]
I have just tested it and either I'm doing something wrong or it's not working as expected...?

![image](https://user-images.githubusercontent.com/1777466/194844892-f71b2c07-be00-4f46-83c5-722e3a0884d2.png)

**Comment by aristocratos** [comment]
@stefanos82 
> I have just tested it and either I'm doing something wrong or it's not working as expected...?

Well I guess that would be kinda expected if you try it before it was added...

"Will take a look at it when I've got some time."
 Turns out I had some time now.

**Comment by aristocratos** [comment]
Output with verbose flag:
```bash
$ make VERBOSE=true CXXFLAGS=-Dtest1 LDFLAGS=-Dtest2

 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.5
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++-11 (11.2.0)
THREADS    :| 8
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=8
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector 
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS) -Dtest1
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS) -Dtest2

Building btop++ (v1.2.12) Linux x86_64
Compiling src/btop.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop.o src/btop.cpp
Compiling src/btop_config.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_config.o src/btop_config.cpp
Compiling src/btop_draw.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_draw.o src/btop_draw.cpp
Compiling src/btop_input.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_input.o src/btop_input.cpp
Compiling src/btop_shared.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_shared.o src/btop_shared.cpp
Compiling src/btop_theme.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_theme.o src/btop_theme.cpp
Compiling src/btop_menu.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_menu.o src/btop_menu.cpp
Compiling src/btop_tools.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/btop_tools.o src/btop_tools.cpp
10%  -> obj/btop_theme.o              (1,4MiB) (05s)
Compiling src/linux/btop_collect.cpp
g++-11 -Dtest1 -std=c++20 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic -Iinclude -Isrc -MMD -c -o obj/linux/btop_collect.o src/linux/btop_collect.cpp
20%  -> obj/btop_input.o              (1,4MiB) (06s)
30%  -> obj/btop_config.o             (1,5MiB) (06s)
50%  -> obj/btop_tools.o              (1,4MiB) (06s)
50%  -> obj/btop.o                    (1,8MiB) (06s)
60%  -> obj/btop_shared.o             (1,7MiB) (06s)
70%  -> obj/btop_menu.o               (2,0MiB) (06s)
80%  -> obj/btop_draw.o               (2,3MiB) (07s)
90%  -> obj/linux/btop_collect.o      (3,1MiB) (06s)

Linking and optimizing binary...
g++-11 -o bin/btop obj/btop.o obj/btop_config.o obj/btop_draw.o obj/btop_input.o obj/btop_menu.o obj/btop_shared.o obj/btop_theme.o obj/btop_tools.o obj/linux/btop_collect.o -Dtest2 -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector  -O2 -ftree-loop-vectorize -flto=8 -Wall -Wextra -pedantic
100% -> bin/btop                      (1,5MiB) (06s)

Build complete in (17s)
```

**Comment by NexAdn** [comment]
Works as expected. Thank you very much!
