### ISSUE TITLE
[BUG] Display wrong in macOS

### ISSUE THREAD

**Issue by shoyuf** [aristocratos/btop#447]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**
run btop without normal

the reason may be i install btop with homebrew before change system account, but i already delete old system account

I already clear btop.conf and btop.log can't send out any useful information

[A clear and concise description of what the bug is.]

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**
Display normal
[A clear and concise description of what you expected to happen.]

**Screenshots**
![image](https://user-images.githubusercontent.com/27998490/196576844-d980e586-b87d-419e-b31d-e56c178ed79d.png)
[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: `btop -v` 1.2.9 and 1.2.12
 - Binary: [self compiled or static binary from release] homebrew and github release
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m` x86
 - Platform: [Linux, FreeBSD, OsX]. OS X
 - (Linux) Kernel: `uname -r`
 - (OSX/FreeBSD) Os release version:  12.5
 - Terminal used: iTerm and Terminal.app and iTerm with ssh
 - Font used: unset

**Additional context**
I try to unset theme, It has same display

```log
2022/10/19 (09:37:56) | ===> btop++ v.1.2.9
2022/10/19 (09:37:56) | INFO: Logger set to DEBUG
2022/10/19 (09:37:56) | DEBUG: Setting LC_ALL=zh_CN.UTF-8
2022/10/19 (09:37:56) | INFO: Running on /dev/ttys001
2022/10/19 (09:37:56) | DEBUG: get_sensors(): show_coretemp=0 check_temp=0
2022/10/19 (09:37:56) | DEBUG: Loading theme file: /Users/jenkins/.config/btop/themes/adapta.theme
```

**Comment by aristocratos** [comment]
@shoyuf 
Try from the btop source folder: `sudo make uninstall && sudo make install` and see if it runs.

**Comment by shoyuf** [comment]
> @shoyuf Try from the btop source folder: `sudo make uninstall && sudo make install` and see if it runs.

It‘s works, Thank you!
