### ISSUE TITLE
[BUG] Link error on Btop compilation

### ISSUE THREAD

**Issue by Thisora** [aristocratos/btop#451]
**Read the README.md and search for similar issues before posting a bug report!**

 -Done  ;-)

**Describe the bug**

Linker error for for macos 13.0.0. Linker error:
ld: -rpath can only be used when targeting Mac OS X 10.5 or later

Total gmake logs:
```
PLATFORM   ?| macos
ARCH       ?| arm64
CXX        ?| g++-11 (11.3.0)
THREADS    :| 8
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=8
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS    -framework IOKit -framework CoreFoundation -Wno-format-truncation
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.24) macos arm64
Compiling src/btop_tools.cpp
Compiling src/btop_draw.cpp
Compiling src/btop_input.cpp
Compiling src/btop_menu.cpp
Compiling src/btop_config.cpp
Compiling src/btop_theme.cpp
Compiling src/btop.cpp
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
Compiling src/osx/btop_collect.cpp
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
-> obj/btop_tools.o                (516KiB) (02s)
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
Compiling src/osx/sensors.cpp
-> obj/btop_input.o                (644KiB) (02s)
g++-11: warning: could not understand version '13.00.00'
-> obj/btop_theme.o                (680KiB) (02s)
-> obj/btop_config.o               (740KiB) (03s)
Compiling src/osx/smc.cpp
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
g++-11: warning: could not understand version '13.00.00'
-> obj/osx/sensors.o               ( 60KiB) (01s)
-> obj/btop.o                      (864KiB) (03s)
g++-11: warning: could not understand version '13.00.00'
-> obj/osx/smc.o                   ( 28KiB) (00s)
g++-11: warning: could not understand version '13.00.00'
-> obj/btop_menu.o                 (1,1MiB) (04s)
g++-11: warning: could not understand version '13.00.00'
-> obj/osx/btop_collect.o          (2,0MiB) (06s)
g++-11: warning: could not understand version '13.00.00'
-> obj/btop_draw.o                 (1,8MiB) (07s)

Linking and optimizing binary...
g++-11: warning: could not understand version '13.00.00'
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:210: btop] Error 1
```

**To Reproduce**
```
On mac M1 with osx version 13 (Ventura):
brew install coreutils make gcc@11
git checkout OSX
gmake
```
**Expected behavior**

Compile btop.

**Comment by aristocratos** [comment]
@Thisora 
Yeah, noticed it just two days ago when I updated my Mac mini M1 to Ventura.
It fails when compiling with gcc11, gcc12 regardless if compiling for arm64 or x86_64.
Haven't tested gcc10 yet, but I'm guessing it will be the same.
Will look in to it when I've got time.

**Comment by aristocratos** [comment]
@Thisora 
You'll get by the linker error:
```
g++-11: warning: could not understand version '13.00.00'
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
```
if compiling with gcc12, there however seems to be a different bug in the latest xcode command line tools for Ventura causing another linker bug: https://stackoverflow.com/questions/73714336/xcode-update-to-version-2395-ld-compile-problem-occurs-computedatomcount-m

So should be able to compile if you use gcc12 and downgrade the tools to 13.4 version until Apple fixes it.

**Comment by aristocratos** [comment]
Downloading latest command line tools from https://developer.apple.com/download/all/?q=xcode and using gcc12 `gmake CXX=g++-12`confirmed working.

**Comment by Thisora** [comment]
Thank you very !
I was also searching for a workaround but you were faster than me !
Now i have successful comilation but segmentation fault on launch 😖

**Comment by aristocratos** [comment]
Make sure you run `make clean` before compiling.

**Comment by aristocratos** [comment]
There also seems to be a consistent issue on macos that if you install over a previous installation were you also ran `gmake setuid` it fails to run unless you first run `gmake uninstall`.

**Comment by aristocratos** [comment]
Also updated the Makefile in the latest commit so it should automatically choose gcc12 if detected and no other compiler has been manually set with `CXX=`.

**Comment by Thisora** [comment]
I tried to run after `make clean`, still segfault, i also tried to run `gmake uninstall` and compile everything i still have segfault.
For now i run directly from `/bin/btop` so i don't think installation or setuid change anything ?

**Comment by aristocratos** [comment]
Are you also using `gmake setuid` ? That could possibly be the issue in that case.

**Comment by aristocratos** [comment]
No working fine.
Try uninstalling again and then install and don't run `sudo gmake setuid`

**Comment by Thisora** [comment]
> No working fine. Try uninstalling again and then install and don't run `sudo gmake setuid`

Still have segfault

**Comment by aristocratos** [comment]
Do you by chance have more than one btop installed? Since it doesn't make much sense that it would work in the build folder but not when copied to `/usr/local/bin`.

If you uninstall and run `which btop` does it find anything?

**Comment by Thisora** [comment]
Oh my bad i wasn't clear, i tried to run directly from build folder and same error happended.

**Comment by aristocratos** [comment]
Oh, what's the full command you use when compiling?

**Comment by Thisora** [comment]
Just using `make` ? I think i misunderstood your question

**Comment by aristocratos** [comment]
What output do you get if you run `gmake distclean && gmake VERBOSE=true`

**Comment by Thisora** [comment]
> What output do you get if you run `gmake distclean && gmake VERBOSE=true`

```
PLATFORM   ?| macos
ARCH       ?| arm64
CXX        ?| g++-12 (12.2.0)
THREADS    :| 8
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=8
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection  -framework IOKit -framework CoreFoundation -Wno-format-truncation
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
```

**Comment by aristocratos** [comment]
It's the part below that I'm mostly interested in.

**Comment by Thisora** [comment]
Oh sorry i thought you would check args. Here is the full output :
```PLATFORM   ?| macos
ARCH       ?| arm64
CXX        ?| g++-12 (12.2.0)
THREADS    :| 8
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=8
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-clash-protection  -framework IOKit -framework CoreFoundation -Wno-format-truncation
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.24) macos arm64
Compiling src/btop_theme.cpp
Compiling src/btop_draw.cpp
Compiling src/btop_tools.cpp
Compiling src/btop_input.cpp
Compiling src/btop.cpp
Compiling src/btop_menu.cpp
Compiling src/btop_config.cpp
Compiling src/osx/btop_collect.cpp
-> obj/btop_tools.o                (520KiB) (02s)
-> obj/btop_input.o                (632KiB) (02s)
-> obj/btop_theme.o                (660KiB) (02s)
Compiling src/osx/sensors.cpp
-> obj/btop_config.o               (732KiB) (03s)
Compiling src/osx/smc.cpp
-> obj/btop.o                      (848KiB) (03s)
-> obj/osx/sensors.o               ( 60KiB) (01s)
-> obj/osx/smc.o                   ( 28KiB) (00s)
-> obj/btop_menu.o                 (1,1MiB) (05s)
-> obj/osx/btop_collect.o          (1,9MiB) (06s)
-> obj/btop_draw.o                 (1,7MiB) (07s)

Linking and optimizing binary...
-> bin/btop                        (988KiB) (03s)

Build complete in (11s)
```

**Comment by aristocratos** [comment]
> Building btop++ (v1.0.24) 

Um, current version of btop is v1.2.12, v1.0.24 would be about a year old...

**Comment by Thisora** [comment]
Hummm i feel so confuse i checked out the branch OSX because i thought that would solve initial issue... I noticed it in 'step to reproduce'

For now it works on main branch !

**Comment by aristocratos** [comment]
Np :)
The OSX branch is the branch used during initial development for macos, it's only saved to follow the git history before the merge to main.
