### ISSUE TITLE
[REQUEST] Use the first IP of the network interface, instead of the last, in the NET box.

### ISSUE THREAD

**Issue by correabuscar** [aristocratos/btop#456]
**Is your feature request related to a problem? Please describe.**
In a case such as the following (output from `$ ip a`) ie. when network interface has more than one IP associated with it:
```
2: em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 12:34:56:78:90:AB brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.2/16 brd 192.168.255.255 scope global em1
       valid_lft forever preferred_lft forever
    inet 169.254.0.100/24 brd 169.254.0.255 scope global em1
       valid_lft forever preferred_lft forever
```
The last IP (`169.254.0.100`) is being displayed by `btop` in the NET box for the `em1` interface, but I want the first one (`192.168.0.2`) instead. (`nload` uses the first one too, and it is coincidentally(?) the IP that I use to connect to the internet from this computer ie. gateway is on this subnet)

**Describe the solution you'd like**
```patch
Index: /var/tmp/portage/sys-process/btop-1.2.12/work/btop-1.2.12/src/linux/btop_collect.cpp
===================================================================
--- .orig/var/tmp/portage/sys-process/btop-1.2.12/work/btop-1.2.12/src/linux/btop_collect.cpp
+++ /var/tmp/portage/sys-process/btop-1.2.12/work/btop-1.2.12/src/linux/btop_collect.cpp
@@ -26,6 +26,7 @@ tab-size = 4
 #include <netdb.h>
 #include <ifaddrs.h>
 #include <net/if.h>
+#include <arpa/inet.h>
 #include <thread>
 
 #if !(defined(STATIC_BUILD) && defined(__GLIBC__))
@@ -1374,25 +1375,36 @@ namespace Net {
 				return empty_net;
 			}
 			int family = 0;
-			char ip[NI_MAXHOST];
+			//char ip[NI_MAXHOST]; // NI_MAXHOST is 1025
+			const static int IPBUFFER_MAXSIZE=std::max(INET_ADDRSTRLEN, INET6_ADDRSTRLEN);
+			// INET6_ADDRSTRLEN is 46, INET_ADDRSTRLEN is 16
+			char ip[IPBUFFER_MAXSIZE];
 			interfaces.clear();
 			string ipv4, ipv6;
 
 			//? Iteration over all items in getifaddrs() list
-            for (auto* ifa = if_wrap(); ifa != NULL; ifa = ifa->ifa_next) {
+			for (auto* ifa = if_wrap(); ifa != NULL; ifa = ifa->ifa_next) {
 				if (ifa->ifa_addr == NULL) continue;
 				family = ifa->ifa_addr->sa_family;
 				const auto& iface = ifa->ifa_name;
 
-				//? Get IPv4 address
-				if (family == AF_INET) {
-					if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in), ip, NI_MAXHOST, NULL, 0, NI_NUMERICHOST) == 0)
-						net[iface].ipv4 = ip;
-				}
-				//? Get IPv6 address
-				else if (family == AF_INET6) {
-					if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in6), ip, NI_MAXHOST, NULL, 0, NI_NUMERICHOST) == 0)
-						net[iface].ipv6 = ip;
+				struct in_addr addr = reinterpret_cast<struct sockaddr_in*>(ifa->ifa_addr)->sin_addr;
+				if (NULL != inet_ntop(family, &addr, ip, IPBUFFER_MAXSIZE)) { //FIXME: blatantly assumes `family` can be only AF_INET or AF_INET6.
+					//? Get IPv4 address
+					if (family == AF_INET) {
+						//if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in), ip, NI_MAXHOST, NULL, 0, NI_NUMERICHOST) == 0)
+						if (net[iface].ipv4.empty()) {  //use the first encountered IP for the interface, not the last!
+							net[iface].ipv4 = ip;
+						}
+					}
+					//? Get IPv6 address
+					else if (family == AF_INET6) {
+						//if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in6), ip, NI_MAXHOST, NULL, 0, NI_NUMERICHOST) == 0)
+						//if (NULL != inet_ntop(family, ifa->ifa_addr, ip, INET6_ADDRSTRLEN))
+						if (net[iface].ipv6.empty()) {  //use the first encountered IP for the interface, not the last!
+							net[iface].ipv6 = ip;
+						}
+					}
 				}
 
 				//? Update available interfaces vector and get status of interface
```

**Describe alternatives you've considered**
I haven't  :)

**Additional context**
In the above patch, I chose to replace `getnameinfo` with `inet_ntop`, but I've zero experience with either, so I don't know what unknown side-effects, if any, this might have?! The `ip` buffer is now 979 bytes smaller because of that. Maybe there's a good reason why `getnameinfo` was chosen instead, I've no idea.

You may close this if you'd like, I'm happily using the above patch locally. This feature request is just my attempt to give back.

**EDIT:** the patch above is bugged in the sense that it won't see any subsequent IP changes on interfaces, because I was using `.empty()` like that. I'll make a [PR](https://github.com/aristocratos/btop/pull/458) with the right changes. EDIT3: actually, even without the patch, deleting the IPv4 of the interface will keep showing you the old IPv4 instead of the IPv6(or MAC), but PR #457 fixes this.
**EDIT2:** my call to `inet_ntop` is bugged for IPv6 as I'm not considering the difference in `struct`s! **EDIT3:** Aside from the already bugged call `inet_ntop(AF_PACKET,...` which I already had noted as a possibility, but didn't expect it so soon :)) )

**Comment by aristocratos** [comment]
@correabuscar 
> Maybe there's a good reason why getnameinfo was chosen instead, I've no idea.

It's likely `getnameinfo` is used just because it was the most referenced function when I was looking up how to resolve the IP's, can't really remember.

> The last IP (169.254.0.100) is being displayed by btop in the NET box for the em1 interface, but I want the first one (192.168.0.2) instead.

I believe that is what most people would want, the fact that the code is overwriting `net[iface].ipv4` and `net[iface].ipv6` would indicate that I didn't consider interfaces having more than one ipv4 or ipv6 address.

Please feel free to create a pull request OR preferably 2 pull requests, with the change to `inet_ntop` in a separate PR so that if it would cause any issues, it can be easily reverted without reverting the behavior of which IP to pick.
