### ISSUE TITLE
[BUG] Nice level underflow

### ISSUE THREAD

**Issue by uAliFurkanY** [aristocratos/btop#461]
**Describe the bug**

nice level number underflows

**To Reproduce**

start a process with `nice -n -4` and see the nice level from btop

**Expected behavior**

nice should display -4

**Screenshots**

![Screenshot_20221106_122024](https://user-images.githubusercontent.com/57134217/200163159-42855f63-ded2-4d37-a025-baedc8096b0e.png)

**Info (please complete the following information):**
 - btop++ version: `1.2.12`
 - Binary: Arch official repos
 - Architecture:  `x86_64`
 - Platform: Linux
 - (Linux) Kernel: `6.0.7-zen1-1-zen`
 - Terminal used: Alacritty
 - Font used: Hack Regular 10

**Additional context**

contents of `~/.config/btop/btop.log`

```
2022/11/06 (12:22:24) | ===> btop++ v.1.2.12
2022/11/06 (12:22:24) | DEBUG: Starting in DEBUG mode!
2022/11/06 (12:22:24) | INFO: Logger set to DEBUG
2022/11/06 (12:22:24) | DEBUG: Setting LC_ALL=en_US.UTF-8
2022/11/06 (12:22:24) | INFO: Running on /dev/pts/2
2022/11/06 (12:22:28) | INFO: Quitting! Runtime: 00:00:04
```

**Comment by correabuscar** [comment]
Seems to work with this change:
```patch
diff --git a/src/btop_shared.hpp b/src/btop_shared.hpp
index 919bc31..f9275a4 100644
--- a/src/btop_shared.hpp
+++ b/src/btop_shared.hpp
@@ -262,7 +262,7 @@ namespace Proc {
         double cpu_p{};         // defaults to = 0.0
         double cpu_c{};         // defaults to = 0.0
 		char state = '0';
-        uint64_t p_nice{};      // defaults to 0
+        int64_t p_nice{};      // defaults to 0
         uint64_t ppid{};        // defaults to 0
         uint64_t cpu_s{};       // defaults to 0
         uint64_t cpu_t{};       // defaults to 0
```

Though I'm unsure if that's the right type to use (tested Linux only).

**Comment by aristocratos** [comment]
@uAliFurkanY @correabuscar 
Good catch, fixed in latest commits.
