### ISSUE TITLE
[BUG] btop shows absolute zero CPU temp

### ISSUE THREAD

**Issue by joske** [aristocratos/btop#467]
On an amazon EC2 instance (not sure, but a VM for sure), a colleague of mine saw the CPU temp as -273 C:

**To Reproduce**

not known if it is like this on all VMs

**Expected behavior**

a reasonable CPU temp

![image](https://user-images.githubusercontent.com/532423/201608512-99977a0e-6a6f-46ff-91ce-ab30f4874299.png)

**Info (please complete the following information):**
 - btop++ version: `btop -v` 1.2.13
 - Binary: snap install btop
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m` x86_64
 - Platform: Linux
 - (Linux) Kernel: `uname -r` 5.15.0-1022-aws
 - (OSX/FreeBSD) Os release version: ubuntu 20.04.5
 - Terminal used: not known - probably not relevant
 - Font used: not known - not relevant

**Comment by joske** [comment]
Ok, in the guest OS, there's nothing in `/sys/class/hwmon`. Also no coretemp in `/sys/devices/platform` so I guess there's nothing more to do than not show the temp if it's 0.

**Comment by aristocratos** [comment]
@joske 
It also looks in `/sys/class/thermal`.
Regardless, don't think I've ever seen the sensors data being passed down from the VM host to the guest. So unless there is specific functionality built in to do this, I wouldn't trust any sensors data inside a VM.

He could always just set `show_temp` config option to `false`, I mean, that's why it's there.

Although acknowledging that sub-zero cooling is extremly rare;  ignoring the temp below zero would be throwing away valid data if the temp is below 0.

**Comment by aristocratos** [comment]
But who knows, maybe amazon has built quantum servers and managed to cool the system to 273.4 that gets rounded down to 273 :)

**Comment by joske** [comment]
I'll ask him again tomorrow, I also received an EC2 instance, also installed btop via snap, and in that machine, btop just doesn't show the temperature.

**Comment by aristocratos** [comment]
> and in that machine, btop just doesn't show the temperature.

That would be the expected in a VM, not sure why he as sensors picking anything up at all.

**Comment by FlamenWolf** [comment]
I'm on PopOS with no VM and I have the same bug. I have a tool named Vitals I got off of gnome extensions and it detects my cpu temperature with no problem.

**Comment by azzydoesgit** [comment]
> I'm on PopOS with no VM and I have the same bug. I have a tool named Vitals I got off of gnome extensions and it detects my cpu temperature with no problem.

What hardware are you using? I'm on PopOS as well and have never had any issues.

**Comment by D0LLYNH0** [comment]
I have the same behavior on all my Amazon EC2 instances ranging between Ubuntu, Fedora and CentOS; I only use the [release binaries](https://github.com/aristocratos/btop/releases/latest/download/btop-x86_64-linux-musl.tbz).
I have other VMs on DigitalOcean and Contabo, but none exhibit this behavior, the temperature just isn't displayed, which is expected.

![Snap 796 • 02 01 2023 17h 32m 24s](https://user-images.githubusercontent.com/67797325/210278853-a8aa9827-d02e-4887-9353-2c9a13da1ffc.png)

**Comment by vitaly-zdanevich** [comment]
It showing 1 degree for me, my first thought was that wow my big watercooling works so great.

Previously on the same machine I had some normal temperature, in BIOS I see real ~38 degrees.
