### ISSUE TITLE
[BUG] Reported memory usage in LXC exceeds actual available memory

### ISSUE THREAD

**Issue by jdrusso** [aristocratos/btop#473]
**Describe the bug**

The reported memory usage is 163PiB, although actual available memory is only 100GiB.

**To Reproduce**

Launch `btop` within an LXC container

**Expected behavior**

Used memory should not exceed total memory

**Screenshots**

![image](https://user-images.githubusercontent.com/1316917/204897363-c58f472f-bef9-4082-b793-6727a4211d53.png)

**Info (please complete the following information):**
 - btop++ version: `1.2.12`
 - Binary: `self compiled`
 - (If compiled) Compiler and version: `gcc 12.2.0`
 - Architecture: [x86_64, aarch64, etc.] `x86_64`
 - Platform: `Debian` LXC under Proxmox
 - (Linux) Kernel: `5.15.30-2-pve`
 - (OSX/FreeBSD) Os release version: `Debian 11 bullseye`
 - Terminal used: `screen`
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

```
2022/11/30 (20:00:47) | ===> btop++ v.1.2.12
2022/11/30 (20:00:47) | WARNING: No good candidate for cpu sensor found, using random from all found sensors.
```

**Comment by aristocratos** [comment]
@jdrusso 
Well, apparently your kernel thinks you have more memory available than your total memory.
Not sure how that makes sense...
So `Total - Available` underflows `Total` and wraps around.

Added a change so if Available memory is greater than Total memory (!), the calculation uses Free memory instead.
Build from latest commit or download binary from https://github.com/aristocratos/btop/actions/runs/3587321636

**Comment by jdrusso** [comment]
Thanks for this, and for the quick turnaround!

It works -- but, of course, now (after consistently running into this for weeks) I'm unable to reproduce the original bug.

Sounds like the fix should solve it though -- I'll update if/when I'm able to reproduce the original problem and check the patched version against it.

**Comment by jdrusso** [comment]
Reproduced, and confirmed this fixes it! Thanks again!
