### ISSUE TITLE
[BUG] Possibly mssing target dependencies in Makefile

### ISSUE THREAD

**Issue by NexAdn** [aristocratos/btop#479]
**Describe the bug**

In [Gentoo Bug 884005](https://bugs.gentoo.org/884005) we noticed builds failing due to files not being created with e.g. this output from the Tinderbox:

> Assembler messages:
> Fatal error: can't create obj/btop_menu.o: No such file or directory
> Assembler messages:
> Fatal error: can't create obj/btop_draw.o: No such file or directory

As described by a user on the [gentoo-user mailing list](https://marc.info/?l=gentoo-user&m=166980746719287), the problem might be that the `mkdir` commands for the output directories didn't finish before some jobs attempted to open files in said directories, leading to write failures.

**To Reproduce**

The aforementioned user got this problem by building on a machine with many jobs in parallel (here it was `-j17`).

**Expected behavior**

The compiler should be able to open the files for writing.

**Screenshots**

Screenshots not applicable, but you might be interested in some of this output:

* [Tinderbox build log](https://884005.bugs.gentoo.org/attachment.cgi?id=838935)
* [First comment on Bug 884005](https://bugs.gentoo.org/884005#c0) (contains a condensed output with less noise)
* [Environment variables set during build](https://884005.bugs.gentoo.org/attachment.cgi?id=838931)
* [emerge --info](https://884005.bugs.gentoo.org/attachment.cgi?id=838927) (contains a bunch of system and package manager information from the build)

**Info (please complete the following information):**
 - btop++ version: `btop -v` – Not applicable, since the build failed. As can be deduced from the build log, a build of 1.2.13 was attempted.
 - Binary: self compiled
 - (If compiled) Compiler and version: From the build log: `CXX        ?| x86_64-pc-linux-gnu-g++ (12.2.1)`
 - Architecture: [x86_64, aarch64, etc.] `uname -m`: amd64
 - Platform: Gentoo Linux
 - (Linux) Kernel: `uname -r`: Linux-6.0.10-x86_64-AMD_Ryzen_9_5950X_16-Core_Processor-with-glibc2.36
 - (OSX/FreeBSD) Os release version: Not applicable
 - Terminal used: Not applicable
 - Font used: Not applicable

**Additional context**

contents of `~/.config/btop/btop.log` – Not applicable

**GDB Backtrace**

Not applicable.

**Comment by NexAdn** [comment]
As we already discussed in the [Gentoo bug](https://bugs.gentoo.org/884005#c8), the issue is probably that the build targets don't depend on the `directories` target, thus allowing make to execute both targets in parallel, which breaks the build on the rare occasion that mkdir takes longer than g++ takes to make the `open()` call.

**Comment by NexAdn** [comment]
Of course depending on the directories target is not possible for this build system as the dependencies are used as input to the g++ command lines, thus forbidding a dependency on phony targets.

An alternative solution might be calling `make -p` in the build jobs.
This is an idempotent way of creating the output directories and should be multi-job safe.
Or one could rewrite the all target to call `$(MAKE)` instead of using the dependcy mechanism:

```make
all:
    $(MAKE) directories
    $(MAKE) btop
```

**Comment by Flowdalic** [comment]
I think this is a prime use case for an order-only prerequisite.

**Comment by NexAdn** [comment]
Didn't even know that existed, but [StackOverflow](https://stackoverflow.com/questions/58039810/makefiles-what-is-an-order-only-prerequisite) helped :sweat_smile: 

I'll open a PR.
