### ISSUE TITLE
[REQUEST] Ubuntu Instructions

### ISSUE THREAD

**Issue by hl2guide** [aristocratos/btop#486]
**Is your feature request related to a problem? Please describe.**
Please add instructions for installing within Ubuntu.

**Describe the solution you'd like**
Instructions for installing within Ubuntu.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by afiorillo** [comment]
Hi!

Installing for Ubuntu is already covered by the installation instructions in the README [here](https://github.com/aristocratos/btop#installation). (I just installed it on a new laptop a few days ago :smile: ). In particular, I ran:

```bash
# step 1, download it
# your CPU architecture may be different!
$ wget https://github.com/aristocratos/btop/releases/download/v1.2.13/btop-x86_64-linux-musl.tbz

# step 1b, unzip it
$ tar -xvf btop-x86_64-linux-musl.tbz

# step 2, install it
$ cd btop && ./install.sh
```

I didn't set the suit bit, but that would be exactly as documented.
