### ISSUE TITLE
[BUG] Proc per core over 999% usage

### ISSUE THREAD

**Issue by ghz-max** [aristocratos/btop#50]
**Describe the bug**

When a process uses over 999% with proc per core = true (more than 10 cores), btop prints the usage on 3 digits and truncate last numbers.

**To Reproduce**

1) Have a CPU with over 10 cores
2) install sysbench
3) sysbench cpu --threads=`nproc` run
4) watch btop which doesn't scale the cpu usage over 3 digits

**Expected behavior**

btop prints cpu usage on more than 3 digits (e.g. 1400%)

**Screenshots**

![image](https://user-images.githubusercontent.com/48886505/134977608-dc4aa736-6e61-4ade-b8d7-fb89955c5c99.png)

**Info (please complete the following information):**
 - btop++ version: 1.0.9
 - Binary: static binary from release
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] x86_64
 - Platform: Linux (WSL2)
 - (Linux) Kernel: 5.4.72-microsoft-standard-WSL2
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Windows terminal + tmux
 - Font used: MeslolGS NF

**Comment by aristocratos** [comment]
@ghz-max 
Should be fixed in latest commit, if you need static binary it will be up in release v1.0.10 later today.

**Comment by ghartz** [comment]
I tested the v1.0.10 and it looks good to me.

Thanks for your help!
