### ISSUE TITLE
Extra character being displayed under filesystems ( disks )

### ISSUE THREAD

**Issue by kenny-ngo** [aristocratos/btop#51]
Please take a look at my screenshot.
![bug](https://user-images.githubusercontent.com/15976483/135008066-ec2cf136-0fdc-4af1-b309-26c01e88b74d.png)

I am using the latest x64 binary for linux

**Comment by aristocratos** [comment]
@kenny-ngo 
That's short for "Used", on small terminal sizes the text is cut off to show more of the percentage meter.
