### ISSUE TITLE
[REQUEST] Add night-owl theme

### ISSUE THREAD

**Issue by zkourouma** [aristocratos/btop#53]
**Describe the solution you'd like**
include a `night-owl.theme` file in the  default options

**Describe alternatives you've considered**
i've already implemented it for myself and wanted to share it

**Additional context**
this theme is inspired by the original [VS Code version](https://github.com/sdras/night-owl-vscode-theme) by sdras

**Comment by aristocratos** [comment]
@zkourouma 
Hi, making a pull request for a theme is totally fine, just haven't had time to look at it yet (your previous PR i mean).

Although it would be appreciated if you include some screenshots, that way others can also chime in a bit easier.

**Comment by zkourouma** [comment]
![image](https://user-images.githubusercontent.com/3931509/135132415-1e9f2f76-96f4-4ad6-b263-a75bc5a224cb.png)

screenshot for context

**Comment by aristocratos** [comment]
@zkourouma 
Looks good to me :)
Unless you have any more changes you wanna do I will merge your PR in next release.

Thanks for contributing!

**Comment by zkourouma** [comment]
no changes here, thanks for taking a look!
