### ISSUE TITLE
[REQUEST] ability to set update_ms as CLI flag

### ISSUE THREAD

**Issue by code-n-go** [aristocratos/btop#551]
As the title states, adding an ability to set the update_ms upon startup using a command-line flag.  I have it launch automatically in a devcontainer, and have to manually adjust that every time.  I think there would be value under other circumstances to be able to set this upon launch also.

**Comment by nobounce** [comment]
Can you try [this branch](https://github.com/nobounce/btop/tree/redraw-frequency)?

**Comment by code-n-go** [comment]
@nobounce ... I thought I commented on this; however, realized I did not when I checked up the status of this.  This worked great.  Any update on when we may be able to get this merged and implemented?  Highly appreciate you taking the time to do this!
