### ISSUE TITLE
[REQUEST] Remove compiler version selection in the Makefile

### ISSUE THREAD

**Issue by imwints** [aristocratos/btop#566]
I don't think it's necessary to set the compiler to a `g++-<version>` anymore when running make.
I'm encountering an issue where I have my `/usr/bin/g++` pointing to GCC 13 (which is not yet covered by the Makefile) and I've installed GCC 10 alongside for testing. This configuration selects GCC 10 over 13.

I think we should trust that the distribution has set g++ to the latest and most stable version of the compiler that should be used on that system. If the user wants to, they can pass a specific compiler as an environment variable. If we clearly state this in the installation instructions it should be sufficient.
The worst thing that can happen is, as it does now, that the compilation fails. There is also a version check so if the compiler version is too old this gets printed out.

And I don't think we should take care of those rare situations where, e.g. GCC 9 and GCC 11 are installed and
```
/usr/bin/g++ -> /usr/bin/g++-9
```
This is a setup where it's up to the user or developer to call `make CXX=g++-11`, not the Makefile. It's just too much to account for.

Of course we could with no issue just add a few more checks for every new compiler but this is really just putting more work on maintaining that Makefile. The solution above is a lot simpler.

**Comment by correabuscar** [comment]
I've hit this on Gentoo, as follows:
```
...
Linking and optimizing binary...
x86_64-pc-linux-gnu-g++ -o bin/btop obj/btop.o obj/btop_config.o obj/btop_draw.o obj/btop_input.o obj/btop_menu.o obj/btop_shared.o obj/btop_theme.o obj/btop_tools.o obj/linux/btop_collect.o -Wl,-O1,--sort-common,--as-needed,-z,relro -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -D_FILE_OFFSET_BITS=64 -fexceptions -fstack-clash-protection -fcf-protection -fstack-protector   -Wall -Wextra -pedantic
100% -> bin/btop                      (27MiB) (00s)

Build complete in (01s)
>>> Source compiled.

>>> Test phase [not enabled]: sys-process/btop-1.2.13-r2

>>> Install sys-process/btop-1.2.13-r2 into /var/tmp/portage/sys-process/btop-1.2.13-r2/image
make --no-keep-going --output-sync=target -j18 PREFIX=/usr DESTDIR=/var/tmp/portage/sys-process/btop-1.2.13-r2/image install
ccache: error: Could not find compiler "g++-12" in PATH
Makefile:78: *** ERROR: Compiler too old. (Requires Clang 16.0.0, GCC 10.1.0).  Stop.
 * ERROR: sys-process/btop-1.2.13-r2::gentoo failed (install phase):
 *   emake failed
```

I have only `/usr/bin/g++-13` and `/usr/bin/g++` however:
```
# /usr/lib/ccache/bin/g++-12
ccache: error: Could not find compiler "g++-12" in PATH
```
After manually upgrading ccache from 4.8-r2 to 4.8.3 on Gentoo the g++-12 symlink that ccache had, was removed.

so previously:
```
lrwxrwxrwx 1 root root   15 May 25 22:56 g++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 May 25 22:56 g++-12 -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 May 25 22:56 g++-13 -> /usr/bin/ccache
```
and now:
```
lrwxrwxrwx 1 root root   15 Oct  8 08:36 g++ -> /usr/bin/ccache
lrwxrwxrwx 1 root root   15 Oct  8 08:36 g++-13 -> /usr/bin/ccache
```

I didn't update g++ recently, so I don't know why ccache would have a symlink to 12 too...
Now btop emerged successfully on Gentoo.

**Comment by nobounce** [comment]
@correabuscar 
that seems about right. the source code for 1.2.13 does not "support" gcc 13 (under the condition that a binary from gcc 12 or earlier is found), so this is expected. i linked the relating pull request which should land in the next version!
