### ISSUE TITLE
[REQUEST] How to save options.

### ISSUE THREAD

**Issue by LittleNewton** [aristocratos/btop#574]
**Is your feature request related to a problem? Please describe.**
When I reboot my OS and restart btop, the settings will vanished. I have to open the option menu and re-config it.

- Theme
- Vim move style

**Describe the solution you'd like**
Add an entry for saving profiles.

**Comment by LittleNewton** [comment]
I am sorry. There is a configuration file can be customized.

**Comment by nobounce** [comment]
The config file should be synced on exit. I sometimes observe something similar if I configure an option and then close my terminal without quitting btop. Try to gracefully exit btop after changing a setting and see if it works.

**Comment by dm17** [comment]
I don't want it to only be saved on exit. I accidentally press a key and I don't want to debug it right then - I just want to restore my previously saved preferences. Is there some way to easily save & restore?

**Comment by imwints** [comment]
Copy the config file to a backup location? There is no option in the program itself

**Comment by dm17** [comment]
Oh, now I get it. If I mess up the config by accident, then I restore it by closing the terminal instead of pressing `q` to quit btop. Then it won't save and therefore I can easily restore it.

**Comment by imwints** [comment]
Exactly, the changes in config are kept in memory until the program exits.

https://github.com/aristocratos/btop/blob/e4f69cd72868d60c40f2861a46c085ee6014f004/src/btop.cpp#L291-L337

This is the `SIGTERM` handler.

https://github.com/aristocratos/btop/blob/e4f69cd72868d60c40f2861a46c085ee6014f004/src/btop.cpp#L316

is automatically run here, but not during program execution.
