### ISSUE TITLE
[REQUEST] Please add Nvidia GPU monitoring. 

### ISSUE THREAD

**Issue by joshigarvitgh** [aristocratos/btop#575]
**Is your feature request related to a problem? Please describe.**
I am working on a server with multiple GPUs and if I can see GPU stats and a list of tasks on GPU this will greatly improve my efficiency.

**Comment by nobounce** [comment]
#426 #529

**Comment by joshigarvitgh** [comment]
#529 There is an issue in btop.cpp. please replace println with print. println stops the make process.
