### ISSUE TITLE
[REQUEST] Install Issue and Fix - Debian 12.0 Bookworm

### ISSUE THREAD

**Issue by mattpogue** [aristocratos/btop#577]
Hello,

I wanted to drop a quick note regarding btop installation on Debian 12 and possibly other *nix OSes. Btop has been a part of my standard server build for quite a while and I consider it a foundational app on all my Linux systems. I run Debian (recently upgraded to 12.0 "bookworm") and I wanted to mention an issue I ran into recently while building on a new server. 

Since Debian doesn't have the [fmt library](https://github.com/fmtlib/fmt) by default, I began receiving the following during the "make" step:

```makefile
In file included from src/btop_config.cpp:27:
src/btop_tools.hpp:42:10: fatal error: fmt/core.h: No such file or directory
   42 | #include <fmt/core.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:302: obj/btop_config.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/btop_draw.cpp:28:
src/btop_tools.hpp:42:10: fatal error: fmt/core.h: No such file or directory
   42 | #include <fmt/core.h>
     |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:302: obj/btop_draw.o] Error 1
In file included from src/btop.cpp:47:
src/btop_tools.hpp:42:10: fatal error: fmt/core.h: No such file or directory
   42 | #include <fmt/core.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:302: obj/btop.o] Error 1
In file included from src/btop_input.cpp:26:
src/btop_tools.hpp:42:10: fatal error: fmt/core.h: No such file or directory
   42 | #include <fmt/core.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:302: obj/btop_input.o] Error 1
```

After a bit of searching, the fix is relatively simple:

1. Clone the fmt repo: 
    a. `git clone https://github.com/fmtlib/fmt.git`
2. Install `cmake`: 
    a. `apt install cmake`
3. Following [instructions](https://fmt.dev/latest/usage.html#building) from the `fmt` site, build and install the `fmt` library: 
    a. `cd fmt` 
    b. `mkdir build` 
    c. `cd build` 
    d. `cmake ..`
    e. `make install`

After completing the `fmt` library install, the btop `make && make install` works flawlessly.

Hopefully can save someone a few minutes of digging!

Again, thank you for the awesome, awesome app!

**Comment by tchereau** [comment]
or just do `git clone --recursive https://github.com/aristocratos/btop.git` to get fmtlib automaticaly ;)
```bash
git clone --recursive https://github.com/aristocratos/btop.git
Cloning into 'btop'...
remote: Enumerating objects: 4253, done.
remote: Counting objects: 100% (4253/4253), done.
remote: Compressing objects: 100% (1196/1196), done.
remote: Total 4253 (delta 2825), reused 4140 (delta 2776), pack-reused 0
Receiving objects: 100% (4253/4253), 8.30 MiB | 131.00 KiB/s, done.
Resolving deltas: 100% (2825/2825), done.
Submodule 'lib/fmt' (https://github.com/fmtlib/fmt) registered for path 'lib/fmt'
Cloning into '/home/thomas/btop/lib/fmt'...
remote: Enumerating objects: 32536, done.
remote: Counting objects: 100% (3303/3303), done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 32536 (delta 3114), reused 3171 (delta 3068), pack-reused 29233
Receiving objects: 100% (32536/32536), 13.89 MiB | 149.00 KiB/s, done.
Resolving deltas: 100% (22073/22073), done.
Submodule path 'lib/fmt': checked out 'a54cb108d4634e768ad3ce0855313991ccc768de'
```

**Comment by mattpogue** [comment]
Thank you @tchereau! Jeez dude, I'm embarrassed. Leaving this here as a reminder to myself to RTFM. Obviously that's a much better solution :)

**Comment by mattpogue** [comment]
Remember kids, always read the instructions first!

**Comment by tchereau** [comment]
to be honest I didn't even read the manual, I just do it mechanically ^^

**Comment by mattpogue** [comment]
Man, I don't know how I didn't realize that I probably should have always been doing `--recursive`. And here I always thought I didn't learn anything new working weekends :-P
