### ISSUE TITLE
[REQUEST] Aggregate child process values in tree mode

### ISSUE THREAD

**Issue by magneticflux-** [aristocratos/btop#598]
**Is your feature request related to a problem? Please describe.**
I'd like to view the process tree, but also sort by total child CPU usage so that (_non-collapsed_) subtrees with a lot of resource usage appear higher.

**Describe the solution you'd like**
An option to report aggregate statistics about child processes regardless of the nodes being collapsed or not.

**Describe alternatives you've considered**
Introduce another toggle like `per-core` called `aggregate`?

**Additional context**
This seems mostly-implemented already since collapsed nodes already sum their values, I'd just like to see the sums while also seeing the child processes.

**Comment by nobounce** [comment]
I've implemented this in https://github.com/nobounce/btop/tree/aggregate-child-processes, but I find this hardly distinguishable from the normal per-process statistics. Any idea how this could be made visible that this a the combined resource usage so user won't freak out if they are not aware of this?

**Comment by magneticflux-** [comment]
Awesome that works perfectly! It makes a huge difference when there's deeply-nested trees and I want to show the most "active" ones first, like compiling a bunch of packages in NixOS.

<details>
<summary>Details</summary>

![image](https://github.com/aristocratos/btop/assets/9124288/4238d0af-afa7-4eca-8dfe-2978e27a6f28)

Overriding the `btop` package in Nix to use this branch:
```nix
(btop.overrideAttrs (prev: {
  name = "btop/aggregate-child-processes";
  src = pkgs.fetchFromGitHub {
    owner = "nobounce";
    repo = "btop";
    rev = "aggregate-child-processes";
    hash = "sha256-wWpcqnZXBH4nIE/EzWWooFyzM0odX2ewAHq1fIuX5M8=";
  };
}))
```

</details>


Before this, the `systemd/sshd/nixos-rebuild` tree wasn't guaranteed to be at the top because random background services with 2% CPU usage got sorted above `sshd` with 1%, even though the _tree_ was a lot more active.

---

To make it explicitly clear to users, you could split the display of values into "self" and "child" parts, so something like `/sbin/init` spawning a child with 5G memory would look like `1.6M + 5G`. The downside is that it's much wider than the original.

In my opinion, having the aggregate stats option default to off and making the description really clear is a good approach if you're concerned about confusion. I suggest the description be:
> In tree-view, include all child resources with the parent even while expanded.

**Comment by nobounce** [comment]
I just realized that if we show both memory values we would also want to show all of the other resources twice, but that would take up to much space (or I just can't imagine a nicer way of doing things)
