### ISSUE TITLE
Which character(s) are used for blank space in graphs

### ISSUE THREAD

**Issue by wnhrt** [aristocratos/btop#60]
Which character(s) are used for the blank space in the CPU, network and memory graphs?

At the moment I'm using the font [Cozette](https://github.com/slavfox/Cozette) and btop looks like this:
![btop](https://user-images.githubusercontent.com/70302993/135579484-336d7ca4-99f5-4d08-b7be-6f47a2907c32.png)

My guess is one of the “Geometric Shapes”, which are not all supported by Cozette.

Before opening an issue at https://github.com/slavfox/Cozette, I wanted to confirm this suspicion.

**Comment by aristocratos** [comment]
@wnhrt 
It's Four-Per-Em Space [(U+2005)](https://www.compart.com/en/unicode/U+2005) in the "General punctuation" block.
Will update the Prerequisites section in the readme.

It's used to be able to get an accurate size of one of the lines in the graph, the byte size of a "normal" space would be too small  and mess up the alignment if not parsing every line at every update (would be slow).

You could try patching in the missing symbol with the font patcher from https://github.com/ryanoasis/nerd-fonts

**Comment by aristocratos** [comment]
@wnhrt 
Realized it was actually not an issue to change to regular whitespace...
Fixed in [v1.0.13](https://github.com/aristocratos/btop/releases/tag/v1.0.13)
