### ISSUE TITLE
[BUG] UI shows too many cores

### ISSUE THREAD

**Issue by Xenfo** [aristocratos/btop#605]
**Describe the bug**

btop shows 20 cores, I only have 12.

**To Reproduce**

Open btop

**Expected behavior**

UI only shows 12 cores

**Screenshots**

![image](https://github.com/aristocratos/btop/assets/46873232/097abf68-3dae-49ae-855c-c0c43003d729)

**Info (please complete the following information):**
 - btop++ version: 1.2.13
 - Binary: Static
 - Architecture: x86_64
 - Platform: Linux
 - Kernel: 6.4.12-arch1-1
 - Terminal used: Kitty v0.29.2
 - Font used: Monolisa

**Additional context**

contents of `~/.config/btop/btop.log`
```
2023/08/27 (16:40:24) | ===> btop++ v.1.2.13
2023/08/27 (16:40:24) | DEBUG: Starting in DEBUG mode!
2023/08/27 (16:40:24) | INFO: Logger set to DEBUG
2023/08/27 (16:40:24) | DEBUG: Using locale en_US.UTF-8
2023/08/27 (16:40:24) | INFO: Running on /dev/pts/0
2023/08/27 (16:40:28) | INFO: Quitting! Runtime: 00:00:04
```

**Comment by aristocratos** [comment]
https://letmegooglethat.com/?q=12700f+cpu+specifications

**Comment by Xenfo** [comment]
Yes, 12 cores, 20 threads. I was under the impression that btop shows cores.

**Comment by aristocratos** [comment]
Why? I don't know of any resource monitor that doesn't show all logical cores.

**Comment by Xenfo** [comment]
I was messing around with `sensors-detect` and when I restarted btop the cpu section seemed like it was bigger than it was. I don't remember seeing 20 threads before. Maybe it was bugged before. Anyways, I'll close since this seems to be expected behavior.

**Comment by aristocratos** [comment]
@Xenfo Probably likely that you saw an increase in size if your temperature sensors started reporting values btop could pick up. The core temps is hidden if no sensors is found.
