### ISSUE TITLE
[BUG] btop (snap) segfaults on zfs directory

### ISSUE THREAD

**Issue by kz6fittycent** [aristocratos/btop#639]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

`btop` fails to run and segfaults immediately. Logs show it's unable to access zfs (i.e. permission denied). This is a new error with the snap. 

**To Reproduce**

[Steps to reproduce the behavior:]
Run `btop` from terminal

**Expected behavior**

`btop` has worked flawlessly for a long time now, this is a new error. 

**Screenshots**

![image](https://github.com/aristocratos/btop/assets/14829816/52bf395d-b8c3-4728-8a7c-ffee6dbebe5d)

**Info (please complete the following information):**
 - btop++ version: 1.2.13 (snap)
 - Binary: snap
 - (If compiled) Compiler and version: n/a
 - Architecture: x86_64
 
 - Platform: Linux
 - (Linux) Kernel:  5.15.0-83-generic
 - (OSX/FreeBSD) Os release version: Ubuntu Server 20.04.
 - Terminal used: terminator
 - Font used: utf-8

**Additional context**

contents of `~/.config/btop/btop.log`

```
2023/10/02 (17:05:15) | ===> btop++ v.1.2.13
2023/10/02 (17:05:15) | WARNING: Error in Mem::collect() : filesystem error: directory iterator cannot open directory: Permission denied [/proc/spl/kstat/zfs/data01]

2023/10/02 (17:05:47) | ===> btop++ v.1.2.13
2023/10/02 (17:05:47) | WARNING: Error in Mem::collect() : filesystem error: directory iterator cannot open directory: Permission denied [/proc/spl/kstat/zfs/data01]
```

**Comment by kz6fittycent** [comment]
Hmm, similar error with snap on `Pop!_OS` 22.04 - 

```
2023/02/17 (10:43:11) | ===> btop++ v.1.2.13
2023/02/17 (10:43:11) | WARNING: Failed to join _runner thread on exit!

2023/04/02 (14:44:57) | ===> btop++ v.1.2.13
2023/04/02 (14:44:57) | WARNING: Failed to join _runner thread on exit!

2023/04/11 (16:06:33) | ===> btop++ v.1.2.13
2023/04/11 (16:06:33) | WARNING: Failed to join _runner thread on exit!

2023/05/20 (22:38:55) | ===> btop++ v.1.2.13
2023/05/20 (22:38:55) | WARNING: Failed to join _runner thread on exit!

2023/07/11 (10:06:37) | ===> btop++ v.1.2.13
2023/07/11 (10:06:37) | WARNING: Failed to join _runner thread on exit!

2023/08/29 (13:11:07) | ===> btop++ v.1.2.13
2023/08/29 (13:11:07) | WARNING: Failed to join _runner thread on exit!

2023/09/15 (11:22:09) | ===> btop++ v.1.2.13
2023/09/15 (11:22:09) | WARNING: Failed to join _runner thread on exit!
```

**Comment by kz6fittycent** [comment]
OK, sort of interesting turn - it works on Intel procs but not on my AMD machines...

**Comment by kz6fittycent** [comment]
Please see my forum post regarding this issue: https://forum.snapcraft.io/t/btop-having-issues-with-segfault-on-hosts-running-zfs/38078

**Comment by kz6fittycent** [comment]
Anyone running into this issue, I have verified that it does not exist in the `stable` channel for the `btop` snap. Do not refresh to `edge`, or you'll see these issues.

**Comment by kz6fittycent** [comment]
@aristocratos , was there some update to `btop` that would be throwing these `apparmor` denials with `zfs`? There haven't been any changes to the `hardware-observe` interface from Canonical.

**Comment by aristocratos** [comment]
@kz6fittycent 
Don't think so.

Since the error occurs when reading from `/proc/spl/kstat/zfs`, it seems more likely the issue would be with snap (or apparmor).
Git blame shows that particular read has been there since May 5 2022.
So nothing recent.

**Comment by aristocratos** [comment]
@kz6fittycent 
Added some extra guards for the zfs code to make sure exceptions are caught.
Might fix the segfault, but will not fix the denied read...

**Comment by kz6fittycent** [comment]
@aristocratos - what's odd is that the version of `btop` in the `stable` channel for the snap (released 14 Sep 2023) is working on all my systems, but all the builds thereafter are failing. I keep getting these odd `segfaults` and the logs above.
