### ISSUE TITLE
Add Intel GPUs?

### ISSUE THREAD

**Issue by dm17** [aristocratos/btop#644]
Is there a way to display the output from `intel_gpu_top` in btop already? If not, that is kind of what I'm looking for... And perhaps other users can use the same method to poll radeontop and similar.
Thanks; btop is great!

**Comment by 42Willow** [comment]
https://github.com/aristocratos/btop/pull/529#issuecomment-1632328432

Support for GPU's was added in this PR, but unfortunately for now there isn't any intel GPU support (99%, unless it just isn't working for me)

**Comment by notorand-it** [comment]
As of 1.3.2, no Intel GPU (mine is Iris Xe Graphics) usage is shown.

**Comment by Sarajevo1914** [comment]
thinkpad T14 Gen 2 i5 1135g7 is not shown (btop 1.3.2)

**Comment by dontknowhy** [comment]
Good news:There is some other way to show Team Blue's GPU usage:
![Screenshot_20240524_184554](https://github.com/aristocratos/btop/assets/85813508/5f0bc2d1-248f-4ad9-992c-4b2f400b2a3d)

Bad news:I think it uses DRM to get the GPU's usage.
[Mission Center](https://gitlab.com/mission-center-devs/mission-center)

As [this pull message](https://github.com/aristocratos/btop/pull/529#issuecomment-1632328432) said,it's hard to use the same way as [igt-gpu-tools](https://gitlab.freedesktop.org/drm/igt-gpu-tools).

**Comment by Antiarchitect** [comment]
btop 1.3.2 IrisXe HP Pro Book - not shown

**Comment by dm17** [comment]
In terms of AMD and Intel GPUs, I've found `nvtop` to be significantly nicer than `radeontop` and `intel_gpu_top`. Would be cool to have them all working in `btop` though!

**Comment by notorand-it** [comment]
The point here, IMHO, is not to the the best ever GPU usage tracking, but rather to add (for now) an idea on how much the GPU(s) are loaded. Nicer, fancier, more accurate can come later.

**Comment by aristocratos** [comment]
Added in commit 24fc97c

**Comment by dontknowhy** [comment]
> Added in commit 24fc97c

@aristocratos 
It works for me.
But why I need to give it my root permission to see my GPU usage?
Is there any way to use it without root?

**Comment by aristocratos** [comment]
@dontknowhy 
Because the user you are launching btop with doesn't have permission to read SYSFS.

You can either check documentation for your distribution how to fix that.
Or try with `sudo setcap cap_perfmon=+ep /usr/local/bin/btop` (replace the path with your path to btop).

This will be explained in the documentation when I create a new release, and will add a option to the Makefile `make setcap` that will do that for you.

**Comment by dontknowhy** [comment]
> @dontknowhy 
> Because the user you are launching btop with doesn't have permission to read SYSFS.
> 
> You can either check documentation for your distribution how to fix that.
> Or try with `sudo setcap cap_perfmon=+ep /usr/local/bin/btop` (replace the path with your path to btop).
> 
> This will be explained in the documentation when I create a new release, and will add a option to the Makefile `make setcap` that will do that for you.

Now it works.
:)

**Comment by FranMUex** [comment]
Mine only shows gpu usage, but not it's frequency or power usage, even when running as root
![dom 22 sep 2024 12:14:20 CEST](https://github.com/user-attachments/assets/899154ab-1240-4f67-a86f-e4654b25213a)

**Comment by dontknowhy** [comment]
> Mine only shows gpu usage, but not it's frequency or power usage, even when running as root
> ![dom 22 sep 2024 12:14:20 CEST](https://github.com/user-attachments/assets/899154ab-1240-4f67-a86f-e4654b25213a)
> 

Try to restart it.
Because mine didn't show up in her first time.

**Comment by aristocratos** [comment]
Only utilization, watt and clockspeed is supported for Intel, same as `intel_gpu_top`.

Open up the GPU box to see clocks, '5' key if you only got 1 gpu.

**Comment by FranMUex** [comment]
Oh, thanks, I thought it was supposed to show in the CPU box.

**Comment by aristocratos** [comment]
Added in release [v1.4.0](https://github.com/aristocratos/btop/releases/tag/v1.4.0)

**Comment by notorand-it** [comment]
Super! It works on ArchLinux!
![SHOT-20240922-224127+0200](https://github.com/user-attachments/assets/18f4da70-921b-44f4-b3b4-f8b321e7c622)

**Comment by matthenning** [comment]
Can confirm. GPU usage including power draw works on Arch. Thank you!

**Comment by notorand-it** [comment]
![SHOT-20240923-183201+0200](https://github.com/user-attachments/assets/784534c3-e2d5-426b-b443-017da633d2d5)

Also GPU "ad hoc" panel works nice!

**Comment by 7system7** [comment]
I upgraded, but sadly it does not work here. :cry: 

![Pasted image (2)](https://github.com/user-attachments/assets/38c7a60a-49bb-4226-95d6-ab1749746a75)

**Comment by notorand-it** [comment]
Have you "fixed"other permissions with sudo?

(Read above)

**Comment by 7system7** [comment]
Nope. But after the permissions added, it just works. Thank you and sorry to not read the thread completely. :partying_face:

**Comment by dontknowhy** [comment]
```
btop version: 1.4.0+2e7208d
Compiled with: c++ (14.2.0)
Configured with: cmake -DBTOP_STATIC=OFF -DBTOP_USE_MOLD=OFF -DBTOP_FORTIFY=ON -DBTOP_GPU=ON
```
```
 ❯ sudo getcap btop                
btop cap_perfmon=eip
```
![Screenshot_20240930_213930](https://github.com/user-attachments/assets/94ac9cd0-5638-4ad1-9e5e-de301cdb6380)
I'm sorry. But it looks like somebody did some nasty things...

**Comment by jclsn** [comment]
Just tried installing the static binary on my Debian server. It doesn't work on Alderlake it seems. Works on Arch with on Cometlake laptop.

**Comment by 1nv3n7or** [comment]
Gonna save some time for future generations

As it seams, apt has old version of btop 1.2

You need to install it from sourse or use homebrew

In mine case brew has same 1.4 version as in repo at the time

### Using homebrew
Install homebrew
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Install btop
```bash
brew install btop
```

Find path to btop
```bash
which btop

# /home/linuxbrew/.linuxbrew/bin/btop
```

Find actual path
```bash
readlink -f /home/linuxbrew/.linuxbrew/bin/btop
# /home/linuxbrew/.linuxbrew/Cellar/btop/1.4.0/bin/btop
```

Use actual path to fix permissions
```bash
sudo setcap cap_perfmon=+ep /home/linuxbrew/.linuxbrew/Cellar/btop/1.4.0/bin/btop
```

Now should be fine:
![image](https://github.com/user-attachments/assets/6263cd97-8999-4244-87bf-80cb0cb79e90)

**Comment by xxLeoxx93** [comment]
Should this also work with older Intel GPUs? I'm running a 9400t and intel_gpu_top works, but 1.4.5 with 
`sudo setcap cap_perfmon=+ep /usr/local/bin/btop `
it still doesn't show GPU power and load.

**Comment by jclsn** [comment]
@xxLeoxx93 It does, but only if the Intel GPU is the primary GPU. I have an integrated Intel GPU and a discrete one. It shows only the integrated GPU. You can unbind the driver from both cards and then rebind the discrete one first. Then it becomes `/dev/dri/card0` and will be displayed by btop as well.

**Comment by xxLeoxx93** [comment]
@jclsn
It's my only GPU (no discrete mounted) but I don't have any monitor connected. Does that have an effect?

<img width="1668" height="324" alt="Image" src="https://github.com/user-attachments/assets/ec4ebf38-cbb3-4126-92f1-4d3e8f632a57" />

**Comment by jclsn** [comment]
> [@jclsn](https://github.com/jclsn) It's my only GPU (no discrete mounted) but I don't have any monitor connected. Does that have an effect?

It should not. You only need `intel-gpu-tools` and the right permissions. Should work with sudo or the setcap options.

**Comment by xxLeoxx93** [comment]
My only guess is now that the UHD 630 isn't supported :(

**Comment by jclsn** [comment]
Or your btop binary was compiled without GPU support. The standalone binaries in the release page are built without it afaik.

https://github.com/aristocratos/btop?tab=readme-ov-file#compilation-linux

**Comment by deckstose** [comment]
The conversation has derailed a bit from the original topic, but if you have any further question or need help, please open a new discussion for that.

**Comment by 7karni** [comment]
> Gonna save some time for future generations
> Use actual path to fix permissions
> sudo setcap cap_perfmon=+ep /home/linuxbrew/.linuxbrew/Cellar/btop/1.4.0/bin/btop

and if on NixOS, use a [security wrapper](https://search.nixos.org/options?show=security.wrappers&query=security.wrappers):
```
security.wrappers.btop = {
    source = "${pkgs.btop}/bin/btop";
    capabilities = "cap_perfmon+ep";
    owner = "root";
    group = "root";
  };
```
