### ISSUE TITLE
[BUG] CPU name is cut off

### ISSUE THREAD

**Issue by somera** [aristocratos/btop#65]
**Describe the bug**

[A clear and concise description of what the bug is.]

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**

![image](https://user-images.githubusercontent.com/8334250/135749497-fafc1290-9b2c-486c-b3c6-f5b5c3ee2a40.png)

Just missing the 5 at the end: Pentium Silver J5005

**Info (please complete the following information):**
 - btop++ version: `btop -v` 1.0.13
 - Binary: [self compiled or static binary from release] self compiled

**Comment by aristocratos** [comment]
@somera 
Not a bug.
Were you excepting it to adapt to any arbitrary size?

**Comment by somera** [comment]
> @somera Not a bug. Were you excepting the box to adapt to any arbitrary sized cpu name?

Correct. And yes.

bpytop is showing shorter name for the same CPU

![image](https://user-images.githubusercontent.com/8334250/135750715-db3dbffe-ce05-4c59-b2a5-fda1f916ca6e.png)

**Comment by aristocratos** [comment]
@somera 
> Correct. And yes.

How so? I can't think of any software where the window size is determined by the size of the title.

> bpytop is showing shorter name for the same CPU

You can make an feature request about changes to the CPU name detection (or rather filtering in this case).

You can also manually set the CPU name in the options menu if what it has detected is bothering you.

**Comment by somera** [comment]
Thx. I did't see the option for the CPU name.
