### ISSUE TITLE
[BUG] Reading configuration file from read-only filesystem fails.

### ISSUE THREAD

**Issue by RobertZenz** [aristocratos/btop#650]
**Describe the bug**

When starting btop on a read-only filesystem (with a `btop.conf` present at the right location), btop complains that it can't find `$HOME` nor `$XDG_CONFIG_HOME`, the configuration file is not read and btop reverts to its defaults.

Remounting the filesystem as read-write allows btop to start with the correct configuration.

I guess this is related to #637.

**To Reproduce**

Have a read-only filesystem on which the configuration resides.

**Expected behavior**

btop should at least start with the configuration that is present, and then complain that it can't write changes to it.

**Comment by nobounce** [comment]
Yeah, the current config check fails if neither `$HOME` or `$XDG_CONFIG_HOME` are writable.

I have created a [branch](https://github.com/nobounce/btop/tree/config-read-only) that should allow read only configuration files. I'd like you to test it before creating a PR.
It works on a read only `tmpfs`

**Comment by RobertZenz** [comment]
Yes, that does work as expected, thank you.

However, there is now *no* message at all that the configuration could not be saved, which isn't ideal either.

**Comment by nobounce** [comment]
I've updated the branch, it now also warns if the config dir resides on a read only filesystem

**Comment by RobertZenz** [comment]
Neat! Thank you very much.
