### ISSUE TITLE
[BUG] Btop shows 1/10th of cpu usage, compared to htop or top

### ISSUE THREAD

**Issue by MuffinInACup** [aristocratos/btop#665]
**Describe the bug**

When looking at the per-process cpu consumption, the displayed value is 1/10th of the actual value/values reported by top and htop

**To Reproduce**

1) Open btop and top or htop
2) Observe values of the same process

**Expected behavior**

Btop should show the same values as other process monitors

**Screenshots**

![image](https://github.com/aristocratos/btop/assets/47538902/966a4ff6-980c-4285-a2e3-1b1a3699a98c)

From left to right: btop, htop and top; For example, look at the values for picom process (highlighted in brown in btop, blue in htop and at the top of the list in top). Htop and top report values around 20%, while btop reports around 2.0%

(Edit: changed the screenshot, the first one was incredibly lucky for htop to show 0.0% at the exact frame of screenshotting)

**Info (please complete the following information):**
 - btop++ version: 1.2.13
 - Binary: Official Repositories (extra) for arch (garuda)
 - Architecture: x86_64
 - Platform: Gardua Linux, based on arch
 - (Linux) Kernel: 6.6.1-zen1-1-zen
 - (OSX/FreeBSD) Os release version: Garuda 2.6.19-2
 - Terminal used: xfce4-terminal
 - Font used: Source Code Pro Regular

**Additional context**

contents of `~/.config/btop/btop.log` - irrelevant but just in case:
```
2023/07/01 (16:07:04) | ===> btop++ v.1.2.13
2023/07/01 (16:07:04) | ERROR: Stall in Runner thread, restarting!

2023/08/07 (14:45:34) | ===> btop++ v.1.2.13
2023/08/07 (14:45:34) | ERROR: No tty detected!
btop++ needs an interactive shell to run.

2023/08/24 (18:31:25) | ===> btop++ v.1.2.13
2023/08/24 (18:31:25) | ERROR: Stall in Runner thread, restarting!
```

**Comment by mgradowski** [comment]
By default, btop divides the CPU usage by the number of cores, whereas htop doesn't. You can switch this behaviour by using this option:
![image](https://github.com/aristocratos/btop/assets/24899416/9ac56160-45c4-4efa-8b13-947d20bca008)

Running `stress --cpu 1` with the default value:
![image](https://github.com/aristocratos/btop/assets/24899416/80dd2e85-4b2b-4503-84d2-c2ae041a41c2)

And with `Proc per core` set to `True`:
![image](https://github.com/aristocratos/btop/assets/24899416/6da920ef-f0af-4ea0-8c8b-cb511bbbb7a3)

**Comment by antimirov** [comment]
I wish this was the default setting. This got me so confused and I could not find where to change it, because of course I searched in the 1general and 2cpu settings tabs.

**Comment by MuffinInACup** [comment]
> Why "of course"? 
Not sure about antimirov, but I suppose looking for it in the cpu tab feels more intuitive for me, than in the proc tab. (we are measuring cpu usage after all) but I can see how your way of categorising makes no less sense

>  don't necessarily think it should be the default just because other monitors default to it 
I have mixed feelings about this, I feel like being more 'standard' would be good user experience. The represented value may be less technically correct, but it is more intuitive to sight-read to a user.

And yeah, closing this as its indeed not a bug
