### ISSUE TITLE
raid disk not showing up[BUG]

### ISSUE THREAD

**Issue by mihstaz** [aristocratos/btop#668]
**Describe the bug**
Cannot get raid disk /dev/md0 to show up in disks menu

**To Reproduce**
Install btop on OpenSUSE Leap 15.5, create mdadm raid and run btop

**Expected behavior**
/dev/md0 should show up in btop's disks table

**Screenshots**
![Screenshot from 2023-11-22 21-53-12](https://github.com/aristocratos/btop/assets/106404379/536adf14-ab9b-493b-aafa-89b1d3c80173)

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: `btop -v` 1.2.5
 - Binary: [self compiled or static binary from release] installed from opensuse repo
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m` x86-64
 - Platform: [Linux, FreeBSD, OsX] Linux
 - (Linux) Kernel: `uname -r` 5.14.21-150500.55.31-default
 - (OSX/FreeBSD) Os release version:
 - Terminal used: default ubuntu terminal (I ssh into the system that is monitored with btop)
 - Font used: default

**Additional context**

contents of `~/.config/btop/btop.log`

(nothing but the following repeating with different dates and times:)
2023/11/22 (21:45:25) | ===> btop++ v.1.2.5
2023/11/22 (21:45:25) | WARNING: Failed to join _runner thread on exit!

I've tried messing with the settings under options -> mem and experimented with disks filters ("/dev/md0" or "include=/dev/md0" or "include=/sys/block/md0") but that only removed all disks from the table and only showed my swap.

Also, thank you for making this project in the first place, I really enjoy monitoring my system with it

**Comment by imwints** [comment]
Please update to 1.2.13

**Comment by mihstaz** [comment]
> Please update to 1.2.13

Thank you for your answer.
I just installed version 1.2.13 from github, but I still have the exact same issue.
Just for clarification, what is the correct syntax for disk filters? is it the mount point (/mnt/raid1), the block (/sys/block/md0) or the raid device (/dev/md0)? Neither one works and entering either of them still causes the disks section to show nothing but the swap partition.

**Comment by mihstaz** [comment]
I'm an idiot, it's working now.
Had to change fstab to false and physical only to true, now all other drives show up.
Could've sworn that this was one of the settings combinations I tried before opening this ticket, but apparently not.
Works on version 1.2.5 as well.
