### ISSUE TITLE
[BUG] CPU box displays a "Q" as the name of the CPU

### ISSUE THREAD

**Issue by kekePower** [aristocratos/btop#676]
**Read the README.md and search for similar issues before posting a bug report!**

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

I have an older laptop and in the CPU cores/threads box, it only displays a Q as the CPU name.
The CPU in the laptop is ```Intel(R) Core(TM) i7 CPU       Q 840  @ 1.87GHz.```

```
$ cat /proc/cpuinfo
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 30
model name	: Intel(R) Core(TM) i7 CPU       Q 840  @ 1.87GHz
stepping	: 5
microcode	: 0xa
cpu MHz		: 1867.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid dtherm ida vnmi flush_l1d
vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 3723.85
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**To Reproduce**

Install and use btop on a laptop with the same CPU.

**Expected behavior**

Would be nice to see the full name of the CPU and not just a Q.

**Screenshots**

![Screenshot from 2023-12-05 00-53-04](https://github.com/aristocratos/btop/assets/8249456/66bb51d2-2631-40cb-b4af-cd5af4f12b2e)

**Info (please complete the following information):**
 - btop++ version: `btop -v`: 1.2.13
 - Binary: binary from release
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.]: x86_64
 - Platform: [Linux, FreeBSD, OsX]: Linux
 - (Linux) Kernel: `uname -r`: 6.5.11-desktop-5.mga9
 - (OSX/FreeBSD) Os release version: Mageia 9
 - Terminal used: kitty
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

2023/12/05 (00:55:56) | ===> btop++ v.1.2.13
2023/12/05 (00:55:56) | DEBUG: Starting in DEBUG mode!
2023/12/05 (00:55:56) | INFO: Logger set to DEBUG
2023/12/05 (00:55:56) | DEBUG: Using locale en_US.UTF-8
2023/12/05 (00:55:56) | INFO: Running on /dev/pts/1
2023/12/05 (00:56:00) | INFO: Quitting! Runtime: 00:00:04

**GDB Backtrace**

N/A

**Comment by deckstose** [comment]
This regressed somehow. Looking at the code, it seems to was moved and the patch reverted.

https://github.com/aristocratos/btop/commit/3fa79fe490040c5dc054d75a9465b939ed808539
