### ISSUE TITLE
[REQUEST] Reload config from disk using signal

### ISSUE THREAD

**Issue by Hubro** [aristocratos/btop#683]
**Is your feature request related to a problem? Please describe.**

I want to automate switching between light and dark mode on all my applications. btop is ****ing awesome, so I constantly have it open on all my PCs.

Currently I don't see any *good* way of automatically switching between light and dark themes in btop without doing it manually through the UI.

**Describe the solution you'd like**

It would be nice if I could send a signal (`SIGHUP` or `SIGUSR1`) to btop to make it reload the configuration from disk. That way I could write a `darkman` script that toggles the btop theme in the config file and runs `pkill -USR1 btop` and presto!

**Describe alternatives you've considered**

Wrapper script that restarts btop any time the config file changes. Not ideal, since all state is lost.

**Additional context**

I'm hopelessly addicted to home automation and the lack of this feature is causing me considerable anguish.

**Comment by sahinakkaya** [comment]
Came here for the exact same reason (darkman). It would be really cool to change theme on the fly.

**Comment by MartinPit** [comment]
Just opened a pull request resolving your exact problem.

**Comment by imwints** [comment]
> Describe alternatives you've considered
>
> Wrapper script that restarts btop any time the config file changes. Not ideal, since all state is lost.

Why lost? I don't see why you couldn't save the state. Btop writes it's config before exiting. When you intercept `SIGUSR` with the script you could move the new config out of the way, let btop write its state and then copy the new file back and start btop with the new state. You could even just `sed` only a single config line, like the theme, and any other config change would persist. Or am I missing something?

**Comment by Hubro** [comment]
By state I mean the graphs and such, not the config
