### ISSUE TITLE
Name collision with LSF command btop

### ISSUE THREAD

**Issue by DarwinAwardWinner** [aristocratos/btop#70]
It turns out that LSF, the cluster job submission system, has a command called btop: 

https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=reference-btop

I don't know if this is a large enough issue to consider a name change, but I wanted to at least make you aware of it if you weren't already.

**Comment by aristocratos** [comment]
@DarwinAwardWinner 
I don't know how relevant this really is considering LSF is proprietary software.
It's not like it's gonna collide in a distribution package manager.

And considering the use case for LSF, people who use both LSF and btop++ are probably gonna have a pretty good grasp on how to handle naming collisions.
