### ISSUE TITLE
[BUG] Memory widget shows strange values

### ISSUE THREAD

**Issue by ivan-volnov** [aristocratos/btop#728]
Memory widget shows strange values.

btop shows:

![image](https://github.com/aristocratos/btop/assets/51086293/e431e178-967d-4a6a-91e9-81a1b7db1621)

bpytop shows:

![image](https://github.com/aristocratos/btop/assets/51086293/70be627a-dcae-4a00-a590-31762af681e8)

htop shows:

![image](https://github.com/aristocratos/btop/assets/51086293/34bf1fe0-9c5c-4cc9-b2b3-61d11a913333)

**Expected behavior**

Who knows?

**Info (please complete the following information):**
 - btop++ version: btop version: 1.3.0
 - Binary: pkg install btop
 - (FreeBSD) Os release version: FreeBSD 14.0-RELEASE-p3
 - FS: zfs

**Comment by aristocratos** [comment]
> search for similar issues before posting a bug report
#291
