### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by rabin-io** [aristocratos/btop#73]
I package the application for my self via OBS, you can find the RPM for Fedroa 33/34 [here](https://software.opensuse.org//download.html?project=home%3Arabin-io&package=btop) if you like to add the link to the README file.

**Comment by gourlaysama** [comment]
In case it's useful to someone:

I maintain a Fedora COPR (the equivalent of Arch's AUR) of btop [here](https://copr.fedorainfracloud.org/coprs/gourlaysama/btop/) for Fedora, CentOS Stream and RHEL (on x86_64, aarch64, armhfp, ppc64le and s390x when supported).
