### ISSUE TITLE
[BUG] GPU compilation should enable the linker flag -ldl by default

### ISSUE THREAD

**Issue by rahulaggarwal965** [aristocratos/btop#730]
**Describe the bug**

On Ubuntu 20.04 (g++-10), when compiling from the v1.3.0 tag (I also tested on main) with GPU_SUPPORT enabled  (NVIDIA), the default makefile does not include the linker flag -ldl and therefore does not compile. Adding -ldl solves this problem.

**To Reproduce**

```
git clone https://github.com/aristocratos/btop.git
cd btop
git checkout v1.3.0 (optional)
CXX=g++-10 make
```

I expect the compilation to resolve successfully. Below I have attached a screenshot and a log of the error message.
![image](https://github.com/aristocratos/btop/assets/18104107/f742c053-34e8-427d-81ec-139eb553a942)

<details>

<summary>Text Log</summary>

```
/usr/bin/ld: /tmp/btop.c8wIWg.ltrans16.ltrans.o: in function `Shared::init()':
<artificial>:(.text+0x6608): undefined reference to `dlopen'
/usr/bin/ld: <artificial>:(.text+0x6629): undefined reference to `dlopen'
/usr/bin/ld: <artificial>:(.text+0x663e): undefined reference to `dlerror'
/usr/bin/ld: /tmp/btop.c8wIWg.ltrans22.ltrans.o: in function `Gpu::Nvml::init()::{lambda(char const*)#1}::operator()(char const*) const [clone .constprop.0]':
<artificial>:(.text+0x1b6f): undefined reference to `dlsym'
/usr/bin/ld: <artificial>:(.text+0x1b77): undefined reference to `dlerror'
/usr/bin/ld: /tmp/btop.c8wIWg.ltrans22.ltrans.o: in function `Gpu::Rsmi::init()::{lambda(char const*)#1}::operator()(char const*) const [clone .constprop.0]':
<artificial>:(.text+0x1c6f): undefined reference to `dlsym'
/usr/bin/ld: <artificial>:(.text+0x1c77): undefined reference to `dlerror'
/usr/bin/ld: /tmp/btop.c8wIWg.ltrans25.ltrans.o: in function `Gpu::Rsmi::init() [clone .isra.0]':
<artificial>:(.text+0x8497): undefined reference to `dlopen'
/usr/bin/ld: <artificial>:(.text+0x84b1): undefined reference to `dlerror'
/usr/bin/ld: /tmp/btop.c8wIWg.ltrans25.ltrans.o: in function `Gpu::Nvml::shutdown() [clone .isra.0]':
<artificial>:(.text+0x1c19): undefined reference to `dlclose'
/usr/bin/ld: /tmp/btop.c8wIWg.ltrans25.ltrans.o: in function `Gpu::Rsmi::shutdown() [clone .isra.0]':
<artificial>:(.text+0x1ce7): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make: *** [Makefile:350: btop] Error 1
```

</details>

However, when I compile using the following command:
```
LDFLAGS=-ldl make
```

btop compiles successfully.
![image](https://github.com/aristocratos/btop/assets/18104107/a13c5446-d7d1-49cd-80e9-95480726cbf1)

This seems to be an easy fix, but I would defer to you on whether this fix is only needed on certain platforms/distributions/kernel versions. 

**Info (please complete the following information):**
 - btop++ version: v1.3.0
 - (If compiled) Compiler and version: g++ 10.5.0
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.15.0-91-generic
 - Terminal used: st
 - Font used: roboto-mono

**Comment by imwints** [comment]
> **Read the README.md and search for similar issues before posting a bug report!**

#704 #725

**Comment by rahulaggarwal965** [comment]
> Since the Makefile doesn't do it I wouldn't like to do this to support (compiling against) some ancient glibc.
Being written with C++-20 btop is dependent on recent compilers anyway so it wouldn't make much sense to support (compiling against) older libc's while requiring new compilers.

Sounds good. Since it looks like you want to have this behavior explicitly, I will close this for now.
