### ISSUE TITLE
[BUG] btop from arch repos not reading AMD GPU dispite having rocm-smi-lib installed.

### ISSUE THREAD

**Issue by Doomguy1364** [aristocratos/btop#759]
btop installed from the arch repository is not reading my 7900xtx gpu; Attached is a copy of the log, as well as a screenshot showing proof the packages are installed and up to date.

![image](https://github.com/aristocratos/btop/assets/107533517/35780a6a-fbec-44af-9c11-d09955e0936a)

[btop.log](https://github.com/aristocratos/btop/files/14235355/btop.log)

 - btop++ version: 1.3.1
 - Architecture: x86_64
 - Platform: Linux
 - Kernel: 6.7.4-arch1-1
 - Terminal used: Konsole
 - Font used: JetBrainsMono Nerd Font 10

**Comment by alerque** [comment]
This is follow up to #705 (and I'm the Arch Linux packager).

As of 1.3.1 the builds I did no longer need GPU disabled to not crash, and at compile time they show that GPU support is enabled, but I am unable to make it actually *do* anything. It doesn't find my GPU either even with rocm-smi-lib installed.

**Comment by imwints** [comment]
Please try the linked PR. For some obscure reason the 6.0.x releases from rocm have the internal version 7.0.0.0.

**Comment by alerque** [comment]
I can confirm that patch works for me.
