### ISSUE TITLE
[BUG] Battery Power displays current battery capacity instead of power

### ISSUE THREAD

**Issue by Derppening** [aristocratos/btop#770]
**Describe the bug**

When enabling the battery power display introduced in v1.3.1, the current battery capacity in Wh is displayed instead of the current energy consumption.

**To Reproduce**

1. Open btop and an external tool which monitors battery consumption (I use the Energy information display in KDE).
2. Monitor the Wattage displayed in btop and the current battery capacity in Wh.

**Expected behavior**

The current power consumption is displayed instead of the current battery capacity.

**Screenshots**

The below screenshot shows that the power consumption never exceeds 20W, but the current power consumption displayed by btop is at 34W. Moreover, the numeric value of the power consumption in btop and the remaining energy in KDE's info center is the same (34.32).

![image](https://github.com/aristocratos/btop/assets/4293438/48e814c6-5dff-4117-869c-836f2834ce16)

**Info (please complete the following information):**
 - btop++ version: 1.3.2
 - Binary: static binary from release + Compiled Package from ArchLinux
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 6.7.4-arch1-1
 - Terminal used: konsole/yakuake
 - Font used: Fira Code

**Additional context**

Contents of `~/.config/btop/btop.log`

```
2024/02/14 (00:41:22) | ===> btop++ v.1.3.2
2024/02/14 (00:41:22) | WARNING: ROCm SMI: Failed to get maximum GPU power draw, defaulting to 225W
2024/02/14 (00:41:22) | WARNING: ROCm SMI: Failed to get maximum GPU temperature, defaulting to 110°C
2024/02/14 (00:41:22) | WARNING: ROCm SMI: Failed to get VRAM utilization
2024/02/14 (00:41:22) | WARNING: ROCm SMI: Failed to get GPU power usage
2024/02/14 (00:41:22) | WARNING: ROCm SMI: Failed to get PCIe throughput
```

**Comment by rubin55** [comment]
I'm experiencing exactly this issue with `btop` 1.3.2 on Arch Linux, on an AMD Ryzen 7 PRO 5850U; is that a regression? Screenshot:
![image](https://github.com/aristocratos/btop/assets/6214491/8d31e5a3-0e01-4dd4-a5d7-2964b1f7a490)
