### ISSUE TITLE
[REQUEST] Config for Defaul Kill Signal

### ISSUE THREAD

**Issue by KAGEYAM4** [aristocratos/btop#790]
**Is your feature request related to a problem? Please describe.**
Currently the default signal for killing is `SIGKILL`. I wanted to change it to SIGTERM in order to kill promgrams gracefully.

**Describe the solution you'd like**
A configuration options where we can select default Signal for killing.

**Comment by aristocratos** [comment]
@KAGEYAM4 
So... why not just use the terminate key instead?

![image](https://github.com/aristocratos/btop/assets/59659483/f066685f-566e-4088-a904-367d21318806)

**Comment by KAGEYAM4** [comment]
wow, totally blind, looked at configuration, menus, README  and missed this in plain sight.
