### ISSUE TITLE
[REQUEST] Use theme in banner and options

### ISSUE THREAD

**Issue by cpuccino** [aristocratos/btop#8]
**Describe the solution you'd like**
Any chance there's already a built in way to change the banner colors to the theme selected?
Or maybe just print it out as text instead of ASCII art. The banner doesn't match the theme that i'm using at all right now (nord), cheers

**Comment by mrkeuz** [comment]
Maybe naive additional. It would be good to add `keybinding` for `toggle theme`. For ability change theme on the fly, w/o menu. It will be useful for estimate themes without cover by main menu block and also w/o fade colors.
