### ISSUE TITLE
[REQUEST] Add gruvbox_light theme

### ISSUE THREAD

**Issue by kk9uk** [aristocratos/btop#804]
We only have gruvbox_dark right now but me personally love gruvbox_light and have implemented that, would you like me adding it?

![image](https://github.com/aristocratos/btop/assets/122882463/e449ba40-b3ce-4676-a467-8c3a89bd6ee8)

**Comment by kk9uk** [comment]
In case you want to take a look: https://github.com/kk9uk/btop/blob/main/themes/gruvbox_light.theme

**Comment by imwints** [comment]
Just open a new PR :)

**Comment by kk9uk** [comment]
@imwints See #807 , thanks
