### ISSUE TITLE
No UTF-8 locale detected!

### ISSUE THREAD

**Issue by skirthy** [aristocratos/btop#81]
Running `btop` in the terminal outputs the following:

`ERROR: No UTF-8 locale detected!`
`Use --utf-force argument to force start if you're sure your terminal can handle it.`

Running `btop --utf-force` starts btop without an issue. But how to get rid of the UTF-8 error?

I've already tried these:

`sudo locale-gen "en_IN.UTF-8"`

`sudo dpkg-reconfigure locales`

I've ensured that the terminal character encoding is set to "UTF-8". 

**Info:**
 - btop++ version: 1.0.14
 - Binary: self compiled
 - (If compiled) Compiler and version: gcc 11.1.0
 - Architecture: x86_64
 - Platform: Linux (Ubuntu 18.04.6 LTS)
 - (Linux) Kernel: 5.4.0-87-generic
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Gnome Terminal 3.28.2
 - Font used: Monospace Regular 12

**Comment by phocks** [comment]
Still happening for me on Ubuntu 22.04

**Comment by sagar-hbits** [comment]
Thanks @bilalmirza74  this worked!

**Comment by noel-jose-rajan** [comment]
adding the 
`export LANG=en_US.UTF-8`

to my 
`~/.bashrc` file, solved the issue

**Comment by renhiyama** [comment]
None of these comments try to solve the main issue, all of these are workarounds. Why can't we make btop accept `$LANG` values without `.UTF8` suffix?

**Comment by deckstose** [comment]
???

Because we don't want to start `btop` in non UTF-8 environments. If you think of this as a workaround you might also think of your setup as broken.
