### ISSUE TITLE
[BUG] Invalid RAM usage on MacBook Pro M3 Pro

### ISSUE THREAD

**Issue by corentinjuvigny** [aristocratos/btop#834]
**Describe the bug**

Quantity of RAM used is vastly underestimated  by btop on MacOs compared with what the activity monitor actually reports.

**To Reproduce**

Launch a program using a huge quantity of RAM (surpassing the physical quantity of RAM of the computer, forcing it to use swap memory). In my case I notice the bug while launching cplex, that can reach 50G of memory consumption for 18G of physical RAM. 

**Expected behavior**

Both btop and the macos activity monitor should indicate the same amount of RAM used.

**Screenshots**
<img width="1495" alt="Screenshot 2024-04-30 at 15 13 27" src="https://github.com/aristocratos/btop/assets/49539269/efcc5fdc-8a0c-42a7-bdb9-ad6582b0aec9">

**Info**
 - btop++ version: 1.3.2
 - Binary: static binary from release
 - Architecture: arm64
 - Platform: OsX 
 - (OSX/FreeBSD) Os release version: 14.4.1
 - Terminal used: default mac terminal

**Comment by nicolasbauw** [comment]
<img width="1257" alt="image" src="https://github.com/aristocratos/btop/assets/37193744/36dd49ea-d6f2-4eb2-a868-c400ad4b5b67">
Same observation here on MacOS.

**Comment by k2662** [comment]
Me too on MacOS Ventura x86_64.
OS Version: Ventura 13.6.6 22G630
Kernel Version: 22.6.0

**Comment by aristocratos** [comment]
@corentinjuvigny @nicolasbauw @k2662 

See #291

**Comment by marianokamp** [comment]
When using btop on Mac OS and run a program that is very large I get first a yellow then red indication in the activity monitor. Going into the red slows down the system and will make programs force close. These colors are based on how small the gap between "Physical Memory" and "Memory Used" is. The color is actionable to me and I start closing apps or wait for something to finish before I launch something else.

With btop, even when the Mac OS activity monitor is red, all looks good, like 50% available and I don't see any threshold that I need to keep an eye on.

How do other Mac OS users interpret what btop shows?
