### ISSUE TITLE
[REQUEST] Show multiple GPUs

### ISSUE THREAD

**Issue by adrianlyjak** [aristocratos/btop#865]
This was discussed fairly thoroughly in #426, the issue to add GPU support, but that's been fixed, so figured I'd open a new issue to keep this particular feature visible.

I have multiple GPUs, and expect that a lot of people using btop are futzing around on servers doing ML and want to monitor GPU usage. btop currently supports GPUs (yay!), however it just shows 1

<img width="487" alt="image" src="https://github.com/aristocratos/btop/assets/2024018/00785d80-861c-4436-8ff9-d384f6690f9a">

My personal preference would be to use the CPU style of UI, but modified a little to support GPUs
- treat each GPU like the CPU UI treats a core. It would show current GPU usage, current Memory usage, and current power usage.
- the historical graph would show average total GPU utilization over time like CPU does

While this leaves some historical information out, this approach seems like it should be simple and fit within the current btop design.
 
There were some other alternatives discussed in #426, such as binding digits 5-0 to display different gpus. This seems perhaps like it might make the feature more complicated to implement well. I personally don't have strong opinion though, and just want to see my other GPU

**Comment by actionless** [comment]
i can see 2 GPUs on the left side of the app (with the graph), but on the right side it shows only GPU0 and a blank line following it


here's a comparison, of 1gpu vs 2gpu setup:

![2024-07-05--1720139716_3809x774_scrot](https://github.com/aristocratos/btop/assets/1655669/905b9fd9-86bb-4e54-97d1-f44f8af7aff2)

not sure if that's a separate issue or the same as on topic

**Comment by PorkyC** [comment]
> i can see 2 GPUs on the left side of the app (with the graph), but on the right side it shows only GPU0 and a blank line following it
> 
> here's a comparison, of 1gpu vs 2gpu setup:
> 
> ![2024-07-05--1720139716_3809x774_scrot](https://private-user-images.githubusercontent.com/1655669/345969590-b4db85b5-5475-4981-931f-8a223d6d1e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTk1NjksIm5iZiI6MTcyMTcxOTI2OSwicGF0aCI6Ii8xNjU1NjY5LzM0NTk2OTU5MC1iNGRiODViNS01NDc1LTQ5ODEtOTMxZi04YTIyM2Q2ZDFlNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDcyMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTY2ZTU1OTJmZGUyY2U1MmQ1NDUwYjJhMWMxMDU0ODI0ZjZhMjkyZWMwMGYxZmIyMjZlZjRjOWZhOGUxYzk1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hE76cVTmNvD2ymKVjyilvHeZgs_zgnKz79eo50PswuY)
> 
> not sure if that's a separate issue or the same as on topic

Try pressing 5, 6 to toggle GPU settings.

**Comment by actionless** [comment]
if i press 5 it shows separately info for gpu 0 and if 6 - for gpu 1

but then this detailed info is hidden - in the overview it shows only gpu 0 and a blank line

**Comment by reukiodo** [comment]
I came here with the same issue! Thanks for the 5/6 tip - I didn't know that, but that uses a LOT more vertical space as there are 4 GPUs on this server:

```
024-09-11 13:34:02 root@ads-vs18:~# nvidia-smi 
Wed Sep 11 13:34:07 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          Off |   00000000:01:00.0 Off |                    0 |
| N/A   75C    P0            258W /  300W |   62881MiB /  81920MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off |   00000000:41:00.0 Off |                    0 |
| N/A   31C    P0             43W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          Off |   00000000:81:00.0 Off |                    0 |
| N/A   33C    P0             42W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          Off |   00000000:C1:00.0 Off |                    0 |
| N/A   68C    P0             83W /  300W |   10759MiB /  81920MiB |      8%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     61951      C   python                                      62872MiB |
|    3   N/A  N/A    116494      C   python                                      10750MiB |
+-----------------------------------------------------------------------------------------+
2024-09-11 13:34:08 root@ads-vs18:~# 
```

If I try to view all 4 (press 5, 6, 7, 8) then the dashboard starts to look a lot more cluttered than just showing all 4 under the CPU core list.
![image](https://github.com/user-attachments/assets/ba051716-3d47-4ee6-8ffb-572cec0d6d70)

**Comment by reukiodo** [comment]
I think this enhancement would be quite welcome to show all GPU quickstats under the CPU core list, as there is still space under the first GPU in what would appear should be a list:
![image](https://github.com/user-attachments/assets/0602b33a-de5e-4e5f-96b6-f5af5e13b8e4)

**Comment by aristocratos** [comment]
Yeah, it's supposed to be showing, the empty room has been left there for the additional GPU's.

The current "draw" code for GPU is a bit bugged, including this particular issue.
Haven't had time to go through it yet.

**Comment by aristocratos** [comment]
Fixed in latest commits.

**Comment by actionless** [comment]
thanks a lot!

just tested that it works:
![2024-09-25--1727239535_837x282_scrot](https://github.com/user-attachments/assets/63121f02-ea4f-4765-936f-66f1605c0978)
