### ISSUE TITLE
[BUG] The disk graph in io mode disappeared between 1.2.13 and 1.3.0

### ISSUE THREAD

**Issue by feihtthief** [aristocratos/btop#867]
**Read the README.md and search for similar issues before posting a bug report!**

I have read the README.md and looked for similar issues.

**Describe the bug**

The disk graph in io mode disappeared between 1.2.13 and 1.3.0

To reproduce:
- Run a 1.2.x version of btop in io mode and disk graphs are visible
- Run a 1.3.x version of btop in io mode and disk graphs are NOT visible

**Expected behavior**

Disk graphs should be visible in io mode

**Screenshots**

v1.2.13
![image](https://github.com/aristocratos/btop/assets/855235/6ae2791f-47e2-4b71-b076-b393b9e04249)
v1.3.0
![image](https://github.com/aristocratos/btop/assets/855235/eed6f6eb-9509-427f-a18b-d4c2b42599f8)

**Info (please complete the following information):**
 - btop++ version: v.12.13 and v1.3.0
   - If using snap: `snap info btop`
 - Binary: self compiled
 - Architecture: x86_64
 - Platform: Linux - Ubuntu 22.04 (Also applies to Ubuntu 23.10)
 - (Linux) Kernel: 6.5.0-35-generic
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Default Ubuntu Terminal App
 - Font used: No clue

**Additional context**

Git bisect process:
- started at v1.2.13 (`git bisect start`; `git bisect good`)
- checkout v1.3.0 (`git bisect bad`)
- run `make clean && make && ./bin/btop`
- if graph is visible do `git bisect good` if graph is not visible to `git bisect bad`
- repeat from run line

Git bisect log
```git bisect start
# good: [0f8498fa4e68e3af36a50b1d9f97b931b41b0824] v1.2.13 Bug fixes
git bisect good 0f8498fa4e68e3af36a50b1d9f97b931b41b0824
# bad: [36842a3bccfb78f5c27642435bff387b42f7d13b] v1.3.0 GPU Support Linux and platform support OpenBSD
git bisect bad 36842a3bccfb78f5c27642435bff387b42f7d13b
# good: [19bcff894bd8f018bc3c76607b1dd91200537923] Squashed commit of the following:
git bisect good 19bcff894bd8f018bc3c76607b1dd91200537923
# good: [450b59b657618beb7a88f34072210e27cab43ca5] Merge branch 'main' into main
git bisect good 450b59b657618beb7a88f34072210e27cab43ca5
# bad: [2796af3f37f07ba838d2eeb06e3d798f5ab00e55] Document DEBUG flag for Makefile
git bisect bad 2796af3f37f07ba838d2eeb06e3d798f5ab00e55
# good: [2d3e453ed527f2d045b9e615422f708820438298] Merge branch 'main' into main
git bisect good 2d3e453ed527f2d045b9e615422f708820438298
# good: [e15e0b71881641ea6d6751e3acd46631d91b494b] Revert "Replace robin_hood map and set with STD alternative and add safeVal() function for map/vector access with fallback"
git bisect good e15e0b71881641ea6d6751e3acd46631d91b494b
# good: [8b81c4a4ecfd7a3e56960befc2b3726f9dddd92d] Return const refs
git bisect good 8b81c4a4ecfd7a3e56960befc2b3726f9dddd92d
# bad: [b4eb397fc69696db18c6f2b90b79172882c39128] Fix errors
git bisect bad b4eb397fc69696db18c6f2b90b79172882c39128
# bad: [3c04a7a380a5a27630193e8805ef5f9d249cecb3] Added more checks and debug logging
git bisect bad 3c04a7a380a5a27630193e8805ef5f9d249cecb3
# first bad commit: [3c04a7a380a5a27630193e8805ef5f9d249cecb3] Added more checks and debug logging
```

I don't know any C++ but the commit [3c04a7a380a5a27630193e8805ef5f9d249cecb3](https://github.com/aristocratos/btop/commit/3c04a7a380a5a27630193e8805ef5f9d249cecb3) was not very complicated.

I suspect it's this change:
![image](https://github.com/aristocratos/btop/assets/855235/32032cad-4edc-4146-bbd3-3aa1a2218fd9)

```if (not io_graphs.contains(mount)) continue;```

Removing that line or replacing `io_graphs` with `disk_meters_used` in that line seems to make it work again, but I don't feel comfortable enough to just submit a PR for this as there might be something more involved needed here.

Thanks for making btop the amazing tool it is.

**Comment by feihtthief** [comment]
I did some more digging and I suspect that
```if (not io_graphs.contains(mount)) continue;```
Should be inside the ```if (io_graph_combined) {``` block and in the else block the following would be needed:
```if (not io_graphs.contains(mount + "_read") or not io_graphs.contains(mount + "_write")) continue;```

**Comment by imwints** [comment]
Not sure if you want this, but can you press `i`?

**Comment by aristocratos** [comment]
@feihtthief 
You're absolutely correct, should be fixed in latest commit.
