### ISSUE TITLE
[BUG] c++20 or c++2a

### ISSUE THREAD

**Issue by brccabral** [aristocratos/btop#89]
Hi all,
Not an actual bug, but a suggestion to improve the compilation process.
I installed the dependencies
```
sudo apt install coreutils sed git build-essential gcc-10 g++-10
```
Cloned the repo 
```
git clone https://github.com/aristocratos/btop.git
cd btop
```
and executed `make` and I am getting this error
```
g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?
```

But that is because my system had g++9 as default.
After I changed to g++10 it compiled without errors.

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
```
Please, add the `update-alternatives` into the instructions.

Thanks,
Bruno

**Comment by brccabral** [comment]
Ok, that works

**Comment by jorvis** [comment]
+1 
I just had this issue today with a current checkout of main.
