### ISSUE TITLE
[BUG] 100% load AMD integrated GPU

### ISSUE THREAD

**Issue by ostrovlyan** [aristocratos/btop#914]
**Describe the bug**

Integrated AMD GPU always show 100% utilization.

**To Reproduce**

Launch btop in any terminal.

**Expected behavior**

GPU utilization shows correct information.

**Screenshots**

![изображение](https://github.com/user-attachments/assets/95b38f45-2e68-43d5-8222-41641262764f)

**Info:**
 - btop++ version: 1.3.2
 - Binary: static from arch repo
 - Architecture: x86_64
 - Platform: Linux
 - Kernel: Linux archlinux 6.10.4-arch2-1
 - Terminal used: any

**Comment by Umio-Yasuno** [comment]
Some Raven/Picasso/Raven2 APU always report gpu_busy_percent as 100.  
https://gitlab.freedesktop.org/drm/amd/-/issues/1932

**Comment by ostrovlyan** [comment]
Got it, thank you.
