### ISSUE TITLE
[REQUEST] Add compile feature flags to `--version`

### ISSUE THREAD

**Issue by Redhawk18** [aristocratos/btop#916]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when nix disables gpu support by support so it can be hard to know what compile flags were enabled at build time

**Describe the solution you'd like**
a version command like vim where it displays a ton of info about its build

**Comment by imwints** [comment]
https://github.com/aristocratos/btop/commit/771702019743e7ee10da71079ff91edd4106fb41
