### ISSUE TITLE
[BUG] Btop does not allow you to quit out if your screen is to small.

### ISSUE THREAD

**Issue by BrendanMesters** [aristocratos/btop#926]
**Describe the bug**

When the btop application is running it will give an error screen if the terminal window is to small.
Normally, when you press 'q' while in btop, it quits the application, however, when the warning about your terminal window being to small is present this functionality does not work.

**To Reproduce**

1. Start up btop
2. Resize your terminal window until the warning message appears (width ≤ 80 or height ≤ 24).
3. Try to quit btop by pressing the 'q' button.
4. (bug) the btop application is not terminated.

**Expected behavior**

The btop application should quit out after pressing the 'q' key (except for when in the menu, then it should take you out of the menu), putting you back in your shell from where you originally launched btop

**Info**

btop version: 1.2.3
btop was installed using `apt`
OS: Ubuntu 22.04
Kernel: x86_64 Linux 6.8.0-40-generic
Terminal emulator: Alacritty

**Additional context**

Default btop config file was used.
No log file was generated.

Note: <C-c> does work to quit out of btop, even when the screen size is too small.

**Comment by imwints** [comment]
I can't reproduce this. Since you're on 1.2.3, please try to compile it from git and try if the bug persists.

**Comment by BrendanMesters** [comment]
The issue does indeed seem to have been resolved somewhere between version 1.2.3 (the current version available via `apt`) and the current version on github.

Since the issue does not exist on the newest version I'll close the issue.
