### ISSUE TITLE
[BUG] Black square appearing with custom theme

### ISSUE THREAD

**Issue by realguse** [aristocratos/btop#940]
**Describe the bug**

I have btop set up with a theme other than the default, but after for example exiting the btop++ menu right after changing theme, a black rectangle appears. This can also sometimes appear just out of now where.

After a bit of using btop, it dissapeared.

**To Reproduce**

Just install btop and wezterm?

**Expected behavior**

The black rectangle should not appear

**Screenshots**

https://github.com/user-attachments/assets/97ee1753-a52f-42d6-8fd1-a3ddca886c96

**Info:**
 - btop++ version: `btop version: 1.4.0
Compiled with: clang++ (16.0.0)
Configured with: /Applications/Xcode.app/Contents/Developer/usr/bin/make STATIC= FORTIFY_SOURCE=true`
 - Binary: installed with brew
 - Architecture: arm64
 - Platform: macOS 24.1.0
 - Terminal used: wezterm
 - Font used: jetbrains mono nerd font

**Comment by aristocratos** [comment]
Report the issue to the developers of `wezterm`.

**Comment by realguse** [comment]
> Report the issue to the developers of `wezterm`.

https://github.com/wez/wezterm/issues/6206

**Comment by tm-craggs** [comment]
exact same bug here.
