### ISSUE TITLE
[BUG] btop menu out-of-bounds access cause crash

### ISSUE THREAD

**Issue by danie-dejager** [aristocratos/btop#989]
**Describe the bug**
When opening the menu for btop 1.4.0 menu options, I am presented with a list from 1 to 5. When I press 6, btop crashes. I replicated this on 1.3.2 as well.

`std::vector::operator[]` does not perform bounds checking.
**To Reproduce**
open btop
press `m` to enter menu
select `options`
press 6 or a number bigger than the listed menu option count.
**Screenshots**
![image](https://github.com/user-attachments/assets/bc5c1215-5fe6-44b4-85b7-1f7eaf64a23c)

**Info (please complete the following information):**
 - btop++ version:
```
btop version: 1.4.0
Compiled with: g++ (11.2.1)
Configured with: make STATIC=true FORTIFY_SOURCE=true GPU_SUPPORT=false RSMI_STATIC=
```
 - Binary: static binary from release
 - Architecture: aarch64
 - Platform: Linux
 - (Linux) Kernel: 6.1.115-126.197.amzn2023.aarch64
 - Terminal used: terminator
 - Font used: nerdfont 

**Additional context**

Contents of `~/.config/btop/btop.log`
```
→ cat ~/.config/btop/btop.log

2024/12/04 (06:10:05) | ===> btop++ v.1.4.0
2024/12/04 (06:10:05) | WARNING: get_cpuHZ() : Failed to read /sys/devices/system/cpu/cpufreq/policy and /proc/cpuinfo.

2024/12/04 (06:11:31) | ===> btop++ v.1.4.0
2024/12/04 (06:11:31) | DEBUG: Running in DEBUG mode!
2024/12/04 (06:11:31) | INFO: Logger set to DEBUG
2024/12/04 (06:11:31) | DEBUG: Using locale en_GB.utf8
2024/12/04 (06:11:31) | INFO: Running on /dev/pts/1
2024/12/04 (06:11:31) | DEBUG: Shared::init() : Initialized.
2024/12/04 (06:11:35) | WARNING: get_cpuHZ() : Failed to read /sys/devices/system/cpu/cpufreq/policy and /proc/cpuinfo.

2024/12/04 (06:14:45) | ===> btop++ v.1.4.0
2024/12/04 (06:14:45) | WARNING: get_cpuHZ() : Failed to read /sys/devices/system/cpu/cpufreq/policy and /proc/cpuinfo.

2024/12/04 (06:15:39) | ===> btop++ v.1.4.0
2024/12/04 (06:15:39) | WARNING: get_cpuHZ() : Failed to read /sys/devices/system/cpu/cpufreq/policy and /proc/cpuinfo.
```

**Comment by aristocratos** [comment]
@danie-dejager 
Should be fixed as of commit b52069c
